### ISSUE TITLE
Bug: Certain RPC Servers cause major slowdown to Host machine

### ISSUE THREAD

**Issue by GoudaCouda** [ggerganov/llama.cpp#10047]
### What happened?

Version on all 3 Machines:3978 (ff252ea4)  I just used Git pull and updated to all 3 machines and then rebuilt the cmake.All the machines are on ethernet.I am not sure if it is normal but I also feel like using the 6700xt should be giving me more than an extra 3 t/s but i am not sure about that.
M1:4070 Laptop; CUDA; Host
M2: 1070;CUDA  
M3: 6700xt;hipBLAS

When I include Machine 2 in my llama-bench it slows down by token speed like 500%. I can post the Bench results below for the machine combinations.

Parameters

-p "You are a helpful Assistant" -ngl 200000 -n 50 -rpc

Only M1

| model                          |       size |     params | backend    | ngl |          test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | -------------------: |
| qwen2 ?B Q5_K - Small          |   4.94 GiB |     7.62 B | CUDA       | 200000 |          tg50 |         44.66 ± 0.17 

M1+M3

  Device 0: NVIDIA GeForce RTX 4070 Laptop GPU, compute capability 8.9, VMM: yes
| model                          |       size |     params | backend    | ngl |          test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | -------------------: |
| qwen2 ?B Q5_K - Small          |   4.94 GiB |     7.62 B | CUDA+RPC   | 200000 |          tg50 |         35.25 ± 0.35 

M1+M2+M3

| model                          |       size |     params | backend    | ngl |          test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | -------------------: |
| qwen2 ?B Q5_K - Small          |   4.94 GiB |     7.62 B | CUDA+RPC   | 200000 |          tg50 |          9.56 ± 0.62 

### Name and Version

M1

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4070 Laptop GPU, compute capability 8.9, VMM: yes
version: 3978 (ff252ea4)
built with MSVC 19.41.34120.0 for x64

M2

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 6700 XT, compute capability 10.3, VMM: no
version: 3978 (ff252ea4)
built with  for x86_64-pc-windows-msvc

M3:

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1070, compute capability 6.1, VMM: yes
version: 3978 (ff252ea4)
built with MSVC 19.41.34123.0 for x64

### What operating system are you seeing the problem on?

Windows

**Comment by GoudaCouda** [comment]
I have 1gbps internet on all machines.I dont understand why it seems to just make them all slower

**Comment by Allan-Luu** [comment]
I believe it has something to do with the concept of RPC itself.

When llama.cpp is built without RPC addition and no layers are being offloaded onto the RPC backends, there's no need for additional communication to the servers. The data transfer over a network will definitely be slower than local data transfer, which is why we may see performance drops when trying to utilize both local + remote communication. When dealing with data transfer on local communication, there's a quicker response time by the machine. 

I was testing this out and saw the same performance drop, and how it made sense to me with offloading to GPU is on the local machine, it will process all the data, then because the RPC backends have to be spun up on each individual GPU, the communication would go from machine 1 (M1) CPU talks to M1 GPU, M1 GPU sends data back to M1 CPU, then M1 CPU transfers data to machine 2 (M2) CPU for processing, M2 CPU transfers to M2 GPU, then M2 GPU back to M2 CPU, and finally back to M1 CPU.

If there were more than 1 RPC backends then it would do this process for each individual GPU, from M1 CPU to M2 CPU to M2 GPU1 to M2 CPU back to M1 CPU, then all the way back to M2 GPU 2.

To mitigate this issue we may need to look into the way the RPC function is developed.

**Comment by Essamara** [comment]
I upgraded to 2.5Gb Ethernet and it isn't saturating the whole band.

I cant notice any other bottlenecks on any of the RPC network computers

So i was thinking it might have been the CUDA or the way RPC is handled .... Allen (above) gave me some answers, this polling of VRAM
