### ISSUE TITLE
Feature Request: Add "tokens per second" information in the Web UI

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#10502]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

The client should display prompt processing and text generations speeds.

### Motivation

I helps to investigate how different parameters affect the performance

**Comment by david68cu** [comment]
Hi Maintainers,

I want to take ownership of this issue and work on resolving it. I’ve reviewed the CONTRIBUTING.md file and familiarized myself with the project structure and guidelines.

If there are any specific details or considerations I should keep in mind while working on this, please let me know. Otherwise, I’ll take the necessary steps to address this issue effectively.

Could you please assign this issue to me?

Thanks,
David

**Comment by slaren** [comment]
I believe this is already being worked on in #10548

**Comment by david68cu** [comment]
Thanks @slaren

**Comment by lhpqaq** [comment]
@david68cu I only added the backend API in #10548, maybe you can continue to implement the frontend.

**Comment by ngxson** [comment]
This can ideally be added after https://github.com/ggerganov/llama.cpp/pull/10599 and https://github.com/ggerganov/llama.cpp/pull/10548 to avoid conflicts
