### ISSUE TITLE
Too many releases

### ISSUE THREAD

**Issue by L3P3** [ggerganov/llama.cpp#1055]
Every second entry in my timeline is a new anonymous, automatical release of this project, please only post releases less frequently...

**Comment by FNsi** [comment]
Somehow in my view it's better to keep more releases so we can figure out where the problems coming from.

**Comment by L3P3** [comment]
I think there should be a place where there is always the newest binaries only and there is no point in having a release for every single commit. There is a commit history for that.

**Comment by ggerganov** [comment]
Lets fix this - I can see it being annoying.
Any suggestions?

**Comment by Technetium1** [comment]
It's really hard to say nicely how much I **_hate_** the basis of this issue. If you don't want updates, don't follow the project. If you want to follow, but not be notified of releases, then it's your responsibility to set it as such: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#configuring-your-watch-settings-for-an-individual-repository
![image](https://user-images.githubusercontent.com/9877150/233714189-0a34c02e-ee23-4f65-b15e-8a640dc6f523.png)

The project shouldn't have to suffer because of unset custom follow settings. The feed is full of _what you've requested it be filled with_. There should *NOT* be delays in releases on the basis of a cluttered feed, that's a user issue not a CI one. Stretching out releases will only hamper development efforts, and make it that much harder for someone to easily download and run various [and especially the newest] revisions.

---

Re @j-f1:
> keeping binary artifacts around forever means people may accidentally download an old version without realizing it

I disagree as I've never had that issue. Also, the latest release is always marked as such, along with a timestamp and brief description. If that weren't the case, I could understand a small confusion specifically when trying to download an older version.

**Comment by j-f1** [comment]
This is what I’m referring to in terms of noise:

<img width="757" alt="Screenshot_2023-04-21 15 11 29" src="https://user-images.githubusercontent.com/25517624/233716291-76394b83-027a-4d48-9d36-04ececb8a436.png">

**Comment by slaren** [comment]
That's what I have been doing as well. If it is simply an issue that people aren't aware that it is possible to disable notifications about new releases, I agree that there is no need to change anything. Have frequent releases allow us to receive more feedback.

**Comment by ggerganov** [comment]
I wasn't aware one can disable release notifications separately.
If so - then it is not an issue

**Comment by Technetium1** [comment]
@j-f1 I recommend you send feedback for the beta feature you're using in that case, especially if you've set custom notification settings already.

**Comment by flesnuk** [comment]
For me seems the feed comes from starring the project, you can also try clicking the 3 dots and telling github to not notify you so much 😃 
![chrome_AnpQ6UKTTc](https://user-images.githubusercontent.com/11600634/233785860-98877427-759b-4277-96e1-ef5decb3c289.gif)

**Comment by L3P3** [comment]
> It's really hard to say nicely how much I **_hate_** the basis of this issue. If you don't want updates, don't follow the project. If you want to follow, but not be notified of releases, then it's your responsibility to set it as such: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#configuring-your-watch-settings-for-an-individual-repository ![image](https://user-images.githubusercontent.com/9877150/233714189-0a34c02e-ee23-4f65-b15e-8a640dc6f523.png)
> 
> The project shouldn't have to suffer because of unset custom follow settings. The feed is full of _what you've requested it be filled with_. There should _NOT_ be delays in releases on the basis of a cluttered feed, that's a user issue not a CI one. Stretching out releases will only hamper development efforts, and make it that much harder for someone to easily download and run various [and especially the newest] revisions.
> 
> Re @j-f1:
> 
> > keeping binary artifacts around forever means people may accidentally download an old version without realizing it
> 
> I disagree as I've never had that issue. Also, the latest release is always marked as such, along with a timestamp and brief description. If that weren't the case, I could understand a small confusion specifically when trying to download an older version.

The thing is, I _want_ to be notified when there are major releases! But not on every 2 lines changed somewhere! Sure, I could unfollow and whatever but I think it is my good right to communicate the fact that I want to be notified on major releases and not on every single damn commit, sorry.

**Comment by Green-Sky** [comment]
> The thing is, I want to be notified when there are major releases!

hackernews will do that for you :laughing:
