### ISSUE TITLE
Support for Minigpt-4?

### ISSUE THREAD

**Issue by spikespiegel** [ggerganov/llama.cpp#1069]
Minigpt-4 is recently released, which is a multimodal model capable of handling both text and image inputs (similar to GPT-4, but this is built by Vicuna-13b and Blit2). From their demo, the model looks very capable! It seems to handle image inputs pretty well. Unfortunately, it currently runs only on GPU, and seems to require 24GB of VRAM.

[Minigpt-4 Github Page](https://github.com/Vision-CAIR/MiniGPT-4)

I am wondering if it is possible to run it on CPU? Also, do you think 4-bit quantization is possible? Vicuna-13b works very well with 4-bit quantization, but I have no idea if the inclusion of Blit2 changes anything, or is it even possible to make a quantization at all. I feel like it would be great if somehow the CPU version could be developed. Thanks!

**Comment by cmp-nct** [comment]
Doesn't really fit into llama.cpp which should be ggllm.cpp anyway. All the core is for language processing and the evaluation is for the currently typical transformers (for tokenized text).

In my personal opinion it's the wrong approach to stick large language models on top of blip image analysis, as long as our processing hardware is so limited that sounds very wasteful to me while making updates and changes very difficult.
Better to have it in two steps, one the image specialist and one the language specialist. with real language in between.
This way you can update both ends as better opportunities come up and choose the right model for the right task.
But that's just how I feel about this, if I were Microsoft of Google or Facebook I'd want it stuffed together because I have unlimited free computing resources.

**Comment by Maknee** [comment]
> Minigpt-4 is recently released, which is a multimodal model capable of handling both text and image inputs (similar to GPT-4, but this is built by Vicuna-13b and Blit2). From their demo, the model looks very capable! It seems to handle image inputs pretty well. Unfortunately, it currently runs only on GPU, and seems to require 24GB of VRAM.
> 
> [Minigpt-4 Github Page](https://github.com/Vision-CAIR/MiniGPT-4)
> 
> I am wondering if it is possible to run it on CPU? Also, do you think 4-bit quantization is possible? Vicuna-13b works very well with 4-bit quantization, but I have no idea if the inclusion of Blit2 changes anything, or is it even possible to make a quantization at all. I feel like it would be great if somehow the CPU version could be developed. Thanks!

It's released here: https://github.com/Maknee/minigpt4.cpp

**Comment by ggerganov** [comment]
@Maknee This looks very clean! I haven't ran it yet but I looked around the repo and it seems well done. Some good usage of CMake too.
