### ISSUE TITLE
Misc. bug: Some server response JSON still not restored

### ISSUE THREAD

**Issue by CentricStorm** [ggerganov/llama.cpp#10728]
### Name and Version

version: 4291 (ce8784bd)
built with MSVC 19.29.30157.0 for x64

### Operating systems

Windows

### Which llama.cpp modules do you know to be affected?

llama-server

### Problem description & steps to reproduce

After #10722, there are still some issues when using the native `/completion` endpoint:
- The `has_new_line` property is set to `1` instead of `true` like it used to be.
- The `model` property is set to `gpt-3.5-turbo-0613` even though this isn't the OpenAI-compatible API.

**Comment by ggerganov** [comment]
PRs welcome

**Comment by MichelleTanPY** [comment]
Hi @ggerganov , I saw the 'good first issue' tag on this.  I'm new to this project and thought to give this a try. I manage to build the llama-server, but I'm getting this strange error when get the server up and running. 
I'm following the README here : https://github.com/ggerganov/llama.cpp/tree/master/examples/server and getting the following error.
`llama_model_load: error loading model: missing tensor 'token_embd.weight'
llama_load_model_from_file: failed to load model
common_init_from_params: failed to load model '.\models\ggml-vocab-deepseek-llm.gguf'
srv    load_model: failed to load model, '.\models\ggml-vocab-deepseek-llm.gguf'
main: exiting due to model loading error`
Any pointers on how I should proceed?  Building with MSVC 19.42.34435.0 x64 Windows machine.

**Comment by ngxson** [comment]
> * The `model` property is set to `gpt-3.5-turbo-0613` even though this isn't the OpenAI-compatible API.

This is to prepare for adding OAI-compat to `/v1/completions` endpoint. If you're searching for the model path, please have a look at `/props` endpoint
