### ISSUE TITLE
Misc. bug: Server Demo on Mac, safari return error

### ISSUE THREAD

**Issue by DickyQi** [ggerganov/llama.cpp#10841]
### Name and Version

5478bbcd

### Operating systems

Mac

### Which llama.cpp modules do you know to be affected?

llama-server

### Problem description & steps to reproduce

1. build on MacBook Pro 16 inch 2019,
2. run server demo
3. open safari browser with localhost:8080
4. type 'hello'

### First Bad Commit

browser popup error dialog with message: "TypeError:r is not async iterable"

### Relevant log output

```shell
srv  update_slots: all slots are idle
```

**Comment by bakkot** [comment]
From a quick glance at the code I would guess this is because of [these lines](https://github.com/VJHack/llama.cpp/blob/9fdb1243049aa7e8211693f116daf2052d47507d/examples/server/webui/src/main.js#L244-L247) introduced in #10786 by @ngxson. That relies in ReadableStream being async iterable, which is [not yet implemented in Safari](https://bugs.webkit.org/show_bug.cgi?id=194379).
