### ISSUE TITLE
Bug: Empty response in interactive mode or incomplete answer

### ISSUE THREAD

**Issue by batmanonline** [ggerganov/llama.cpp#1133]
When running with the -t 12 -i -r "### Human:" flags llama returns control
the cpu activity goes to 0 and the user sends a new input
however, llama now continues responding to the previous input (or returns no response) completely ignoring the new input...

from here llama completely breaks the chat, it even generates the prompt "### Human:" and starts completing the questions written by a human

Using the --ignore-eos does not help, llama keeps stopping randomly.

Note: tested this many times with vicuna and gpt4all
Note: this might be related to issues https://github.com/ggerganov/llama.cpp/discussions/990 https://github.com/ggerganov/llama.cpp/issues/941 https://github.com/ggerganov/llama.cpp/discussions/993

**Comment by slaren** [comment]
If you have a way to reproduce this reliably, it would be easy to find the problem.

**Comment by slaren** [comment]
The problem may be that you are reaching the token limit. Try adding `-n -1 -c 2048` to allow for longer responses.

However, we should probably re-evaluate the behavior of the token limit with interactive mode, as it can be very confusing when this happens. Maybe at least we could inject the anti-prompt, otherwise the input of the user will added in the middle of the response, and if the user doesn't realize this and tries to enter another question, without the anti-prompt the model will just take it as part of its response and produce nonsense.
