### ISSUE TITLE
Feature Request: Attention with Linear Biases (ALiBi)

### ISSUE THREAD

**Issue by loretoparisi** [ggerganov/llama.cpp#1137]
Consider to implement Relative Position Embeddings as opposite to APEs, as described in [Train Short, Test Long: Attention with Linear Biases Enables Input Length Extrapolation](https://arxiv.org/abs/2108.12409)

Short summary:

Attention with Linear Biases (ALiBi) does not add positional embeddings to word embeddings; instead, it biases query-key attention scores with a penalty that is proportional to their distance

Source: 
[The Use Case for Relative Position Embeddings](https://ofir.io/The-Use-Case-for-Relative-Position-Embeddings/)

Official implementation [here](https://github.com/ofirpress/attention_with_linear_biases).

Worth to read:
[The Curious Case of Absolute Position Embeddings](https://arxiv.org/abs/2210.12574)

**Comment by aljungberg** [comment]
Sure, APE is probably a mistake. I like ALiBi and I think it's a convincing paper. That said I'm not sure what you're asking for here.

Llama doesn't use absolute positioning embeddings (in fact the last paper you posted had 3 authors from Facebook, so they know). Llama uses another form of relative positioning, rotary position embeddings. You can argue about whether rotary embeddings are fully relative [1], but even if you take the view they're not... What are you actually proposing? Llama wasn't trained with ALiBi so llama.cpp can't just switch the embedding scheme for another. Even small differences in the rotary embedding implementation can [negatively affect perplexity](https://github.com/huggingface/transformers/blob/3d3204c025b6b5de013e07dd364208e28b4d9589/src/transformers/models/esm/convert_esm.py#L229).

[1]: Press writes in your second link that "Rotary simply element-wise multiplies position representations by the word representations (instead of adding position reps to word reps, as is done in the absolute methods). This means that Rotary still employs position embeddings, which in my view makes it an absolute position method, not a relative one."

Maybe there's a longer form of his argument, but I don't get it as written. The RoFormer paper goes to great lengths to derive a function that encodes only relative information, `g(xm, xn, m-n)`. What they come up with is basically to 2D rotate the embeddings vectors by `position*theta` (and then generalise it to higher dimensions). So between two tokens at `m` and `n`, you get a relative difference in rotation. Yes, you get an absolute rotation as well based on token position, but it's erased in the self-attention weighting. The dot product between two vectors is a function of the magnitude of the vectors and the angle between them. Since we use the dot product for attention weighting, the absolute rotation "disappears" and only the relative difference in rotation makes a difference.

I respect that Press et al did the work and actually show that while rotary embeddings extrapolate better than absolute sinusoidal, T5 Bias and ALiBi are even better. But I don't think the Train Short, Test Long paper actually makes the argument that this is because rotary embeddings fail to be relative? I mean it could just as well be that rotary embeddings are relative, just not very good for the kind of and amount of training the paper tested. (Personally I have a suspicion about where RoPE goes wrong but I don't want to sound silly in case I'm wrong and besides I'm digressing.)

I guess with BLOOM using ALiBi but not being a super strong model, the jury is still out.

**Comment by ofirpress** [comment]
Yup there's no reason to implement ALiBi here, Llama doesn't use ALiBi.

Figure 1 in ALiBi shows that RoPE simply doesn't perform well and I am not aware of any results in other papers that contradict this (but of course, happy to change my mind if someone runs new experiments and shows different results).

**Comment by loretoparisi** [comment]
Thank you @aljungberg for your detailed insight, that was really helpful, I was not aware of these "pseudo positional" embeddings in LlaMa. Closing then as "unrelated" at this stage.

**Comment by ofirpress** [comment]
Seems like people are now interested in using ALiBi-powered models with this library? https://www.reddit.com/r/LocalLLaMA/comments/133vfk3/i_recently_tested_the_mpt_1b_redpajama_dolly/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&utm_content=1&utm_term=15

**Comment by ggerganov** [comment]
`ggml_alibi()` has been added recently https://github.com/ggerganov/ggml/pull/113

**Comment by loretoparisi** [comment]
Thanks to Alibi, it has been reported that MosaicML reached 65k context window size with the latest release of the MPT family model `MPT-7B-StoryWriter`

https://huggingface.co/mosaicml/mpt-7b-storywriter

that's pretty much impressive to me.
