### ISSUE TITLE
It's strange to return after executing the command

### ISSUE THREAD

**Issue by Chting** [ggerganov/llama.cpp#122]
./main -m ./models/7B/ggml-model-q4_0.bin -t 64 -n 256 --repeat_penalty 1.0 --color -i -r "User:" -p 'What is your name?'
![image](https://user-images.githubusercontent.com/17468133/224920438-696f3b65-bc7c-42d9-ab10-a46b686dcb47.png)
Is it because I haven't installed something？
Centos 7

**Comment by gjmulder** [comment]
That's normal behaviour currently. People are working on chat interfaces and Python bindings.

**Comment by Chting** [comment]
Why can't I talk like chatgpt  after executing the command according to the prompt

**Comment by gjmulder** [comment]
Because it is not ChatGPT. The command line interface was provided as a simple way to get the model up and running.

Check out [dalai llama](https://github.com/cocktailpeanut/dalai) for a quick way to get the 7B model running using Node.js

**Comment by G2G2G2G** [comment]
Not sure what these other responses are.
You're not actually giving it any input to know wtf you are talking about, so it is not going to type "User:" ever
make a text.txt file

copy this into it:
```
Bob is a helpful AI chatbot that always provides useful and detailed answers to User's requests and questions.
User: Hi. Can you help me with something?
Bob: Hello this is Bob. How can I help?
User: What is the square root of 625?
Bob: 25. The square root of 625 is 25.
User: How hot is the lava in a volcano?
Bob: I can tell you that the temperature is between 700 and 1,200 degrees celsius.
User:
```

```
./main -m ./models/7B/ggml-model-q4_0.bin -t 64 -n 256 --repeat_penalty 1.0 --color -i -r "User:" -p 'What is your name?'
```
this is your command, change it to:
```
./main -m ./models/7B/ggml-model-q4_0.bin -t 64 -n 1024 --repeat_penalty 1.0 --color -i -r "User:" -f 'text.txt'
```
(note we now use the file as input instead of your prompt) (also made your -n bigger)
feel free to change the prompt and in the initial line you can give it a different personality and give it different answers to different questions (maybe you want to make it into an asshole instead of helpful bot, for example)

keep in mind due to issue #71 these prompts will have to be short, but ideally you can input massive files so it is super fine tuned.


also wtf is with your -t, are you sure you have 64 threads and the memory bandwidth for that? it prob only needs like -t 8 lmao

**Comment by levicki** [comment]
@G2G2G2G Is there some limit on the interactive mode? Mine keeps exiting after one or two user prompts.
