### ISSUE TITLE
[BUG]The new master ClBLas generate garbage text

### ISSUE THREAD

**Issue by FNsi** [ggerganov/llama.cpp#1417]
Opencl version, While the Q5_1 ~~vicuna~~ using -f load any exist prompt file in prompt/ will always turn to generate garbage result.

**Comment by FNsi** [comment]
I observe that if there's only one speaker it works fine.

**Comment by mqy** [comment]
Current CLBlast implementation uses many global variables (context, queue, buffers, ...), so it  can be used with multi sessions.

BTW, I just got an error  when testing [my branch](https://github.com/ggerganov/llama.cpp/compare/master...mqy:llama.cpp:clblast_blocking_mode) on new ggml 7B q4_0.

./example/chat.sh
...
User:OpenCL clEnqueueWriteBuffer b error -30 at ggml-opencl.c:283

Because I haven't fully test my codes before upgrading model, so not sure what's wrong with it. I had created a test file that do mumat with fixed N/K (from model 7B and 13B) and variable M (16 up to 256), no crash.

**Comment by SlyEcho** [comment]
@mqy, I don't exactly know what the problem is in your code but wouldn't it be better to just use the variable `is_blocking_queue` instead of `CL_FALSE` to determine if a CL command is blocking or not, instead of duplicating the code?

**Comment by mqy** [comment]
> @mqy, I don't exactly know what the problem is in your code but wouldn't it be better to just use the variable `is_blocking_queue` instead of `CL_FALSE` to determine if a CL command is blocking or not, instead of duplicating the code?

@SlyEcho  Thanks!

My OS is Darwin, device is: Intel(R) UHD Graphics 630 which is a weak CPU integrated graphics card.
Because the default out of order queue failed to create with this GPU, I'm falling back to blocking queue.

I'll try https://github.com/ggerganov/llama.cpp/pull/1422 then cleanup my codes.
