### ISSUE TITLE
How to output the ggml file with Lora merged?

### ISSUE THREAD

**Issue by FNsi** [ggerganov/llama.cpp#1449]
I think the Lora is applying while do the ggml_graph_comput(lora_ctx, &gf)

What should I do to to output a full ggml file include the llama + merged lora?

I don't think that will work by simply modify Llama_apply_lora_from_file_internal by adding a parameter uint_8 *dst...

Is there any reverse way to turn it to a full ggml file or a way to copy it out from ram?

**Comment by slaren** [comment]
Currently, there isn't any way to create pre-merged models with llama.cpp. If you need to do this, you can merge it with pytorch/PEFT and then convert the merged model to ggml.

Supporting this wouldn't be too hard, we could add a function to save a loaded model to disk that you could use after applying the LoRA, but each API adds complexity and more code to maintain, and am not convinced that we really need this. Is there any reason to do this with llama.cpp instead of using python to merge the LoRA?

**Comment by FNsi** [comment]
> Currently, there isn't any way to create pre-merged models with llama.cpp. If you need to do this, you can merge it with pytorch/PEFT and then convert the merged model to ggml.
> 
> 
> 
> Supporting this wouldn't be too hard, we could add a function to save a loaded model to disk that you could use after applying the LoRA, but each API adds complexity and more code to maintain, and am not convinced that we really need this. Is there any reason to do this with llama.cpp instead of using python to merge the LoRA?

it's a idea from my instinct, I think that would be more direct if we can get the quantised model with Lora in one step, without transfer llama weight to HF or download huge files from hugging face again and again. 

The most important reason I am trying to do it is because I want to merge multi loras without pth-hf-ggml with lower memory requirements, like do it in a 32gb laptop. So more loras merging would be tested like wildfire.

For example currently I am using  wizard-vicuña + Lora: evol-starcoder and I find it's very useful! Somehow crazy it can do large numbers calculations right (still sometime wrong), and yes, it can read the code and tell me what exactly the code do. That just show me a simple truth: 

more Loras could lead to more productivity. 

And as we know so far, those models training data size are not reaching saturate point, and that make loras can lead to almost perfect model, with the full potential of all those parameters. 

That's the reason I would like to know how to do it directly with llama.cpp, lower the boundaries, more people join in, and finally may creat an incredible model.

**Comment by iplayfast** [comment]
I too would think this is useful only because I'm learning llama.cpp and want to concentrate on it. the idea of merging with pytorch/peft, suggests that this would be possible, but you don't know what you don't know. I certainly didn't even know to look at peft (whatever that is!). Having the API available in llama.cpp means I would have found it.  I understand the reluctance to add additional API's but I really feel this would be useful, and one I've looked for before in llama.ccp.
