### ISSUE TITLE
Q4_1 inference appears broken for 13B parameters

### ISSUE THREAD

**Issue by blackhole89** [ggerganov/llama.cpp#152]
I have been experimenting with q4_1 quantisation (since [some preliminary results](https://nolanoorg.substack.com/p/int-4-llama-is-not-enough-int-3-and) suggest it shold perform better), and noticed that something about the pipeline for the 13B parameter model is broken (whether it is the quantization itself, or the saving or loading). This results in all inferred tokens coming out as `#`. Meanwhile, 7B works well.

I know we had a patch a while ago that first made the 13B+ models work for q4_0 - did whatever fixes it made not cover q4_1?

**Comment by tisfeng** [comment]
Yes, I use the 13B model and it doesn't work properly for either chatting or tasks. It simply ends without any response, which is very confusing to me.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/25194972/225215333-1314db35-8a03-456b-9e6f-2b903095169c.png">

**Comment by ggerganov** [comment]
First - great work!

Most likely the cause is that when I changed the `Q4_0` scaling storage, I skipped the `Q4_1` routines:

https://github.com/ggerganov/llama.cpp/commit/007a8f6f459c6eb56678fdee4c09219ddb85b640

This change was necessary to make larger model works, because when we merge rows from different shards, the scaling factors have to be next to the integer quants. Originally, what happened, is the scaling factors of a row, ended up at the start of the memory buffer, before all the int quants, and this caused the merging in `main.cpp` to fail.

**Comment by tisfeng** [comment]
I didn't use `-NDEBUG`, I am a newcomer to this, just converted the  13B model using the latest code from the main branch，no errors were reported during the conversion. 

```
make -j && ./main -m ./models/13B/ggml-model-q4_0.bin -p "What is the best programming language in the world? Why?" -t 8 -n 512
```

When using the 7B model, it works fine.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/25194972/225252039-bf7a1882-ddc2-4717-9476-1ab466f3d4c5.png">

**Comment by blackhole89** [comment]
In 13B Q4_1 mode:

![image](https://user-images.githubusercontent.com/401380/225465813-717c0bba-6322-409e-94de-c1d02a02f470.png)

I think it seems to work now, so I might make a PR against the main repository.

**Comment by tisfeng** [comment]
Great, thank you!
