### ISSUE TITLE
Cmake file always assumes AVX2 support

### ISSUE THREAD

**Issue by diwu1989** [ggerganov/llama.cpp#1583]
When running `cmake` the default configuration sets AVX2 to be ON even when the current cpu does not support it.
AVX vs AVX2 is handled correctly in the plain makefile.

For cmake, the AVX2 has to be turned off via `cmake -DLLAMA_AVX2=off .` for the compiled binary to work on AVX-only system.

Can we make the cmake file smarter about whether to enable or disable AVX2 by looking at the current architecture?

**Comment by howard0su** [comment]
check this #809

**Comment by chen369** [comment]
This issue is causing an issue downstream on "llama-cpp-python" where we cant build a python binding on non supported AVX2 machines that require cuBLAS support. 
Please read my work arround on here https://github.com/abetlen/llama-cpp-python/issues/272#issuecomment-1566224179
Best Regards,

**Comment by happysmash27** [comment]
As per my now-closed issue #1654  (currently closed by me because I figured out the workaround and wasn't sure if default configuration qualified as a "bug"), it assumes a bunch of other extensions as well: AVX, F16C, and FMA. It took me a while to figure out what the flags to disable them were and then add them one by one until it finally worked.

**Comment by TFWol** [comment]
Anyone have a straight forward way to get the combo of **CUDA + no AVX2** to work?
My head is spinning from trying to follow all these threads.
