### ISSUE TITLE
Question: can the conversation context be saved to disk and brought up again incase LLaMa crashes or there is a power failure?

### ISSUE THREAD

**Issue by nazthelizard122** [ggerganov/llama.cpp#174]

**Comment by jart** [comment]
Thank you for using llama.cpp and thank you for sharing your feature request! You'll be excited to hear that what you're requesting is my top priority right now. I'm using https://github.com/ggerganov/llama.cpp/issues/91 as the best place to discuss this, since the solution will entail using mmap(). Everyone is welcome to participate in helping us find the best solution. I believe mmap() will reduce startup latency to effectively zero, for everyone, and it'll work on nearly every platform on earth, including Windows, which has a nearly equivalent API.
