### ISSUE TITLE
Sharing a link to some research on quantization referencing llama.cpp

### ISSUE THREAD

**Issue by snichols** [ggerganov/llama.cpp#2163]
https://arxiv.org/pdf/2307.03738.pdf

> The results are shown in Fig. 4. We observe that our kernels outperform llama.cpp in terms of throughput, by up to 2.6× when using full columns on the 13 billion parameter model, and by approximately 2× when using group implementations. However, we observed a lower performance than llama.cpp for the 30b case for group sizes 16 and 32. We believe that this is due to the assumptions we introduce to solve (5), and should be improvable by further examination

**Comment by JohannesGaessler** [comment]
They report 1.45 t/s for 33b q4_0 with llama.cpp which is absolutely terrible for an AMD EPYC 7742 with octa channel DDR4 memory. You should be getting at least 6 t/s using that hardware and that would make llama.cpp about twice as fast as their implementation. So all I've learned from that paper is that the authors ran llama.cpp with very suboptimal settings.

**Comment by Azeirah** [comment]
There's not a lot pointing how to optimise llama.cpp's performance in the docs. How doable is it to find reasonably optimal settings for a system for an outsider who only reads the readme but not the issues?

I really think this project either needs a wiki or a script that tries to automatically find optimal settings.

**Comment by JohannesGaessler** [comment]
Sorry, but if they're going to release a research paper it's their own responsibility to research the things that they write about. Even if the project itself does not have sufficient documentation it would have taken them all of five minutes to email one of the developers and ask them whether the performance numbers match expectations. Also memory bandwidth is the single most important factor for token generation performance and it's very telling that they didn't think that this number would be important to include in the paper. 

If I had to guess they were probably gimping the performance by using Python bindings (which are outside the control of this repository). So all it would have taken for them to realize their mistake would have been to run the main binary directly. If the problem was instead that they had too much overhead from spinning threads then they only would have had to try running the program with half the number of threads (which is a very obvious thing to try for I/O bound applications). 

For what it's worth, I agree that there is not enough documentation regarding how to get good performance. That's why I started a [Github page about llama.cpp performance](https://johannesgaessler.github.io/llamacpp_performance).

**Comment by Azeirah** [comment]
Oh I agree, the comment was meant to be more in general. Not specific to this issue per sé.

**Comment by SlyEcho** [comment]
We also have some docs like this one: [docs/token_generation_performance_tips.md](https://github.com/ggerganov/llama.cpp/blob/master/docs/token_generation_performance_tips.md).

I think another factor that could also be missed is the mmap performance slowdown in some specific setups. If that server maps the user's data to an NFS share, for example, then loading and running the model will be super slow. Same thing in WSL when the model is in the Windows C: drive. Same thing in macOS when the machine is a lower-tier 8GB model (need mlock).
