### ISSUE TITLE
Use date as version

### ISSUE THREAD

**Issue by Freed-Wu** [ggerganov/llama.cpp#2292]
Can this project use date as version like `2023.7.1`? currently, `master-XXXXXX` cannot compare which version is newer. but date can: `2023.7.1` is newer than `2023.6.29`. It is convenient for the packager to compare which version is newer.

Related: <https://github.com/termux/termux-packages/pull/17457>

**Comment by mxcl** [comment]
@teaxyz would also appreciate this.

Since every push to master triggers a release this would mean some days have multiple releases however. We could do calver+time to mitigate.

Prefacing the next thing I'm saying with: I totally understand why releases are cognitive overhead—ideally the project would migrate to real releases. Start at v0.0.1 by all means!

**Comment by DannyDaemonic** [comment]
There's already a header generated containing a "build" number based on the current commit. When you run `main` you see it as:
```
main: build = 852 (294f424)
```
or:
```
main: build = 867 (ab0e26b)
```

I wonder if this build number could be used somehow instead. Using larger numbers like these isn't unheard these days, for example, with projects like Firefox.
