### ISSUE TITLE
Speed too slow 

### ISSUE THREAD

**Issue by Fcucgvhhhvjv** [ggerganov/llama.cpp#2444]
i compiled llama.cpp in two different phones by cloning this repo and doing make . i got two phones moto g72 and poco x3 pro , poco x3 pro having better cpu that moto g72 works slower than moto g72 . i tested wizardvicuna 7b q_2k  model in both and my poco x2 pro only generates 0.20 token per second meanwhile moto g82 is close to 1 token per second . i compared both the speed and found that moto g72 speed can be conpared to when chat gpt was new . it not the models i tested Pygmalion 7b q_2k in both the phones and the result was same .

**Comment by HansvanHespen** [comment]
With me , the pseed is also too slow, but cmpletely differently, since I'm not hosting on a phone, but on my Windows 11 laptop. Thinkpad, i7 8550u, 32 GB RAM, 1TB SSD, Geforce MX150 2GB VRAM. The 7B llama model takes about 6 minutes on CPU only, now that I have installed NVCC, the new langchain .237 and llama.cpp with CUBLAS=ON, the model finally works with my GPU. 

I understand my small laptop graphics card is not an A100, so I wasn't expecting answer in seconds from my model, yet five to ten times faster as with my 8-core cpu. 

Big was my surprise that with the GPU, results are coming back in 25 to 60 minutes, instead of 6 minutes with the CPU only. I tried a lot of variations: offloading only one layer, so that I do not get out of the VRAM, The GPU is then used for about 4%, offloading 15 layers of the 35, that makes my GPU using about 70%, the full 35 layers, which means that my graphics card is using the normal RAM, moving up the n_batch to 1000, moving up the n_threads to 50, playing with the top_k and top_p values, the fastest I can get it is about 12 minutes, still double the time with CPU only. The fastest effectively is gpu_layers=0.

Maybe it has to do with the fact that I'm also using torch with cuda, that seems to take up quite some VRAM memory. But then I still should see some improvement with only one layer. 

Getting llama-cpp-python installed was a nightmare by the way. It first deinstalls numpy and typing, reinstalls it with the latest version (numpy 1.25) and stops afterwards when it wants to reinstall tensorflow-intel that requires numpy <1.24. Installing numpy 1.24 manually, gives a problem with chex, who wants numpy >= 1.25. 

I ended up by forcing a manual install of chex 1.7.0, then manually install numpy and typing, and do a normal not forced reinstall on llama-cpp-python. 

The model still didn't indicate BLAS, however, and that was then solved by upgrading lanchain from version 234 to 237. Suddenly it worked. I spent the whole night on it, only to discover that the model works even slower. 

That is ennoying for me to test, because I have to wait on every question six minutes, and I wonder if I want to bring my soft in production, if it will work without having to run it on a supercomputer. At a price of £18K per A100, I can sell my house!

Some ideas, anyone? 

Why does it go slower with the GPU, is that because of the slow PCI connection between the gpu and the cpu? I have the feeling that something is bottlenecking here. I can understand that if you have to move the ggml data over the pci to the gpu, that that is slow, but once the data is in the GPU, sending over the question, a bunch of what, 200 tokens or numbers, and receiving an answer back of 512 tokens max, is surely not staurating the PCI and does not count for 50 minutes of calculation. By the way, when all the gpu layers are offloaded on the gpu, the CPU still works at 100 %. 

This is the model verbose that I get in the terminal:
Creating language model...
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce MX150, compute capability 6.1
llama.cpp: loading model from C:/Users/Hans/AppData/Local/llama/llama-2-7b.ggmlv3.q2_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 10 (mostly Q2_K)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  =  439.10 MB (+ 1024.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 384 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 4101 MB
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
Language model created: LlamaCpp
Params: {'model_path': 'C:/Users/Hans/AppData/Local/llama/llama-2-7b.ggmlv3.q2_K.bin', 'suffix': None, 'max_tokens': 512, 'temperature': 0.1, 'top_p': 0.0, 'logprobs': None, 'echo': False, 'stop_sequences': [], 'repeat_penalty': 1.1, 'top_k': 40}
after ask_worker.set_question(question)
after self.ask_thread.start()
ask called
> Entering new RetrievalQA chain...

What is the relation between llama_cpp of langchain and llama.cpp of Mr Gerganov? I started to install llama.cpp because of the explanation it is given in the langchain doc, but I have the feeling they they are not connected.

Thank you very much.

High regards,

Hans

![Screenshot 2023-07-31 124756](https://github.com/ggerganov/llama.cpp/assets/46969188/c6554c69-3120-47ad-a1ba-4ee2a54f2419)

**Comment by Fcucgvhhhvjv** [comment]
my android devices are very different from the brand android version cpu gpu , better deevice should work faster but what i found out from 2 days of testing is that the low end device works as if It was earlier version of chat gpt , it gave like 0.5-1 token/s while my better phone with snapdragon 860 gives 0.20token/second either its my cpu being old or something idk , please help me out.
