### ISSUE TITLE
LoRA GGML is 2x the size of the original LoRA when including all modules

### ISSUE THREAD

**Issue by kallewoof** [ggerganov/llama.cpp#2509]
A LoRA trained with all LoRA modules rather than only the q_proj and k_proj ones. Normally the ggml lora file is a few bytes different in size from the original adapter_model.bin file, but in this case, it was roughly 2x the size (adapter_model.bin 480 MB, ggml-adapter-model.bin 960 MB).

GGML was created as usual using convert-lora-to-ggml.py script.

**Comment by slaren** [comment]
The LoRA B weights are always exported as f32. The LoRA A weights are exported as f16 only if they are originally f16, otherwise they are converted to f32. So in some cases, it can result in all weights being exported as f32, for example if your LoRA is in bf16 format. This is due to a limitation in the data types that ggml can operate with.

**Comment by kallewoof** [comment]
I think you are spot on there. I think I trained bf16 this time, rather than f16. I didn't even think about that.

Should we discourage bf16 use then? It seems super wasteful to get 2x when we can get 1x.

**Comment by slaren** [comment]
I am not sure if training a LoRA as bf16 should be discouraged, my intuition is that for a LoRA precision would be more important than dynamic range, so f16 is probably the preferred type, but I don't know for sure. But even if you train the LoRA as f16, the ggml file is still going to be 1.5x the size, since half of the weights will be converted to f32. Usually this isn't much of a problem since most LoRAs are very small, but it's something that we should improve in the future.
