### ISSUE TITLE
[User] Optimizing llama.cpp using nvcomp

### ISSUE THREAD

**Issue by mikefaille** [ggerganov/llama.cpp#2607]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I expect llama.cpp to efficiently run large language models on commodity computers. To achieve this, I suggest utilizing the nvcomp library to compress and decompress data during memory transfers, which should improve the speed and efficiency of data transfer, especially for larger language models.

# Current Behavior

Currently, llama.cpp uses standard cudaMemcpy calls for transferring data between host and device memory. This may cause bottlenecks, especially when dealing with larger language models on commodity computers that don't have high-end GPUs.

# Reference

https://developer.nvidia.com/blog/accelerating-lossless-gpu-compression-with-new-flexible-interfaces-in-nvidia-nvcomp/

**Comment by klosax** [comment]
It would be great if this could work, as far as I know the main bottleneck is the memory transfer speed.

**Comment by JohannesGaessler** [comment]
I don't see how this would improve performance. The amount of data transferred with the CUDA backend is very small. If anything the issue is latency rather than bandwidth and compression + decompression would only make this worse. At most this would make startup a little faster and shave off ~1 second for 70b.

**Comment by KerfuffleV2** [comment]
LLM data tends to be very high entropy and doesn't compress well. I experimented and even very slow (but effective) algorithms like `xz` with max settings can barely achieve an 8-10% reduction. From the doc, it looks like this is just using ZIP's deflate which is a pretty old/simple algorithm (but fast).

If there actually was a way to get really good compression levels it would be useful (just not the way llama.cpp is implemented right now) because it could open up the possibility of dynamically streaming layers to the GPU instead of just having a set number of layers limited by GPU memory. Unfortunately I don't think there's going to be a way to achieve the necessary levels of compression.

**Comment by mikefaille** [comment]
Thank you for the feedback. It makes sense for me. I will close this PR then !

**Comment by xyproto** [comment]
An 8% reduction in memory usage would be very useful for running a model that requires 34 GiB of memory on a machine that only has 32 GiB of memory, though.
