### ISSUE TITLE
the program always terminate itself for no reasons 

### ISSUE THREAD

**Issue by yuanjv** [ggerganov/llama.cpp#275]

**Comment by yuanjv** [comment]
when I run llama.cpp with the alpaca model, the model always terminates mid-fight and starts to print something like:
main: mem per token = 14368644 bytes
main:     load time =  3370.70 ms
main:   sample time =   176.81 ms
main:  predict time = 38885.40 ms / 114.71 ms per token
main:    total time = 144166.59 ms

**Comment by j-f1** [comment]
There are a few reasons this could be happening:

- You have reached the token limit (it looks like you were at about 339 tokens, so I doubt this is the case)
- The model decided to end its output by sending an end of text token, which means that the response is finished and no more output will be provided. There isn’t a way to prevent this aside from modifying your prompt so that it doesn’t happen anymore. (There aren’t a ton of resources on how to do this yet).
- The program crashed. Since you got the final output, I doubt this is what happened.

**Comment by yuanjv** [comment]
> There are a few reasons this could be happening:
> 
> * You have reached the token limit (it looks like you were at about 339 tokens, so I doubt this is the case)
> * The model decided to end its output by sending an end of text token, which means that the response is finished and no more output will be provided. There isn’t a way to prevent this aside from modifying your prompt so that it doesn’t happen anymore. (There aren’t a ton of resources on how to do this yet).
> * The program crashed. Since you got the final output, I doubt this is what happened.

I tried 999999999 tokens. But it still did not go far.

**Comment by yuanjv** [comment]
I just commented out the code for program termination. Not the best fix but everything works now. lol
