### ISSUE TITLE
Unable to convert GGML to GGUF

### ISSUE THREAD

**Issue by sachinspanicker** [ggerganov/llama.cpp#2812]
I am unable to convert and getting this error. Any info appreciated. -

llama.cpp % python convert-llama-ggmlv3-to-gguf.py -i llama-7b.ggmlv3.q4_1.bin -o ./output.bin -m ./upstage --gqa 8 -c 4096

Using config: Namespace(input=PosixPath('llama-7b.ggmlv3.q4_1.bin'), output=PosixPath('output.bin'), name=None, desc=None, gqa=8, eps='5.0e-06', context_length=4096, model_metadata_dir=PosixPath('upstage'), vocab_dir=None, vocabtype='spm')
=== WARNING === Be aware that this conversion script is best-effort. Use a native GGUF model if possible. === WARNING ===

Scanning GGML input file
GGML model hyperparameters: <Hyperparameters: n_vocab=32000, n_embd=4096, n_mult=256, n_head=32, n_layer=32, n_rot=128, n_ff=11008, ftype=3>
Traceback (most recent call last):
File "/Users/FD00199/Downloads/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 345, in
main()
File "/Users/FD00199/Downloads/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 334, in main
(params_override, vocab_override) = handle_metadata(cfg, model.hyperparameters)
File "/Users/FD00199/Downloads/llama.cpp/convert-llama-ggmlv3-to-gguf.py", line 286, in handle_metadata
assert cfg.model_metadata_dir.is_dir(), 'Metadata dir is not a directory'
AssertionError: Metadata dir is not a directory

**Comment by JackJollimore** [comment]
Hi, the error is basically saying `-m ./upstage ` is the wrong filepath for llama-7b.ggmlv3.q4_1.bin metadata. `./upstage` must include `tokenizer.model`, ect.

**Comment by staviq** [comment]
@KerfuffleV2 

Suggestion, because I saw this being source of confusion couple of times. Maybe convert scripts could check if user wants to name the output .bin and warn about proper extension being .gguf ?

If convert scripts "enforce" file extension, other issue reports wouldn't require additional clarification about the llamacpp version users are on, and would make sorting issues easier imho.

**Comment by KerfuffleV2** [comment]
> Maybe convert scripts could check if user wants to name the output .bin and warn about proper extension being .gguf ?

I'm not sure I understand what you mean. The error is related to the user using `-m` to point at something that isn't a directory with metadata. The name of the output file doesn't affect anything, as far as I know. It might be kind of confusing, but there's nothing stopping people from naming the outfile `blah.bin` instead of `blah.gguf`.

The commandline option is also called `--model-metadata-dir` and the error specifically says `Metadata dir is not a directory`. So it seems like the problem would be pretty clear?

**Comment by JackJollimore** [comment]
> Suggestion, because I saw this being source of confusion couple of times. Maybe convert scripts could check if user wants to name the output .bin and warn about proper extension being .gguf ?
> 

This is a good point that I missed, he's using `bin` for output instead of `gguf`. It's gonna be a bad time.

**Comment by KerfuffleV2** [comment]
> It's gonna be a bad time.

Why? Nothing cares about the file extension, as far as I know. I just double checked it: converting a GGML file called `testy.bin` to a GGUF file called `jomomma.bin` works just fine both for converting and loading in the `main` example.

**Comment by JackJollimore** [comment]
> > `jomomma.bin` works just fine both for converting and loading in the `main` example.

Apologies, I misuderstood. I thought `gguf` extension was absolutely required.

**Comment by staviq** [comment]
See that's what I meant by source of confusion :)

It's just an absolutely low priority suggestion to have file naming convention. I vaguely remember ggerganov mentioning new model files should be named .gguf, but thats definitely nothing critical, so feel free to ignore this suggestion.

**Comment by Yeetster-cmd** [comment]
> Hi, the error is basically saying `-m ./upstage ` is the wrong filepath for llama-7b.ggmlv3.q4_1.bin metadata. `./upstage` must include `tokenizer.model`, ect.

Question about this, I've personally converted some GGMLV3's to GGUF without the metadata, would that affect anything performance/quality wise? I'm not exactly sure what to expect tbh.

**Comment by KerfuffleV2** [comment]
> would that affect anything performance/quality wise? 

Performance, _mostly_ no. There were some improvements to quantization after the GGUF stuff got merged so if you're converting files quantized before that point there may be small differences in the quantization quality and file size. This isn't 100% specific to the GGML conversion stuff since if you made a GGUF file before those improvements it would basically be the same.

However, there is likely a reduction in quality due to it not being possible to perfectly convert the vocabulary from a GGML file to a GGUF file. Aside from conversion just not being perfect in that regard, there were also improvements to vocabulary handling in GGUF which you can't really take advantage of unless you convert the GGML file using metadata.

From my own testing, the reduction in quality seemed relatively low but the GGML to GGUF conversion stuff is basically supposed to be something to ease the pain of the transition. Generally good enough to use if you can't get the GGUF model, but ideally get an actual GGUF model or at least convert using the metadata from the original model.

**Comment by sachinspanicker** [comment]
Thanks for the suggestions. Am able to convert now. However unable to use the converted file. Any inputs on this one?
-----------------------
error loading model: create_tensor: tensor 'blk.0.attn_k.weight' has wrong shape; expected  4096,   512, got  4096,  4096,     1,     1
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/Users/FD00199/Downloads/ll.py", line 10, in <module>
    llm=LlamaCpp(model_path="llama.cpp/output.bin")
  File "/Users/FD00199/miniconda3/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: llama.cpp/output.bin. Received error  (type=value_error)

**Comment by KerfuffleV2** [comment]
>  Any inputs on this one?

Didn't notice this before, but `--gqa 8` is only for 70B LLaMA2 models as far as I know. Seems like you converted a 7B? Use `--gqa 1` (or just don't specify it because 1 is the default).

**Comment by KerfuffleV2** [comment]
@sachinspanicker Is your issue here resolved?

**Comment by sachinspanicker** [comment]
It is resolved
