### ISSUE TITLE
has anybody already converted Together.AI's LLaMA-2 variant with 32k context?

### ISSUE THREAD

**Issue by rozek** [ggerganov/llama.cpp#2841]
Together.ai has released a variant of LLaMA 2 fine-tuned for context sizes of up to 32k (see [Huggingface](https://huggingface.co/togethercomputer/LLaMA-2-7B-32K). This _could_ be compatible with llama.cpp when using the new `--rope-scale` argument.

And since I'm really disappointed by the horrible hallucinations of CodeLLaMA (LLaMA 2 was so much better) I would like to test that variant...

Has anybody already made a quantized GGUF file for that model?

**Comment by rozek** [comment]
I've meanwhile found the (closed) issue #2530 which states that the mentioned model does work - now I'm just looking for the proper GGUF file...

**Comment by rozek** [comment]
FYI: I've just created a Q8_0 quantized version of LLaMA-2-7B-32K which seems to work (tested with `-c 16384 --rope-scale 4`) - and am now in the process of uploading it to Huggingface...

Stay tuned for link and instructions how to quantize using Docker (for those who do not like Python stuff on their machines)

**Comment by pnb** [comment]
It should not be necessary to specify the rope scale anymore with the new GGUF format. If the model has been converted properly, it will include the appropriate rope scale in the GGUF file. I downloaded your Q4_0 model to check, and it reports the rope base and scale correctly as defined in the [model's config.json](https://huggingface.co/togethercomputer/LLaMA-2-7B-32K/blob/main/config.json) (GGUF stores the inverse value, 1/8):

```bash
llm_load_print_meta: freq_base      = 10000.0
llm_load_print_meta: freq_scale     = 0.125
```

So specifying `--rope-scale 4` is not needed, and might actually reduce the quality of generation, as sometimes happens when rope scale is lower than what the model was fine-tuned with.

**Comment by JackJollimore** [comment]
> If the model has been converted properly, it will include the appropriate rope scale in the GGUF file.

Oh, cool.

**Comment by rozek** [comment]
that's good to know, thank you very much!

**Comment by BrutalCoding** [comment]
Just wanted to drop in and say thanks for sharing @rozek. I came by your models on HF, tried it out and it worked right out of the gate. 

I’m still getting trying to figure out how to improve the inference performance (M1 with 16GB). Setting context size to 2048 seems to be fast enough but anything over that would take like minutes to complete a single sentence😅. 

Anyhow I’ll keep reading and tweaking around. Cheers!

**Comment by rozek** [comment]
Thanks for the plaudit!

Have tried compiling llama.cpp with Metal support and running it with '--ngl 8'? I've just succeeded running this model with '-c 32768' on an MBA 15" with 24GB RAM - and it started spitting out tokens at high rates after a few seconds starting up.

Of course, your M1 Macbook should also have two SSD chips rather than just one in order to benefit from the full SSD bandwidth...

**Comment by BrutalCoding** [comment]
> Thanks for the plaudit!
> 
> Have you tried compiling llama.cpp with Metal support and running it with `--ngl 8`? If so, don#t forget to place the file `ggml_metal.metal` in the same folder as your binaries (e.g., `main`) or Metal support will not work.
> 
> I've just succeeded running this model with `-c 32768` on an MBA 15" with 24GB RAM - and it started spitting out tokens at high rates after a few seconds starting up. (With 16GB RAM, your context size limit could be around 16k - you should, however, avoid setting `--mlock` then or use lower context sizes)
> 
> Additionally, your M1 Macbook should also have two SSD chips installed rather than just one in order to benefit from the full SSD bandwidth when loading the model...


I figured out why my performance was slow, I had ngl set to 1 (like the example) because I thought any value over 0 would be treated like a boolean (a true). Bad assumption. It's the amount of GPU layers, so setting it to 1 makes it run quite poor haha. Context size is restrained by my poor low free available RAM. I've just tried it out with Q8_0 with 4k context and that works. Setting it to 8k is too much with the dev crap I got running in the background too. I will keep playing around by trying different quantizations with higher contexts. 

I've got a powerhouse of a workstation to fall back to. I'm just trying to find the right model & settings for the average consumer like hardware :D

I think you can close this issue now
