### ISSUE TITLE
Is this still unusable?

### ISSUE THREAD

**Issue by mikewii** [ggerganov/llama.cpp#2893]
Didn't checked this in few months, is this still constantly breaking formats and having segfaults/freeze after few prompts?

**Comment by KerfuffleV2** [comment]
Talk to the manager to collect your refund. Constantly breaking formats? What are you talking about? It's literally been a whole 9 days since the last breaking format change.

**Comment by JackJollimore** [comment]
> Is this still unusable?

![I say sir_x4](https://github.com/ggerganov/llama.cpp/assets/130917767/b619d045-2772-4c8c-b775-78c696146511)

**Comment by mirek190** [comment]
> Didn't checked this in few months, is this still constantly breaking formats and having segfaults/freeze after few prompts?

Breaking formats?

Finally llamacpp standardized format so is much easier to maintain even other model formats now.

**Comment by vfhbg** [comment]
Please see the "Discussions" tab this is not an issue with the software.

**Comment by rozek** [comment]
I'm currently using llama.cpp even with large context sizes (up to 16k - that's what my little Macbook Air can handle) and it performs really well - especially when using Metal support.

Segfaults may appear if your PC does not have enough RAM to handle the size of your model and context - in that case, just choose a smaller model, a different quantization or a smaller context size

**Comment by mikewii** [comment]
> 

i dont have high end pc, but its good enough, and i have 20gb RAM, last time i tried to use llama 7B Q4_0, which is  about 4gb in size, it either segfault immediately or froze after around 6 prompts

**Comment by rozek** [comment]
Personally, I have experiences with Apple silicon only.

If you expect getting help from the community, I therefore recommend to post more (technical) details (as requested by the "Issue and enhancement template" for new issues)

This is because llama.cpp is indeed usable - even under modern conditions (such as a context size of 32k using RoPE), provided that it runs inside the memory constraints of your CPU and/or GPU (on Intel/AMD based systems you may have to consider them separately, on Apple silicon the RAM is "unified")

**Comment by Green-Sky** [comment]
> i dont have high end pc, but its good enough, and i have 20gb RAM, last time i tried to use llama 7B Q4_0, which is about 4gb in size, it either segfault immediately or froze after around 6 prompts

I encourage you to try again :)

**Comment by mikewii** [comment]
alright
