### ISSUE TITLE
Infinite context

### ISSUE THREAD

**Issue by logikstate** [ggerganov/llama.cpp#2925]
This new paper claims it's possible to achieve longer context without retraining.

https://arxiv.org/abs/2308.16137

**Comment by mindplay-dk** [comment]
There's an implementation here for reference - the code is actually very simple:

https://github.com/kyegomez/LM-Infinite

According to the paper, this not only achieves longer (practically infinite) context - it also improves attention and performance overall, by allowing the algorithm to focus on more important tokens, as well as "garbage collecting" unimportant tokens, which (incredibly) also apparently results in a 2-4x relative speedup.

David Shapiro talked about it in this video:

https://youtu.be/5XaJQKgL9Hs?si=GXPX74wNH0U6Wu3c

It sounds like a no-brainer, but perhaps too good to be true?

It might be interesting to have it an as option, maybe?

**Comment by mindplay-dk** [comment]
On a related note, I wonder if, with this addition, it would become feasible to serialize and restore attention state?

That is, rather than the traditional approach of parsing the entire previous conversation for every new entry, would it be possible to actually pause and resume the conversation, by dumping and reloading the generator state for a given conversation?

If this change truly enables effectively "infinite" context, this question could become very relevant - besides the ability to carry on a single conversation with an assistant over an extended period of time, imagine being able to bootstrap a conversation by preloading the entire codebase for your project, preloading entire books, agents or search engines without the need for the ML-based indices these tools use now, and so on.

This would probably blow just about anything else completely out of the water. 😄

**Comment by KerfuffleV2** [comment]
> That is, rather than the traditional approach of parsing the entire previous conversation for every new entry, would it be possible to actually pause and resume the conversation, by dumping and reloading the generator state for a given conversation?

You can already do that.

    --prompt-cache FNAME  file to cache prompt state for faster startup (default: none)
    --prompt-cache-all    if specified, saves user input and generations to cache as well.
                          not supported with --interactive or other interactive options
    --prompt-cache-ro     if specified, uses the prompt cache but does not update it.
