### ISSUE TITLE
Unable to activate the Cublas while running a python file which implements the llamachain using the llamacpp 

### ISSUE THREAD

**Issue by Llama-activator** [ggerganov/llama.cpp#2958]
I was trying to activate the Blas backend since a month to improve the performance by using GPU, and finally was able to activate the cublas that uses the GPU while running the main.exe from the llama.cpp/build/bin/Release following these steps : [https://github.com/ggerganov/llama.cpp#cublas](url)

I have been running a LlamaChain that implements Llamacpp inside a python file, where in the model properties it's showing 

> BLAS = 0

 and thus not using the GPU.

I want to activate the CuBlas upon running this python file and utilize the GPU to improve the performance. Any assistance on this issue is highly appreciated. 
Thanks in advance. 

System specifications :
OS : Windows 11
GPU : NVIDIA T600 Laptop GPU

**Comment by staviq** [comment]
You might have a better luck asking here: https://github.com/abetlen/llama-cpp-python as "core" llamacpp is not directly related to langchain.

If you're able to run `main` or `main.exe` with GPU support, the problem is not related to the llamacpp "backend" and it's somewhere in how langchain uses or provides it.
