### ISSUE TITLE
Questions about llm inference thread

### ISSUE THREAD

**Issue by AndreaChiChengdu** [ggerganov/llama.cpp#3154]
I have two questions that I would like answered:
the first one:
      I found that -t 4 is faster than -t 8 in my 8gen1/M2 devices，the conclusion is from CPU inference with openblas，but as i know,the soc have 8 cpu cores。

the 2rd question:
     will llama.cpp support Apple ANE for acceleration? In some cases, ANE has better power efficiency
thanks~

**Comment by bobqianic** [comment]
This might explain your question 1
https://github.com/ggerganov/whisper.cpp/issues/1282

**Comment by staviq** [comment]
Ideal number of threads is not obvious, and you often have to manually find a number that works best.

Long story short, it's currently not possible to perfectly and evenly spread the load across every bit of hardware you have. Often the CPU or GPU has to wait on various memory transfers to catch up, and more threads can in some cases result in more waiting rather than more performance.
