### ISSUE TITLE
Discrepencies between max position embeddings and max sequence length

### ISSUE THREAD

**Issue by Nexesenex** [ggerganov/llama.cpp#3225]
In the convert.py file (line 217 in LlamaCPP b1250) :
 
       if "max_sequence_length" in config:
            n_ctx = config["max_sequence_length"]
        elif "max_position_embeddings" in config:
            n_ctx = config["max_position_embeddings"]

The parameter n_ctx refers to both max sequence length and max position embedding from the params.json/config.json. Yet, these 2 values sometimes differ on fine-tuned models. Many models are trained for a higher max position embedding then their max sequence length is. 33b and 65b models of Llama 1 can be trained for 16k max context with a scale of 4, yet use only data with a max_sequence length of 8k due to the lack of VRAM of the machine they trained on. The couple 8k/2k is also common.

And many models have badly filled fields. I recompose them by reading the readme of the models and using the ctx length of the training data as max sequence length, and the max context advertised by the model as max position embedding.

Is that correct ?

And does this discrepancy between the 2 values, yet being considered as the same parameter n_ctx by convert.py, pose problem for the quality of the conversion in GGUF, so does it need a fix to acknowledge both values as different parameters, and affect the conversion accordingly? Or is it irrelevant?

**Comment by KerfuffleV2** [comment]
> pose problem for the quality of the conversion in GGUF,

I don't think so. It's just the default context size limit, you can set `-c` to whatever you want. I'm _pretty sure_ the only thing it affects is the print out of the model parameters and the warning you get if you set `-c` above the context size saved in the model.

From what you say, it's still not ideal because it can confuse users (and having to search around to find the correct context size would be annoying too).

**Comment by KerfuffleV2** [comment]
At the risk of being annoying by replying multiple times:

> And many models have badly filled fields. 

This seems like it may be the main issue. If one could definitively say "You're supposed to use `max_sequence_length`" or "You're supposed to use `max_position_embeddings`" then it would be an easy change.

From the code you pasted, it seems like we prefer `max_sequence_length` and fall back on `max_position_embeddings` if the former isn't available. Can you (and hopefully other people also) verify that doing it the other way around would produce better results in most cases? That would be an easy pull to create, and I can do it if no one else wants to.

>  I recompose them by reading the readme of the models and using the ctx length of the training data as max sequence length, and the max context advertised by the model as max position embedding. Is that correct ?

That's the fun question. If they're providing the wrong information then who knows! Usually it's pretty obvious when you're exceeding the context because the results from the model turn to nonsense. If the settings the people who made the model provide aren't actually accurate, doing a test to find the practical limit to the model's context is probably the only real way to know. That's out of scope for a simple tool like `convert.py` though.
