### ISSUE TITLE
[User] Insert summary of your issue or enhancement..

### ISSUE THREAD

**Issue by Showwwwwwwww** [ggerganov/llama.cpp#3288]
I am trying to use the main.cpp in .example/main  to run the model. However When I compile this model, it show the error for cannot find the file inside the #include "". I changed the path to the whole path for the file and it still does not work. 
Here is the error message. 

`(llama) chen@chenshuodeMBP-9 main % g++ -Wall -o test main.cpp
main.cpp:6:10: fatal error: 'common.h' file not found
#include "common.h"
         ^~~~~~~~~~
1 error generated.`

If anyone know how to solve it? 
Thanks.

**Comment by staviq** [comment]
Examples are part of the llama.cpp project, and you compile entire llama.cpp with make/cmake etc like in the readme, and you get separate binaries for each example.

**Comment by Showwwwwwwww** [comment]
Hi,
It is possible to run this signle file for the llama model? If so, can you tell me how to run it? I tried the ./mian +args but it does not work and shows "no such file or directory: ./main"

**Comment by Showwwwwwwww** [comment]
> Examples are part of the llama.cpp project, and you compile entire llama.cpp with make/cmake etc like in the readme, and you get separate binaries for each example.

Hi,
It is possible to run this signle file for the llama model? If so, can you tell me how to run it? I tried the ./mian +args but it does not work and shows "no such file or directory: ./main"

**Comment by KerfuffleV2** [comment]
You need to use the `Makefile` to compile it (`main`, the examples, whatever) or cmake. Try running `make main` instead.

It's not impossible to compile the parts manually but you'd basically have to replicate what the `Makefile` does and there's really no point.

**Comment by Showwwwwwwww** [comment]
> You need to use the `Makefile` to compile it (`main`, the examples, whatever) or cmake. Try running `make main` instead.
> 
> It's not impossible to compile the parts manually but you'd basically have to replicate what the `Makefile` does and there's really no point.

I tried to use make/cmake to compile the folder which called in example and named main. The reason I do that because I tried to allow read the content in txt file as the input rather than read from console. I supposed that this main.cpp is provided for customise the functionality. While after I want to test it I do not know how to run this file/model. That's the reason that I tried to complie and use it.

**Comment by KerfuffleV2** [comment]
I'm not completely sure what you're trying to do - if you're trying to modify the existing `main` example, if you made another directory and copied some files to it or something else.

The examples aren't stand-alone, they need to be compiled with GGML, they need some defines set, they need to have the stuff in `common/` included and linked with them, etc. You can't just do `gcc -o blah blah.cpp` since they have dependencies.

If you just modified `examples/main` or one of the other examples that already exist then you should be able to do what I said before and run `make main` or whatever. There's already a rule in the `Makefile` to compile `main` with all the dependencies and other stuff that it needs.

If you're trying to create a new example based on main then you'll basically have to edit the `Makefile` and make a copy of an existing rule and modify it to use your example instead. What I suggest is modifying `main` in a git branch or something so you can just use the existing stuff in the `Makefile`. If you want to do something more complicated, you'll basically have to learn a bit about the make system and Makefiles on your own. (You could also do essentially the same thing with cmake but I'm pretty sure that would be even more complicated. I personally don't like cmake and don't really use it.)

**Comment by Showwwwwwwww** [comment]
Yes I found that it working. Thanks for your help. :)
