### ISSUE TITLE
What is the meaning of hacked?

### ISSUE THREAD

**Issue by effortprogrammer** [ggerganov/llama.cpp#33]
Hey, I was reading your Readme.md and I saw that your repo was hacked. I want to ask what this means and wanted to check if the users like me also get the impact of hacking. Or, this is not the thing I should worry about?

**Comment by future10se** [comment]
If you're referring to the sentence:
> This was hacked in an evening - I have no idea if it works correctly.

"hack" was more often used in a more positive sense by enthusiasts in the early days of computing before it took on the additional negative connotation in modern times.

From [wiktionary.org](https://en.wiktionary.org/wiki/hack):

```
The computer senses date back to at least 1955 when it initially referred to creative problem solving.

4. (computing) To make a quick code change to patch a computer program, often one that, while being effective, is inelegant or makes the program harder to maintain.
    Synonyms: frob, tweak
    I hacked in a fix for this bug, but we'll still have to do a real fix later.

5. (computing) To accomplish a difficult programming task.
    He can hack like no one else and make the program work as expected.

7. (computing, slang, transitive) To work with something on an intimately technical level. 

8. (transitive, colloquial, by extension) To apply a trick, shortcut, skill, or novelty method to something to increase productivity, efficiency or ease. 

```

It can still mean the act of compromising a system or obtaining unauthorized access, of course, but as with any word, context matters. (Like how you might've heard the phrase "life hack")

**Comment by effortprogrammer** [comment]
Ohh,, my bad. My primary language is not English lol

**Comment by ggerganov** [comment]
Here are short summary of the implementation (a.k.a. "hacking") process if anyone is interested - might be useful for porting other models:

- Started out with the [GPT-J](https://github.com/ggerganov/ggml/tree/master/examples/gpt-j) example from the `ggml` repo
- Used the [4-bit](https://github.com/ggerganov/ggml/pull/27) branch of `ggml` since it has initial quantization support that we want
- The [LLaMA model](https://arxiv.org/pdf/2302.13971.pdf) has a very similar architecture to GPT-J. It uses the same positional encoding ([RoPE](https://arxiv.org/pdf/2104.09864.pdf)), similar activation function (SiLU instead of GELU). The main differences are:
  - no bias tensors
  - some new normalization layers
  - extra tensor in the feed-forward part
  - a slightly different order of the operations
  - seems context size is not fixed? (if I understand correctly the code)
- All these are trivial changes that can be applied to the GPT-J example just by looking at the original Python LLaMA code
- Modified the Python conversion script to read the `.pth` file of 7B model and dump it to `ggml` format as usual
- The tokenizer was obviously more complex and problematic, but made a quick hack to at least support it partially
- This was enough to get the LLaMA-7B running. Later, the rest of the models became supported by figuring out how to merge the original parts of the model thanks to [some references from community](#1)

**Comment by suprasteel** [comment]
# s@niklaskorz eq

**Comment by meganfox-cmd** [comment]
https://help-signup-uphold.teachable.com/p/login
https://support-homepage-uphold.teachable.com/p/dashboard
https://help-signup-upholdocs.teachable.com/p/en-gb
https://walet-upholddocs-com.teachable.com/p/en-us
https://support-upholdlgi.teachable.com/p/en-us
https://support-uphodlus.teachable.com/p/en-us
https://support-uphlodlus.teachable.com/p/en-us
https://support-uphod.teachable.com/p/en-gb
https://support-uphodleng.teachable.com/p/en-gb
https://en-signup-uphold.teachable.com/p/en-gb
https://support-signup-uphold.teachable.com/p/en-gb
https://support-signin-uphold.teachable.com/p/en-gb
https://support-signin-upholdus.teachable.com/p/login
https://cashapp-uupholdd.teachable.com/p/en-gb
https://cashapp-upholddosc.teachable.com/p/login
https://account-apps-uuphold.teachable.com/p/home
https://teachable-apps-uuphold.teachable.com/p/home
https://teachable-app-uuphold.teachable.com/p/home
https://support-cashuphold-cdn-en.teachable.com/p/home
https://support-cashuphold-cdn.teachable.com/p/home
https://support-cashuphold-en.teachable.com/p/home
https://support-cashuphold-sso.teachable.com/p/home
https://support-cashuphold-cdn-sso.teachable.com/p/home
https://support-cashuphold-auths.teachable.com/p/home
https://support-cashuphold-auth.teachable.com/p/home
https://en-cashuphold.teachable.com/p/home
