### ISSUE TITLE
Grammars from other projects

### ISSUE THREAD

**Issue by tom-adsfund** [ggerganov/llama.cpp#3303]
Having a constraining grammar is a great idea, but is there a way we can reuse work done in other grammars?

**Comment by staviq** [comment]
BNF isn't specific to llama.cpp at all, it's a well established format, quite old actually

Fun fact, I wanted to send you a link with BNF description, and I just noticed wiki article on it has a history section, turns out, while BNF itself was developed around 1960, the concept of constrained grammar dates back to ~6 BC :)

https://en.m.wikipedia.org/wiki/Backus%E2%80%93Naur_form#History

**Comment by tom-adsfund** [comment]
This thread highlights something like my perspective on it: https://www.reddit.com/r/Compilers/comments/sw3f8g/what_is_the_deal_with_bnf/

One person's response: "the BNF description of the language is a reminder for you, not for formal systems. You'll have to convert it to either parser combinators or to LR/LALR parser generator, and they have concrete syntax."

**Comment by staviq** [comment]
I'm not entirely sure what the autor of that Reddit comment had in mind, but with llama.cpp, BNF grammar is directly guiding generation.

If you have BNF definition for something, you can directly pass that as an argument to `main`, and that's it, it already works like I'm assuming you want it to:

https://github.com/ggerganov/llama.cpp#constrained-output-with-grammars

**Comment by ejones** [comment]
Yeah, that's the thing about BNF - it's a family of formats, and there's a variety of syntaxes out there both abstract and in parser generators. There was some talk in the initial grammar implementation of having alternate grammar syntaxes or converters to support existing formats (ANTLR was brought up) but nothing's been done on that front.

Honestly what I've been doing is to ask GPT-4 to convert/generate a GBNF grammar for me. Basically feed it the GBNF docs (`grammars/README.md`) or a sample GBNF file (e.g., `grammars/chess.gbnf`) in addition to some grammar and ask it to make the translation. Or "write a GBNF grammar to do X".

Usually it does a pretty good job with the output needing some syntactic cleanup. One common error I've encountered is that it uses `snake_case` instead of `kebab-case` for rule names, which is easily rectified.

**Comment by tom-adsfund** [comment]
@ejones Yes, I was thinking of ANTLR. Because I somehow don't think GPT4 will produce a valid Clojure grammar!

**Comment by staviq** [comment]
Take a look at `simple` example source, here: https://github.com/ggerganov/llama.cpp/blob/bc9d3e3971e5607a10ff4c24e39568ce1ac87271/examples/simple/simple.cpp#L100

If write your own `llama_sample_token_X` function, you can basically implement any sort of grammar guidance you want.

**Comment by tom-adsfund** [comment]
A grammar of GBNF would be useful (including for attempting to convert other formats to it).

**Comment by ejones** [comment]
@tom-adsfund good point, yes, I had been meaning to do that at some point

**Comment by jmikedupont2** [comment]
https://github.com/BNFC/bnfc I have been eyeing this project that can import antlr and other forms

**Comment by tom-adsfund** [comment]
@jmikedupont2 Great find! I wonder if Gemini Pro (free via AI Studio until 15 Jan) can help convert the grammars in the examples folder of the project you've mentioned. I tried to use coding LLMs before to do it, but they all failed pretty hard, although these grammars you're suggesting are much more like GBNF, so in some respects I'd be surprised if they (especially Gemini Pro) failed this time.

**Comment by jmikedupont2** [comment]
Well you can see my work in progress where I am creating an ocaml menhir parser
 https://github.com/meta-introspector/gbnf-nice-parser/tree/feature/parser it is work in progress, see the grammars directory for the examples I collected. The grammar has no conflicts and passes some parse tests, lot more work to do.

**Comment by jmikedupont2** [comment]
> A grammar of GBNF would be useful (including for attempting to convert other formats to it).

yes i am working on it,

**Comment by jmikedupont2** [comment]
https://github.com/meta-introspector/gbnf-nice-parser I have gotten all of the test cases from the other systems to pass and I found a couple of things that looked like they might be errors in the original syntaxes that I fixed using my parser and I'd like to invite everyone to try my parser out at least to validate their code and give me some feedback it's now able to pass all of the tests and get to eof

**Comment by tom-adsfund** [comment]
@jmikedupont2 I'm unclear what's there. Is `test/test.gbnf` the GBNF grammar? Quick look seems unlikely because doesn't do "::=".

**Comment by jmikedupont2** [comment]
https://github.com/BNFC/bnfc I have been eyeing this project that can import antlr and other forms look at the grammar's directory and those are the grammars that I'm testing

**Comment by jmikedupont2** [comment]
I need to delete that test directory it's not being used I only have one test that I fed it it's in line inside of the the test file otherwise I'm testing outside

**Comment by jmikedupont2** [comment]
I mean that file's not being used to test directory is being used there is a there's a oak camel file that has a test number two that's being used

**Comment by jmikedupont2** [comment]
I mean that file's not being used to test directory is being used there is a there's a ocamel file that has a test number two that's being used. See report.sh for tests

**Comment by jmikedupont2** [comment]
https://github.com/meta-introspector/gbnf-nice-parser
   90bfb0b..8772d13  feature/ppx -> feature/ppx 
on this branch we have resolved the EOF error, have the newlines handled and are starting to build the grammar tree.
