### ISSUE TITLE
Bad Output after runnig the train-text-from-scratch

### ISSUE THREAD

**Issue by Tantawi1** [ggerganov/llama.cpp#3356]
Hi there,

I have a simple dataset to train with the llama and vicuna model. I tried to train the data with this command.
./train-text-from-scratch --vocab-model models/vicuna-13b-v1.5-16k.Q2_K.gguf --ctx 64 --embd 256 --head 8 --layer 16 --checkpoint-in chk-newData-256x16.gguf --checkpoint-out ggml-shakespeare.gguf --model-out ggml-shakespeare.gguf --train-data "shakespeare.txt" -t 6 -b 16 --seed 1 --adam-iter 256 --no-checkpointing

I get the hole data printed when I run the output model and try to ask something.

Dose anyone has this problem before?!

**Comment by xaedes** [comment]
You trained a small model from scratch which has only seen this shakespeare data set. 
It will happily generate shakespeare-like text but probably won't be able to be used in a question answer setting.

`train-text-from-scratch` uses only the vocabularly of the model given by `--vocab-model`. 
Probably you wanted to finetune the vicuna model? Try to use `./finetune` for this purpose. For example:
```
./finetune \
  --model-base models/vicuna-13b-v1.5-16k.Q2_K.gguf \
  --checkpoint-out chk-lora-vicuna-shakespeare.gguf \
  --lora-out lora-vicuna-shakespeare.bin \
  --train-data "shakespeare.txt" \
  ...(other params you want to specify)
```
This will finetune a LORA adapter on your data.

A full finetune is possible with train-text-from-scratch, but only for non-grouped-quey-attention and F32 models, it will consume lots of memory for bigger models. To try a full-finetune anyway you need to pass the model via the `--checkpoint-in` parameter. Btw: Full finetune on vicuna-13b Q2_k won't work because it is not F32.
