### ISSUE TITLE
llama : revisit using flash attention for prompt processing (a.k.a. prefil) + GPU implementation

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#3365]
Sample Flash Attention usage on the CPU has been demonstrated here:

https://github.com/ggerganov/llama.cpp/pull/778

Although it didn't provide improvement during text generation workloads, it might be beneficial during prompt processing.
Investigate if that is the case and attempt Metal and CUDA implementations

**Comment by netrunnereve** [comment]
Does the patch in #778 still work with the latest master? That would be a easy way for us to try this out.

**Comment by Aya-ZIbra** [comment]
Is there any current implementation for flash attention for GPU? If not,
any pointers where to start?

**Comment by fzzylogic** [comment]
Just putting this here fwiw, creators of FlashAttention released [FlashDecoding](https://pytorch.org/blog/flash-decoding/), which can apparently improve inference by up to 8x.

**Comment by lapp0** [comment]
Published yesterday, [FlashDecoding++](https://arxiv.org/pdf/2311.01282.pdf)

"Our extensive results show that FlashDecoding++ achieves an average of 1.37× speedup compared with FlashDecoding"

**Comment by BrainSlugs83** [comment]
FYI Flash Attention 2 also exists now: https://arxiv.org/abs/2307.08691 (published in July) whereas #778 is from April... so that PR might be a good starting place, but it's not testing the latest thing. -- Supposedly the new algorithm achieves about a  2x speedup vs the original.

Off topic, but for CPU inferencing speed-ups, this might be applicable? 
https://huggingface.co/papers/2311.00502 -- they're claiming 20ms to 30ms per token with Llama 7B on a 4th gen Xeon CPU... which is kind of impressive IMO. -- Even on a 4bit model with my RTX 2070 I'm not getting those speeds out of llama.cpp! -- It looks like they're doing stuff to take advantage of the CPU cache more effectively? 
(I mention it because it seems like kind of a sister to Flash Attention / Decoding which are optimized to take advantage of the GPU architecture, and this seems to take advantage of the CPU architecture).

**Comment by FSSRepo** [comment]
I am trying to create the CUDA kernel, but I am having trouble finding a way to reduce the memory usage as proposed in the paper. The implementation in the original repository requires Nvidia CUTLASS (a library that is too heavy with many dependencies), which allows high-level handling of operations. However, here we are working with CUDA at a low level, using custom kernels.

**Comment by YehowshuaScaled** [comment]
@FSSRepo, are you still working on the CUDA kernels? Do you have a branch? What kinds of memory issues have you been hitting?

**Comment by ggerganov** [comment]
#5021
