### ISSUE TITLE
iOS swift package seems to use internal symbols: cblas_sgemm from NEWLAPACK, causing apps that use this to be unable to be published to the App Store

### ISSUE THREAD

**Issue by l3utterfly** [ggerganov/llama.cpp#3438]
Building an app that links to the swift package llama.cpp gives an error during the App validation phase when publishing to the app store.

In particular, the error it gives says `app references non-public symbol cblas_sgemm$NEWLAPACK$ILP64`

**Comment by jhen0409** [comment]
It seems like related to #3342. Also, what is your Xcode version?

/cc @jagtesh

**Comment by l3utterfly** [comment]
I'm using the latest version of Xcode 15

**Comment by jhen0409** [comment]
@l3utterfly can you check if #3481 is works for you? Thanks!

**Comment by l3utterfly** [comment]
@jhen0409 thanks, this fixes the issue.

Strange though.. because I actually researched this function as well, and I tried updating my xcode settings to target minimum iOS version 16.5, it still gives this error.

**Comment by psugihara** [comment]
FWIW I got a rejection on the latest FreeChat TestFlight from this as well. We ship a lipo'd version of the server executable, one compiled on sonoma m1 MacBook and one compiled on my x86 iMac. This is for a macOS app. I'm going to try bumping the deploy target to 13.5 (from 13.3) and will report back. Otherwise I'll try re-compiling with `LLAMA_NO_ACCELERATE`.
