### ISSUE TITLE
llama.cpp BPE tokenization of wiki.test does not match the HF tokenization

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#3502]
I did the following test to tokenize `wiki.test.raw` using our tokenizer and the Python tokenizer.
The expectation is that the outputs will match:

```bash
# generate ggml-vocab-falcon.gguf
./convert-falcon-hf-to-gguf.py --vocab-only ~/development/huggingface/falcon-7b/ --outfile ./models/ggml-vocab-falcon.gguf

# tokenize using Python
python3 tests/test-tokenizer-0-falcon.py ~/development/huggingface/falcon-7b/ --fname-tok ./build/wikitext-2-raw/wiki.test.raw

# tokenize using llama.cpp
cd build
make -j
./bin/test-tokenizer-0-falcon ../models/ggml-vocab-falcon.gguf ./wikitext-2-raw/wiki.test.raw

# compare the results
cmp ./wikitext-2-raw/wiki.test.raw.tok ./wikitext-2-raw/wiki.test.raw.tokcpp 
./wikitext-2-raw/wiki.test.raw.tok ./wikitext-2-raw/wiki.test.raw.tokcpp differ: char 1, line 1
```

The results are pretty close, but not exactly the same. Any ideas why the test does not pass?
I thought that #3252 would resolve this

cc @goerch

**Comment by goerch** [comment]
That is a nice test. I made some modifications to get more detailed outputs of the tests and see differences like

1.  Problem with `endoftext`

![image](https://github.com/ggerganov/llama.cpp/assets/3709434/291e9c93-4be7-40a5-a181-9d53c1d17cbb)

2. Non greediness

![image](https://github.com/ggerganov/llama.cpp/assets/3709434/99e749fe-14fd-466a-9908-01d5c9eb756d)

![image](https://github.com/ggerganov/llama.cpp/assets/3709434/60667d99-fddb-4962-ad11-978e8d2a2893)

**Comment by goerch** [comment]
Intermediate results of debugging: `bpe_gpt2_preprocess` seems to do the right thing, `llm_tokenizer_bpe::tokenize` seems to be subtly broken, although it looks very similar to `examples/gptneox-wip`.  Paging @cmp-nct in need for help, because `git blame` doesn't work very well here.

**Comment by goerch** [comment]
> `llm_tokenizer_bpe::tokenize` seems to be subtly broken

I implemented an independent port of the [gpt2-tokenizer](https://github.com/openai/gpt-2/blob/master/src/encoder.py#L55-L101)(will share the code if someone is interested) and it shows the same behavior as the `llama.cpp` tokenizer. I also tried to use the `slow` tokenizer of HF (i.e. the `Python`  implementation) to compare without success, i.e. I didn't get it working (any tips appreciated!). I tried to understand the fast tokenizer implemented [here](https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/models/bpe/word.rs#L161-L252), which looks like it supports some advanced features. This looks pretty hopeless until we are going to debug the complete HF stack (which I currently don't know how to). BTW: I'm not talking about the `endoftext` problem here.

**Comment by jploski** [comment]
> > `llm_tokenizer_bpe::tokenize` seems to be subtly broken
> 
> I implemented an independent port of the [gpt2-tokenizer](https://github.com/openai/gpt-2/blob/master/src/encoder.py#L55-L101)(will share the code if someone is interested) and it shows the same behavior as the `llama.cpp` tokenizer. I also tried to use the `slow` tokenizer of HF (i.e. the `Python` implementation) to compare without success, i.e. I didn't get it working (any tips appreciated!). I tried to understand the fast tokenizer implemented [here](https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/models/bpe/word.rs#L161-L252), which looks like it supports some advanced features. This seems hopeless until we are going to debug the complete HF stack (which I currently don't know how to). BTW: I'm not talking about the `endoftext` problem here.

You can create the slow (or fast) GPT2 tokenizer in tests/test-tokenizer-0-falcon.py  like so:
```
from transformers import GPT2TokenizerFast, GPT2Tokenizer
slow_tokenizer = GPT2Tokenizer(vocab_file=dir_tokenizer + '/vocab.json', merges_file=dir_tokenizer + '/merges.txt')
fast_tokenizer = GPT2TokenizerFast(tokenizer_file=dir_tokenizer + '/tokenizer.json')
```
You will have to create the files vocab.json and merges.txt yourself. The file vocab.json should contain only the vocab map from Falcon's tokenizer.json (e.g. see https://huggingface.co/gpt2/blob/main/vocab.json). The file merges.txt should contain only the contents of the merges array, one array element per line (i.e. space separated token pairs, e.g. see https://huggingface.co/gpt2/blob/main/merges.txt).

You will notice that the slow tokenizer tokenizes "2000" differently ("20" "00") than the fast one ("200" "0"). So yes, I think we are running into a HF implementation bug, but the cpp code tokenizes like the (presumably now less popular) slow tokenizer.

And the <|endoftext|> in the front is trivial, it's just the artificially injected BOS token (which I believe is a Llama thing and should not be inserted for Falcon).

**Comment by ggerganov** [comment]
So maybe it is best to switch to the slow tokenizer in `test-tokenizer-0-falcon.py` and close the issue if things match?
Probably also add this as a `ctest`

**Comment by goerch** [comment]
I could imagine this to be hairy problem, because I'd assume a couple of models have been trained with the fast tokenizers?

**Comment by jploski** [comment]
> I could imagine this to be hairy problem, because I'd assume a couple of models have been trained with the fast tokenizers?

Yes, I suppose everyone uses the fast ones because they are default, so having a tokenizer in llama.cpp which behaves differently is not good.

One point which I am still unclear about is whether the fast tokenizer, which for some reason (also) wants tokenizer.json rather than just the vocab.json/merges.txt file as input maybe relies on some extra information from tokenizer.json, which makes it behave differently in our test case. So there's still some chance it might not be a bug in the HF implementation after all, but rather our lack of understanding of it. I'm hoping to learn more from HF's response to https://github.com/huggingface/tokenizers/issues/1363.

**Comment by apage43** [comment]
the discrepancy here is because Falcon's `tokenizer.json` specifies a different `pre_tokenizer`.

_Most_ BPE-using models use the default config that mimics GPT2 - i.e. "pretokenizing" is done with the standard regex: https://github.com/karpathy/minGPT/blob/master/mingpt/bpe.py#L92

```json
  "pre_tokenizer": {
    "type": "ByteLevel",
    "add_prefix_space": false,
    "trim_offsets": true,
    "use_regex": true
  },
```

replacing with this gets consistent behavior, but that's not really what we want. Falcon instead specifies this:

```json
{
  "type": "Sequence",
  "pretokenizers": [
    {
      "type": "Punctuation",
      "behavior": "Contiguous"
    },
    {
      "type": "ByteLevel",
      "add_prefix_space": false,
      "trim_offsets": true,
      "use_regex": true
    },
    {
      "type": "Digits",
      "individual_digits": false
    },
    {
      "type": "Split",
      "pattern": {
        "Regex": "[0-9][0-9][0-9]"
      },
      "behavior": "Isolated",
      "invert": false
    }
  ]
}
```

that is, it first applies [punctuation splitting](https://docs.rs/tokenizers/latest/src/tokenizers/pre_tokenizers/punctuation.rs.html#48) _before_ the standard regex, then the standard regex, then ["Digits"](https://docs.rs/tokenizers/latest/src/tokenizers/pre_tokenizers/digits.rs.html#48-65) (force spans of digits to be separated from non-digits) ,  _then_ ["isolated" mode custom regex splitting](https://docs.rs/tokenizers/latest/src/tokenizers/pre_tokenizers/split.rs.html#127-138) on a regex matching 3 consecutive digits so that no token over 3 digits long makes it past the pretokenizer

its the last one that seems to cause the discrepancy here - but the problem is that to be fully consistent with `tokenizers` we will need to implement some of the less common `pre_tokenizer`/`pretokenizers` options

**Comment by bobqianic** [comment]
@apage43

Could you take a look at my code? I followed the procedure you outlined and even checked the source code, but I'm still getting inconsistent results. Is there a way to directly test the pre-tokenizer without comparing the final output of the tokenizer? This might help us pinpoint the exact issue. https://github.com/ggerganov/llama.cpp/pull/5613
