### ISSUE TITLE
bug in k_quants.c

### ISSUE THREAD

**Issue by shlevi-microsoft** [ggerganov/llama.cpp#3636]
There is a bug in k_quants.c.

the loop index j is incremented by k in each iteration, which means that each iteration processes a block of k elements. starting at column j. However, the loop condition is j < nb. This condition may not be correct, because nb is calculated as k / QK_K, which is the number of blocks in the matrix, not the number of elements.

j < nb should be change to j < n
![image](https://github.com/ggerganov/llama.cpp/assets/93481053/4ed8ced5-1f08-4cdc-a900-2928b9308333)

**Comment by coezbek** [comment]
You are certainly right that since `nb < k` (because `nb = k / QK_K`) that the loop is only executed once (with `j == 0`)

On the other hand, if this is wrong then all the `ggml_quantize_...` methods would be wrong.

Maybe the code isn't used, but rather the code from ggml.c: https://github.com/ggerganov/llama.cpp/blob/master/ggml.c#L20565

**Comment by shlevi-microsoft** [comment]
I noticed that ggml_quantize_q4_l is only called with n = k, causing it to terminate after one loop iteration. This isn't a problem when k = n, but if k < n, it could lead to a bug. T
o avoid this, consider fixing the code to handle cases where k < n properly.
