### ISSUE TITLE
Why avx512 is not used

### ISSUE THREAD

**Issue by hhy3** [ggerganov/llama.cpp#4200]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

# Motivation

# Possible Implementation

**Comment by BarfingLemurs** [comment]
@hhy3 avx512 releases: https://github.com/ggerganov/llama.cpp/releases/download/b1557/llama-b1557-bin-win-avx512-x64.zip

**Comment by BarfingLemurs** [comment]
https://github.com/ggerganov/llama.cpp/archive/refs/tags/b1592.zip

**Comment by hhy3** [comment]
> The project code is all available on the main page, you can git clone the url or download the zip: https://github.com/ggerganov/llama.cpp/archive/refs/tags/b1592.zip

Thanks for the reply, but I didn't see any code related to avx512 in this branch (by running `ag m512`). Did I miss something?

**Comment by jboero** [comment]
Hi I also recently noticed this with my COPR RPM builds since I've tried on a system with AVX512 support. If you install the RPMs from COPR I noticed that the COPR build environments don't have AVX512, so the builds produced aren't currently supporting it. I may either need to force this in the Make or just recommend that people build from source.

https://copr.fedorainfracloud.org/coprs/boeroboy/brynzai/package/llama.cpp/
