### ISSUE TITLE
Clarification for multi GPU

### ISSUE THREAD

**Issue by jholla-atx** [ggerganov/llama.cpp#4238]
From what I can see there arent any docs that make it clear to leverage multiple GPUs, outside of disparate threads in issues. 

This is all I have found, what are the actual instructions to use multi-gpu?

`make clean && LLAMA_HIPLAS=1 && HIP_VISIBLE_DEVICES=0,1 make -j`

`make LLAMA_CUBLAS=1 CUDA_DOCKER_ARCH=compute_80`

**Comment by jholla-atx** [comment]
@ruped no offense, but i am tired of useless answers, do you not think i have not looked at the readme?

**Comment by askmyteapot** [comment]
@jholla-atx No offense, but  you haven't provided *ANY* useful information to go on for your use case or to assist with troubleshooting your slowness issue.

For example: 
What OS are you using? 
What hardware are you using? CPU, GPU(s)
What SDK's are you using? 
What version 
What command did you use to build?
What model (and quant) are you using?
What commands did you use to run? 
What speeds are you getting for a given prompt request? 

**To answer your question:** That's correct, llama.cpp does not automatically use all GPUs. If you want simple, use a front end like [oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui) or [LostRuins/koboldcpp](https://github.com/LostRuins/koboldcpp)

**Comment by cmp-nct** [comment]
> I assume I'm being pinged due to a recent comment I made regarding splitting the model layer wise instead of tensor wise. That was mainly just a theory I had, I don't own any GPUs to test it on. Even if you could do so, it would only be an improvement over splitting tensor wise if the GPUs have significantly different performance characteristics, and even then you'd need to use tricks like speculation to utilize the GPUs simultaneously. Tensor wise splitting should be performant for most cases.
> 
> Unfortunately, I'm not a maintainer and don't touch any of the GPU related code, so that's about as far as I can help. Perhaps some specific use cases, logs, and hardware specs could help other developers with your issue.

I've an open enhancement discussion on layer splitting as well (https://github.com/ggerganov/llama.cpp/issues/4055).
It doesn't have the support of the current cuda main developer, adding it without that wouldn't get accepted or maintained.

**Comment by AutonomicPerfectionist** [comment]
The MPI backend is already pipeline parallel, so as soon as I finish fixing it, it would be trivial to run GPUs in pipeline parallel (run two MPI processes, each one only using a single GPU). However, that introduces a bit of overhead from MPI communication. I believe most popular runtimes will do shared memory communication when on the same host, so it's probably not significant. Keep in mind, however, that pipeline parallel is really only used in certain scenarios precisely because of what the CUDA developer mentioned: without specific architecture tricks, you will only be using one GPU at a time, and your performance will suffer compared to a single GPU due to communication and synchronization overhead. There are cases where it makes sense, but they are few and far between, so it's not surprising the CUDA maintainer doesn't want to add support directly.
