### ISSUE TITLE
Failed to convert Llama-v2 models 

### ISSUE THREAD

**Issue by HighTemplar-wjiang** [ggerganov/llama.cpp#4493]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [Y] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [Y] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [Y] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Successful converting Llama models using the following command:

``
python convert.py models/xxx
``

where xxx is the original trained Llama model downloaded from Facebook.

# Current Behavior

Cannot convert with errors (detailed below). 

I've found there was an update in the following commit, after checkout an older version, the conversion could be done:

[873637afc7924f435ac44c067630a28e82eefa7b](https://github.com/ggerganov/llama.cpp/commit/873637afc7924f435ac44c067630a28e82eefa7b)

It seems that after the above commit, convert.py does not support the BPE vocab format anymore (--vocabtype param has been removed). While README did not reflect such change. This causes confusion.  

# Environment and Context

* Physical (or virtual) hardware you are using, e.g. for Linux:

Macbook M3 Max 

* Operating System, e.g. for Linux:

MacOS - 14.1 (23B2073)

* SDK version, e.g. for Linux:

Python 3.10.13
transformers 4.36.1

# Failure Information (for bugs)

```
Loading model file models/13B/consolidated.00.pth
Loading model file models/13B/consolidated.01.pth
params = Params(n_vocab=32000, n_embd=5120, n_layer=40, n_ctx=4096, n_ff=13824, n_head=40, n_head_kv=40, n_experts=None, n_experts_used=None, f_norm_eps=1e-05, rope_scaling_type=None, f_rope_freq_base=None, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=PosixPath('models/13B'))
Traceback (most recent call last):
  File "llama.cpp/convert.py", line 1279, in <module>
    main()
  File "llama.cpp/convert.py", line 1255, in main
    vocab = VocabLoader(params, vocab_dir)
  File "llama.cpp/convert.py", line 342, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(str(fname_tokenizer), trust_remote_code=True)
  File "python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 752, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1082, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "python3.10/site-packages/transformers/configuration_utils.py", line 644, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "python3.10/site-packages/transformers/configuration_utils.py", line 699, in _get_config_dict
    resolved_config_file = cached_file(
  File "python3.10/site-packages/transformers/utils/hub.py", line 360, in cached_file
    raise EnvironmentError(
OSError: models/13B does not appear to have a file named config.json. Checkout 'https://huggingface.co/models/13B/None' for available files.
```

**Comment by adelmofilho** [comment]
Same here

**Comment by YizhongC** [comment]
I am running into this same issues, Can you post if you find a resolution?

**Comment by HighTemplar-wjiang** [comment]
> I am running into this same issues, Can you post if you find a resolution?

As a temporary fix you can simply checkout an older commit, such as:

``
git check out 0353a1840134b24b07ab61fd4490192f28c4db6b
`` 

This is the latest commit before this bug appears.

**Comment by leejw51** [comment]
the same error, it worked before

**Comment by teleprint-me** [comment]
SPM and BPE vocabularies were removed, so if you're using a non-huggingface model, you'll get this error. If you use facebooks hf model, it will work. This is simply due to the way the vocabularies are handled. I'll be looking into it over the next few days to see if I can fix the regression.

**Comment by ggerganov** [comment]
@teleprint-me Thanks for looking into this. Pinging also @strutive07 for any extra insight on this

**Comment by XiongjieDai** [comment]
Here is how I have gone through it in the last two weeks; basically you can try to convert your model to the huggingface format to get the config.json file.

`curl -o convert_llama_weights_to_hf.py https://raw.githubusercontent.com/huggingface/transformers/main/src/transformers/models/llama/convert_llama_weights_to_hf.py`

`python3 -m pip install -r requirements.txt`

`python3 convert_llama_weights_to_hf.py --input_dir models/7B/ --model_size 7B --output_dir models/7B/`

One trick is you don't need to install `accelerate` package. You will still get the config.json file although you will encounter `requires Accelerate error`. Then you can delete other half-way model files and convert the original model to ggml FP16 format.

**Comment by quanpinjie** [comment]
python convert.py ./models/34B/
Loading model file models/34B/consolidated.00.pth
Loading model file models/34B/consolidated.01.pth
Loading model file models/34B/consolidated.02.pth
Loading model file models/34B/consolidated.03.pth
params = Params(n_vocab=32000, n_embd=8192, n_layer=48, n_ctx=16384, n_ff=22016, n_head=64, n_head_kv=8, n_experts=None, n_experts_used=None, f_norm_eps=1e-05, rope_scaling_type=None, f_rope_freq_base=1000000, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=None, path_model=PosixPath('models/34B'))
Traceback (most recent call last):
  File "convert.py", line 1295, in <module>
    main()
  File "convert.py", line 1271, in main
    vocab = VocabLoader(params, vocab_dir)
  File "convert.py", line 342, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(str(fname_tokenizer), trust_remote_code=True)
  File "/data/code/llama.cpp/new/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 701, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/data/code/llama.cpp/new/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 1023, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/code/llama.cpp/new/lib/python3.8/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/code/llama.cpp/new/lib/python3.8/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "/data/code/llama.cpp/new/lib/python3.8/site-packages/transformers/utils/hub.py", line 400, in cached_file
    raise EnvironmentError(
OSError: models/34B does not appear to have a file named config.json. Checkout 'https://huggingface.co/models/34B/None' for available files.

**Comment by teleprint-me** [comment]
Between work, holidays, and helping out my cousins, I got sick over the holidays, so that's why I went MIA. Spent the last few days fighting off the fever. Starting to feel better now. Wondering if any progress was made, if not, I can pick up where I left off.

**Comment by teleprint-me** [comment]
I've been reviewing the `convert.py` script and verified the removal of both BPE and SentencePiece Vocab classes. My understanding was that these vocabularies would be merged, as indicated in my [comment on PR #3633](https://github.com/ggerganov/llama.cpp/pull/3633#issuecomment-1822142148). 

My efforts were aimed at maintaining backward compatibility while looking forward. This approach may have seemed like digression, but it was strategic, anticipating a more integrated solution which unfortunately didn't materialize as expected.

I have a [script](https://github.com/teleprint-me/to-gguf/blob/main/to_gguf/convert/fast.py) that follows what I envisioned for PR #3633. It's currently non-functional but fixable. Integrating all three vocab classes (`BpeVocab`, `SentencePieceVocab`, `HfVocab`) into one is a complex task that could lead to brittle code. However, I believe using a factory pattern, as I initially proposed, provides a more maintainable and scalable approach. This method allows for cleaner separation of concerns and easier adaptation to future changes. I'm committed to exploring this path, considering the time constraints and balancing other commitments.

My goal is to have a working fix in the next few days, though realistically, it might take a week of focused effort. As a user of llama.cpp and llama-cpp-python, I'm personally invested in resolving this. I appreciate everyone's patience and welcome any suggestions or collaborative efforts.

**Comment by teleprint-me** [comment]
I attempted to simplify the process by trying "the easy way," but unfortunately, it didn't behave as expected. As a result, I opened issue [#28370](https://github.com/huggingface/transformers/issues/28370) in the Transformers repository to address the underlying problem.

The previously utilized implementation, `BPEVocab` and `SentencePieceVocab`, in [convert.py](https://github.com/ggerganov/llama.cpp/blob/master/convert.py) had fewer lines of code and appeared more straightforward. However, since the new `VocabLoader` doesn't work as intended, this led to the need for further investigation.

Here's a snippet that showcases the idea:

```python
class VocabLoader:
    def __init__(self, params: Params, fname_tokenizer: Path) -> None:
        try:
            from transformers import AutoTokenizer
        except ImportError as e:
            raise ImportError(
                "To use VocabLoader, please install the `transformers` package. "
                "You can install it with `pip install transformers`."
            ) from e

        try:
            self.tokenizer = AutoTokenizer.from_pretrained(str(fname_tokenizer), trust_remote_code=True)
        except ValueError:
            self.tokenizer = AutoTokenizer.from_pretrained(str(fname_tokenizer), use_fast=False, trust_remote_code=True)
        except OSError:
            # Handle SPM model here
```

Exploring the [convert_slow_tokenizer.py](https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py) script from the Transformers repository allowed me to capture the differences and learn more about the problem.

I'm uncertain whether it's best to wait for a resolution, revert to the previous code in [convert.py](https://github.com/ggerganov/llama.cpp/blob/master/convert.py) for now, or explore other potential solutions. Nevertheless, the exploration was worthwhile, and I appreciate the learning experience it provided.

What's convenient about this approach is that we can convert to the fast tokenizer using the `convert_slow_tokenizer` function if it were to operate as expected.

Just exploring all of my options before jumping in and changing anything.

**Comment by ggerganov** [comment]
@teleprint-me Thank you for looking into this and appreciate the effort.

I'm honestly a bit lost myself here - didn't expect this to be such a difficult change and I really don't understand what is the issue now. 

In any case, don't want you to spend too much effort looking into this.
I will simply revert #3633 if this does not get fixed in a day or two

**Comment by teleprint-me** [comment]
@ggerganov I think there's a middle ground where we can have our cake and eat it too. I appreciate the feedback regardless. Hopefully it doesn't come to that.

**Comment by ggerganov** [comment]
The `convert.py` script should support the vanilla LLaMA models - this is the primary purpose of the script and the instructions in the README require it. For HF models, we have the `convert-hf-to-gguf.py` script. Based on the directory structures that you showed, I'm not sure why `convert.py` was chosen for implementing the `transformers.AutoTokenizer` support. It looks something more suitable for `convert-hf-to-gguf.py`?

> Let's aim for a solution that allows users to continue utilizing their existing models seamlessly while also aligning with transformers standards.

Of course, I just don't want to have invalid instructions in the README, so a temporary solution is to go back to the working version until we figure out the proper way to implement this.

**Comment by teleprint-me** [comment]
I completely understand. The integration in PR #3633 was primarily aimed at enhancing support for multilingual models. While the outcomes weren't as anticipated, the thoughtfulness and forward-thinking behind these efforts are invaluable.

I'm in the process of restoring the original functionality of `convert.py` and, simultaneously, exploring ways to smoothly integrate the advancements from #3633.

Technical debt is a natural part of any rapidly evolving project, and `llama.cpp` is no exception. The overwhelming demand and the community's active engagement are testaments to the incredible platform you've built.

I believe adopting a more collaborative strategy for managing these updates could be beneficial as you continue progress. It's about finding the right balance and ensuring that no single person bears the whole weight of this dynamic environment.

Your leadership and the community's passion are the driving forces behind the success of `llama.cpp`. You built something amazing here and people want to be apart it. I think that's pretty cool.

I'm working towards a preliminary PR. It should be up soon. I'll keep you in the loop.

**Comment by ipolytex** [comment]
> > I am running into this same issues, Can you post if you find a resolution?
> 
> As a temporary fix you can simply checkout an older commit, such as:
> 
> `git checkout 0353a1840134b24b07ab61fd4490192f28c4db6b`
> 
> This is the latest commit before this bug appears.

Hi 
Do you have the name for the branch?

**Comment by teleprint-me** [comment]
[Screencast from 2024-01-07 15-30-21.webm](https://github.com/ggerganov/llama.cpp/assets/77757836/97db7bd3-ba67-43af-b8f3-a4b31c515180)

It's working!

I was also able to preserve support for transformers as well!

🥳

**Comment by teleprint-me** [comment]
It's up: https://github.com/ggerganov/llama.cpp/pull/4818

**Comment by ggerganov** [comment]
@HighTemplar-wjiang and all, please confirm that conversion works with latest `master`

**Comment by teleprint-me** [comment]
**Note on `n_vocab` Parameter Handling:**

In the `convert.py` script, there is now a check to ensure the `n_vocab` parameter in `params.json` is properly defined before proceeding with the model conversion process. This parameter represents the vocabulary size of the model and is crucial for the conversion process to accurately reflect the model's structure.

I observed that in some instances, `n_vocab` is set to `-1`, a value that signifies an undefined or unspecified vocabulary size. The implications of proceeding with a conversion process under this condition are not fully understood and could potentially lead to inaccuracies or errors during model inference.

To safeguard against such uncertainties and to maintain the integrity and reliability of the conversion process, I decided to raise a `ValueError` if `n_vocab` is found to be `-1`. This is a precautionary measure to prompt users to manually verify and set an appropriate value for `n_vocab` in `params.json`. This approach ensures that the conversion process is carried out with a clearly defined and valid vocabulary size, reducing the risk of downstream issues.

I recognize that this decision may necessitate an additional step for users, but I think it is a necessary measure to ensure the correctness and stability of the converted models. We can further investigate the impact and significance of the `n_vocab` parameter and may update this behavior in future versions of the script based on new insights and findings.

Thanks @ggerganov.

**Comment by clairvoyant** [comment]
the conversion fails with the latest in master.  Reverting to    0353a1840134b24b07ab61fd4490192f28c4db6b allows convert.py to progress. 

the backtrace with master is
```
skipping tensor blk.20.attn_rot_embd
skipping tensor blk.21.attn_rot_embd
skipping tensor blk.22.attn_rot_embd
skipping tensor blk.23.attn_rot_embd
skipping tensor blk.24.attn_rot_embd
skipping tensor blk.25.attn_rot_embd
skipping tensor blk.26.attn_rot_embd
skipping tensor blk.27.attn_rot_embd
skipping tensor blk.28.attn_rot_embd
skipping tensor blk.29.attn_rot_embd
skipping tensor blk.30.attn_rot_embd
skipping tensor blk.31.attn_rot_embd
Writing models/7B/ggml-model-f16.gguf, format 1
Traceback (most recent call last):
  File "/opt/test/software/llama.cpp/convert.py", line 1658, in <module>
    main(sys.argv[1:])  # Exclude the first element (script name) from sys.argv
  File "/opt/test/software/llama.cpp/convert.py", line 1643, in main
    OutputFile.write_all(
  File "/opt/test/software/llama.cpp/convert.py", line 1188, in write_all
    check_vocab_size(params, vocab, pad_vocab=pad_vocab)
  File "/opt/test/software/llama.cpp/convert.py", line 993, in check_vocab_size
    raise ValueError(
ValueError: The model's vocab size is set to -1 in params.json. Please update it manually. Maybe 32000?
```

**Comment by teleprint-me** [comment]
@clairvoyant Read the exception.

```python
ValueError: The model's vocab size is set to -1 in params.json. Please update it manually. Maybe 32000?
```

This is a known issue with the `params.json`. You'll need to manually fix it by updating the value from `-1` to `32000`.

**Comment by teleprint-me** [comment]
@ggerganov 

Maybe we should issue a warning and revert to the fallback instead in the future? Commit  [f36a777](https://github.com/lorddoskias/llama.cpp/commit/f36a777bbc20ccf1e61d3d19777ecf57461c8dd7)  simply used a fallback without any warning. 

Maybe doing something similar would reduce the amount false negatives reported? I'm hesitant to support this approach because it isn't as concise as the exception and would be more difficult to spot as a result.

@clairvoyant 

Commit [0353a1](https://github.com/ggerganov/llama.cpp/tree/0353a1840134b24b07ab61fd4490192f28c4db6b) uses commit [799a1cb](https://github.com/ggerganov/llama.cpp/commit/799a1cb13b0b1b560ab0ceff485caed68faa8f1f) for `convert.py`. Commit [0353a1](https://github.com/ggerganov/llama.cpp/blob/0353a1840134b24b07ab61fd4490192f28c4db6b/convert.py#L827) doesn't apply any checks for the hyperparameters. 

**Please report _here_ if you experience any issues during inference**. I suspect you will, but they may range from subtle to obvious which could be misconstrued as an issue with the model. 

Personally, I'm not really a fan of the assertion as I consider this to be a brittle approach, but it's the only way to prevent false positives and avoid strange bugs throughout the pipeline. It's a time saver in the long run. Given the trade-offs, I made the decision to enforce it.

**Comment by ggerganov** [comment]
It's fine as it is since there is a workaround suggested. The old method created issues with other models where `n_vocab` cannot be deduced correctly

**Comment by calebheinzman** [comment]
Was there a solution to this?
I'm running:

```
!python llama.cpp/convert.py testing \
  --outfile testing.gguf \
  --outtype q8_0
```

And getting the error:

```
Loading model file testing/pytorch_model-00001-of-00002.bin
Loading model file testing/pytorch_model-00001-of-00002.bin
Loading model file testing/pytorch_model-00002-of-00002.bin
params = Params(n_vocab=32000, n_embd=4096, n_layer=32, n_ctx=4096, n_ff=11008, n_head=32, n_head_kv=32, n_experts=None, n_experts_used=None, f_norm_eps=1e-05, rope_scaling_type=None, f_rope_freq_base=None, f_rope_scale=None, n_orig_ctx=None, rope_finetuned=None, ftype=<GGMLFileType.MostlyQ8_0: 7>, path_model=PosixPath('testing'))
Found vocab files: {'tokenizer.model': None, 'vocab.json': None, 'tokenizer.json': PosixPath('testing/tokenizer.json')}
Loading vocab file 'testing/tokenizer.json', type 'spm'
Traceback (most recent call last):
  File "/content/llama.cpp/convert.py", line 1471, in <module>
    main()
  File "/content/llama.cpp/convert.py", line 1439, in main
    vocab, special_vocab = vocab_factory.load_vocab(args.vocab_type, model_parent_path)
  File "/content/llama.cpp/convert.py", line 1325, in load_vocab
    vocab = SentencePieceVocab(
  File "/content/llama.cpp/convert.py", line 391, in __init__
    self.sentencepiece_tokenizer = SentencePieceProcessor(str(fname_tokenizer))
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
```

**Comment by teleprint-me** [comment]
@calebheinzman 

`convert.py` only supports Llama, Llama-2, CodeLlama, Mistral, and Mixtral. For `transformers` (aka Hugging Face) models, the `--vocab-type hfft` flag was supposed to be utilized for supporting other languages because it did default to the `sentencepiece` vocab which uses `tokenizer.model`. This doesn't imply that you can use any `transformers` model with `convert.py` as it targets only the original models as initially intended. For any other supported architectures, `convert-hf-to-gguf.py` should be used instead. 

As for whether it was fixed or not, @cebtenzzre partially rolled back the patch I applied in PR #5041 due to conflicts with the code style and preference over the actual functional utility of the script. I don't care about this, I just care about whether or not the script functions as advertised. 

Personally, I just use formatters for whatever language I use and don't even think about it outside of my initial preferred settings which is very limited because I'd rather put energy into the code than worry about the way it looks. My primary concerns are always readability, maintainability, and functionality.

I attempted to find a middle ground within the patch so that the work previously applied by both @strutive07 and @TheBloke would continue to function and allow all 3 vocabulary styles to operate depending on user preferences, e.g. Byte-Pair Encoding, Googles SentencePiece, and the Hugging Face Fast Tokenizer used by the `transformers` module. 

The only way the `transformers` implementation is triggered is by passing the boolean flag to the factory that handles the vocabulary required by the model for conversion. While technically still functional, this is no longer apparent due to the removal of this information.

I never got a chance to update the docs, implement the complete changes, or the other stuff it needed. It has been modified since and I haven't had time to really look into it as it requires a much more in-depth review and I have other projects that also need my attention.
