### ISSUE TITLE
Add support for ViP-LLaVA?

### ISSUE THREAD

**Issue by mu-cai** [ggerganov/llama.cpp#4515]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Please provide a detailed written description of what you were trying to do, and what you expected `llama.cpp` to do as an enhancement.

# Motivation

Please provide a detailed written description of reasons why this feature is necessary and how it is useful to `llama.cpp` users.

Hi llama.cpp team,

[ViP-LLaVA](https://vip-llava.github.io/) is a region-level large multimodal model from LLaVA team that is capable of understanding visual prompts such as scribbles, bounding boxes, arrows, etc. 

There are only several lines of changes to the original LLaVA code. Huggingface already integrate ViP-LLaVA into the official transformers library. [https://huggingface.co/docs/transformers/main/model_doc/vipllava](https://huggingface.co/docs/transformers/main/model_doc/vipllava)

Consider adding ViP-LLaVA here?

Thank you!
Mu Cai

# Possible Implementation

If you have an idea as to how it can be implemented, please write a detailed description. Feel free to give links to external sources or share visuals that might be helpful to understand the details better.

**Comment by cmp-nct** [comment]
I tested the demo a bit and it's interesting.
Though I found it strange that the best language model (CoG-VLM) was not included in their benchmarks, as it blows llava totally out in terms of precision, detail detection, hallucinations and spatial information. 

The new 13-b model appears to be better in OCR than the previous llavas I tested, it makes similar errors but it detects significantly more text details. That ability is close to Qwen-VL now. It's not "great" but that improved noticeably.
It had some issues with it not stopping the generation in a test I ran, started repeating all over. Probably can be fixed with sampling but I've not seen that in other llavas yet.

At the same time the object detection is partly worse and partly better than before (ShareGPTV4 is the best llava variant I know here), in addition it has the new shape detection features that look interesting for some use cases.

(Would always be helpful to know which lines changed)

**Comment by mu-cai** [comment]
Hi John,

Thanks for your great work on evaluating our model. 
Here are the changes to 3 files:
* CLIP Model: change from single layer features to multi-layer features. https://github.com/mu-cai/ViP-LLaVA/blob/main/llava/model/multimodal_encoder/clip_4layer_encoder.py#L61
* Moldel builder: add this new model: https://github.com/mu-cai/ViP-LLaVA/blob/main/llava/model/multimodal_encoder/builder.py#L22
* Projector: Add layernorm: https://github.com/mu-cai/ViP-LLaVA/blob/main/llava/model/multimodal_projector/builder.py#L78

Thank you!
Mu

**Comment by cmp-nct** [comment]
I've looked through, I lack enough experience with the clip internals to quickly get that working.
@monatis and @FSSRepo are most experirenced with the codebase.

Though given your involvement, you might be able to do it yourself rather quickly and send a pull request ?
The llava inference is totally separated from everything else currently, it's in the examples/llava directory.

To give you an overview of what I think we will need to adapt locally:
`https://github.com/ggerganov/llama.cpp/blob/master/examples/llava/clip.cpp` < this is the main vision tower inference code
`https://github.com/ggerganov/llama.cpp/blob/master/examples/llava/llava.cpp` < here are helper functions 
`https://github.com/ggerganov/llama.cpp/blob/master/examples/llava/llava-cli.cpp` < main(), probably just a flag to add

In clip.cpp we'll need to change the clip_image_build_graph() mostly the new hidden-state multi-concatation method probably based on `ctx->vision_model.hparams.n_layer`
