### ISSUE TITLE
Weird performance difference between Ryzen 5900X and 7950X

### ISSUE THREAD

**Issue by nathanodle** [ggerganov/llama.cpp#4716]
Did some benchmarking tonight and have a Ryzen 5900X that beats a 7950X for some reason at 3.58 vs 3.37 t/s on Mixtral Q8_0.  Similar results for other quants and with Phi-2.  This shouldn't be the case:

- Both machines stock Ubuntu 22.04 server install
- Clean boot
- llama.cpp compiled from source on each machine
- 7950X has 4 more cores, AVX512, and its cores run at 4.5 vs 3.7 GHz (turbo 5.7 vs 4.8 GHz).    
- Both machines spawned threads equal to how many cores they have (16 vs 12)    
- The machine with the 7950X was running significantly cooler (better case / CPU cooler).    
- Both machines had 128GB at 3600 MT/s, 7950X has DDR5 while the 5900X is DDR 4.

Tried turning the 7950X down to 12 threads to match the 5900X, wondering if there's a weird heat/turbo thing and got 3.35 tokens/s so not that either

The only thing I wonder about the difference between the two machines is that the 7950X is getting compiled with AVX512 (which should help, I know).  Also, it shows AVX512=1, AVX512_VBMI=1, and AVX512_VNNI=1 at runtime regardless of if I set the LLAMA_AVX512 flags to on or off.

It's entirely possible that there's something I'm missing in the setup but wanted to report it here in case there's something strange going on with the AVX512 code?

**Comment by sorasoras** [comment]
Forget about AVX512 variants, Just use openblas instead.

**Comment by askmyteapot** [comment]
> * 128GB at 3600 MT/s, 7950X has DDR5 while the 5900X is DDR 4

This is one issue.  
DDR5 @ 3600MT/s is SLOW. Painfully slow. The main issue causing the DDR5 to be gimped is that it's latency is generally 2x that of DDR4 at the same speed.  

Unless you feel like doing some tuning of your DDR5, its going to be slower than the DDR4 system. I have read people are having better luck with getting faster frequencies and lower latencies on the newest bios releases for AM5, but it still will require manual tuning. 

One thing you can do to test the above, drop down to 64GB on both systems. The DDR5  board should train at a much higher frequency. You should still be able to test q8 mixtral, just with less context. 

Hope that helps.

**Comment by jrichey98** [comment]
I can say that memory bandwidth has a huge impact on llama.cpp.

I gave my old server to my father (Dual Xeon E5-2667 v2 w/8ch 1866MHz DDR3), and it blows the pants off my gaming pc/streaming server (Ryzen 5950X w/2ch 2800, RAM is 3200 but with all four slots full the memory controller defaults to 2666 and isn't reliable faster than 2800). Comparatively the Xeon w/8x1866=14928 vs the 5950X w/2x2800=5600 (Xeon 1.97 t/s vs 5950X .66 w/Llama2-70B).

Keep in mind CUDA (or any BLAS from Intel/AMD) will still help with prompt processing if you're compiled for it, even if no layers are offloaded to the GPU. I will also say that I get my best performance on the 16c/32t 5950X with 6 threads, not with 16 threads. Best performance will be offloading enough layers via -ngl to use up the VRAM, but not go over (really you want about half a gig still free).

First figure out the fastest number of threads to use for the CPU:
`./llama-bench -m ./models/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf -p 256 -n 32 -t 1,2,4,6,8,12,16 -ngl 0`
Optionally you can run something like the following to figure out the best number of graphics layers to offload:
`./llama-bench -m ./models/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf -p 256 -n 32 -t <best thread number> -ngl 8,12,16,20,24,28,30,33`
It may be a layer or two below the result you get, especially if you like large contexts. I usually set -ngl to a number and launching llama.cpp, then looking at how much VRAM is used (model + context), and adjusting till it's less than about VRAM - .5GB.

Mixtral is much faster than Llama2-70B derived models. My experience w/Mixtral Q4_K_M on my 5950X w/128GB 2800 ECC, 3090 24GB VRAM, is that I'm able to get 15.5 t/s with the following:
`./server -m ./models/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf --numa -c 8192 -t 6 -ngl 28`
I'll lose 5 t/s if I go up to -ngl 33 because it doesn't fit in vram anymore. Less or more will cause a drop.

If -ngl is set to 0 I get 4.55 t/s:
`./server -m ./models/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf --numa -c 8192 -t 6 -ngl 0`

If using a dual-cpu computer make certain to use the --numa option. It won't hurt if you're on a single CPU but it also may not help.

**Comment by Azeirah** [comment]
If you want me to provide any benchmarks for a specific model with my following setup, let me know:

- Ryzen 7900x
- 64GB ddr5@5200MT/s

**Comment by jrichey98** [comment]
Issue is that OP thinks [higher compute power](https://www.cpubenchmark.net/compare/2154vs3870vs3862vs5031/Intel-Xeon-E5-2667-v2-vs-AMD-Ryzen-9-5900X-vs-AMD-Ryzen-9-5950X-vs-AMD-Ryzen-9-7950X) should mean faster. That's true for some workloads (encoding/compression for example), but not AI. I just got off a call with my father tonight.

```
System			Video Card	Passmark	RAM		NGL		Q4_K_M		Q6
2x Xeon E5-2667 v2	A4000 w/16GB	24598		8x1866		10		-		5.5
Ryzen 5950X		3090 w/24gb	45781		2x2800		10		4.65		-
Ryzen 5950X		3090 w/24gb	45781		2x2800		0		4.55		-
Ryzen 5950X		3090 w/24gb	45781		2x2800		26		15.5		-
```

Compute power isn't what matters, it's [memory bandwidth](https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/#Memory_Bandwidth). All those threads are tripping over each other starved for memory bandwidth.

To get the optimal thread count, run command: ./llama-bench -m <model path> -p 256 -n 32 -t 1,2,4,6,8,12,16 -ngl 0

Also, if the system has a graphics card that'll make a big difference. Prompt processing is improved if compiled for a GPU, even without offloading layers to GPU. If you have enough VRAM to load the entire model you'll get really good performance.

If he want's to run the model on CPU, a Xeon Gold 6138 system ($30/cpu on ebay) would be absolutely fantastic, especially if equipped with 8-ch of 2400 (2933 if you ever want to upgrade to a 62xx series). Otherwise, get a couple 3090's. Shop for memory bandwidth, not processing power.
