### ISSUE TITLE
Question : Is it normal when the prompt size is large, the result quality will be degraded ?

### ISSUE THREAD

**Issue by x4080** [ggerganov/llama.cpp#4744]
Hi, I wonder if its normal. Using m2 pro, context size 4096 (but prompt is about 2500 ish), instruction is "create 5 bullet points summary from the document provided", it works perfectly if I cut down the prompt to about 1000 tokens, but using the original prompt size, the result is bad like :
- creating 10 bullet points
- outputting question and answer
- outputting gibberish texts
- etc

I tried using 3 models (dolphin phi, docsgpt, mistral ft optimized) - all same result (but different level of quality)

here's the related params :
```
./main -r "<|im_end|>" -ngl 1 -t 0 -m ./models/mistral-ft-optimized-1218.Q3_K_M.gguf --color -c 4096 --temp 0.1 -n -1 -f prompts/mistral.txt --min_p 0.5 --top_p 1 --top_k 50 --repeat_penalty 1.1
```

Thanks for answering

**Comment by cmp-nct** [comment]
I'm not sure how well this works without sliding attention window or NTK-type rope scaling of the kv cache.

As a first step, try apply a scale using   --rope-freq-scale / --rope-freq-base
I believe both will use NTK, the -h documentation isn't too clear and I didn't check the current implementation to be sure so best try both.
Maybe that helps

**Comment by x4080** [comment]
@cmp-nct Thanks, how should I use min_p value for temp of 0.1 ?
I'll try your scaling suggestion.

Today I downloaded new model named "dolphin-2.6-mistral-7b-dpo-laser-Q4_K_M.gguf" and after some testing - it still consistent with using "large" context even if its only about 2500 ish that when using other models mentioned all fall apart

**Comment by cmp-nct** [comment]
Hard to say regarding the native capabilities, if the GGUF has rope scaling settings it would automatically apply that configuration.
Also the models you use (just as so many these days) are a wild mix of various merged models, maybe they don't work well with large context anymore. I doubt they were tested beyond the benchmarks which are all low context questions.

2500ish is about the limit of traditional rope settings, beyond that models became less stable without scaling because of the math behind the default settings. 

regarding min_p: min_p basically protects the sampling from choosing crap tokens. So min_p can work well even with very high temperatures (even above 1.0).
If you use a very low temperature you basically disable most of the benefits of min_p, it doesn't hurt either.
If you want to choose the highest probability token you'd use greedy sampling (temp setting below 0), in that case the sampling variability is removed.

**Comment by x4080** [comment]
@cmp-nct Thanks

**Comment by pudepiedj** [comment]
> Hi, I wonder if its normal. Using m2 pro, context size 4096 (but prompt is about 2500 ish), instruction is "create 5 bullet points summary from the document provided", it works perfectly if I cut down the prompt to about 1000 tokens, but using the original prompt size, the result is bad like :
> 
> * creating 10 bullet points
> * outputting question and answer
> * outputting gibberish texts
> * etc
> 
> I tried using 3 models (dolphin phi, docsgpt, mistral ft optimized) - all same result (but different level of quality)
> 
> here's the related params :
> 
> ```
> ./main -r "<|im_end|>" -ngl 1 -t 0 -m ./models/mistral-ft-optimized-1218.Q3_K_M.gguf --color -c 4096 --temp 0.1 -n -1 -f prompts/mistral.txt --min_p 0.5 --top_p 1 --top_k 50 --repeat_penalty 1.1
> ```
> 
> Thanks for answering

Thank you for raising this because your question prompted me to try a `-f <file>` prompt using `mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf` and I found that it worked extremely well on what sounds like similar hardware (M2 MAX 32GB) using the interactive mode.

The command-line below invokes the `main` llama model executable, loads the `mixtral` model, reads a text file (which appears as the initial response in the output window), then will summarise (when asked) in bullet-points and respond to questions for a considerable length of time afterwards until it exceeds the `4096` context-window. The input file is `1647/9517` words/characters. I haven't pushed it further in terms of size but I will. Also need to experiment to see what the largest `-c` value it will allow is. With the `sudo sysctl` trick this uses about `(26028.86 / 27500.00)` of VRAM.

It doesn't exit gracefully, but fails the `GGML_ASSERT` at `llama.cpp/ggml-metal.m:2128: false` so it would be good if there were a way to track tokens used during the conversation (maybe there is and I haven't found it) or get a warning before it stops with a `zsh: abort`, but I'll raise that as a separate issue with @ggerganov for an enhancement if I can't work out how to do it myself.
```
sudo sysctl iogpu.wired_limit_mb=27500
./bin/main -m ../models/Mixtral-8x7b/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf -c 4096 -ngl 99 -n -1 -s 1 -i -ins -f "/absolute/path/US1134.txt" -ctk q8_0 --override-kv llama.expert_used_count=int:3
```
Reset the VRAM by replacing `27500` with `0` after you're done. (I owe this incredibly useful trick to someone here with a `@z...` moniker but I've lost the reference; apologies).

**Comment by x4080** [comment]
@pudepiedj Thanks for your information. Maybe it depends on the model then, some model will degrade and some wont. Glad to see that mixtral have good result
