### ISSUE TITLE
A chatbot-ui based ui for llama.cpp server

### ISSUE THREAD

**Issue by yportne13** [ggerganov/llama.cpp#4811]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [*] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [*] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [*] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

hey guys, I want to implement a llama.cpp server on my own but i haven't find a beautiful static web yet, so I fork the chatbot-ui and do a little change to feat the llama.cpp server and to make it possible to build as a static web(so that llama.cpp server can serve it on it's own). the repository is [here](https://github.com/yportne13/chatbot-ui-llama.cpp). Due to my poor javascript and typescript ability, this is the best I can do. if anybody want to do more improvement, just fork it

# Motivation

introduce to my little work

# Possible Implementation

I don't know, at least it is work for me now. There must be so many telent people that know how to improve it than me

**Comment by Huge** [comment]
In the parent repo I have read
> You will need to install Docker to run Supabase locally.
Is that the case with your fork or (where )is the history stored?

**Comment by yportne13** [comment]
> In the parent repo I have read
> 
> > You will need to install Docker to run Supabase locally.
> 
> Is that the case with your fork or (where )is the history stored?

I was making this web right before chatbot-ui release new version(chatbot-ui 2.0). so the chat history is stored in local browser storage, not Supabase. as the parent repo said:

> Previously, we used local browser storage to store data.

it is a static web, the only thing you need is the server that comes from llama.cpp and /out dir comes from my repo. no Docker or any other things need (^^)

**Comment by stockmin3r** [comment]
hi! that's a nice UI. I've been working on an "LLM Proxy" here: https://github.com/stockmin3r/llm_proxy.git - a simple C wrapper around llamacpp's main executable. It can load multiple llamacpp processes and will eventually be able to assign different models to each instance. It uses pipes and epoll on linux in order to get notifications on when llamacpp is writing to its STDOUT which llm_proxy then reads the tokens from and currently sends them to a discord bot (but there could be a pub/sub feed as well). 

Still haven't got the windows API code working yet and lots of bugs still to ferret out but I would like to add a UI to it something along the lines of chatbot-ui. There could be a grid of different categories such as 'medical,coding,law,etc' where different models from HF would be listed, and clicking on one would download it from HF and 'load' it via llamacpp. Then multiple chat prompts could be managed, all for different models and they could all be switched around as well and new ones could be kept track of (by category) since HF can be polled every now and then to see if there are any new models released by specific users.

**Comment by redthing1** [comment]
Hi @yportne13,

Thank you for the static chatbot-ui base.
I continued your work and added several additional features:
https://github.com/redthing1/red-chat-ui

One of them was support for a kind of plugin API. It's not complete and still in a testing state, but I'm continuing development. I also added chat templates for more models.
