### ISSUE TITLE
how to use GGML-Tips-&-Tricks in new code？

### ISSUE THREAD

**Issue by 2213601279** [ggerganov/llama.cpp#4819]
https://github.com/ggerganov/llama.cpp/wiki/GGML-Tips-&-Tricks
If you follow this link, an error will appear after you modify it.
```
/media/harijizhang/793D8F946E3470B9/llama.cpp/llama.cpp: In function ‘int llama_decode_internal(llama_context&, llama_batch)’:
/media/harijizhang/793D8F946E3470B9/llama.cpp/llama.cpp:7229:9: error: ‘n_past’ was not declared in this scope
 7229 |     if (n_past % 45 == 0) {
      |         ^~~~~~
gmake[2]: *** [CMakeFiles/llama.dir/build.make:76：CMakeFiles/llama.dir/llama.cpp.o] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:732：CMakeFiles/llama.dir/all] 错误 2
gmake: *** [Makefile:146：all] 错误 2
```
The compilation failed because it is incompatible with the current llama.cpp

**Comment by bullno1** [comment]
After the move to batch, n_past doesn't exactly exist anymore.

I guess `batch.pos[batch.n_tokens - 1]` is an approximation. It should work for a single sequence batch.

I don't know why it's `% N` though, that would output the graph every few tokens?

**Comment by Javipove** [comment]
Can any one explain how to solve this problem?

**Comment by 2213601279** [comment]
> Can any one explain how to solve this problem?

hey , bro, just n_past is now replaced with batch.pos[]  ,it will be okay 


https://github.com/ggerganov/llama.cpp/wiki/GGML-Tips-&-Tricks

**Comment by Javipove** [comment]
But then how it should look the resulting modification to print the computational graph? Because performing that change it doesn't compile and the other part of the code to modify do only save one layer doesn't exist. Sorry I am a bit new in this but the guide for this "simple" modification is not correct

<img width="560" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/62990073/9a9e118f-9bba-4a79-a57d-355b938efd36">
