### ISSUE TITLE
Loading GGUF models on iOS with swift package gives assertion error

### ISSUE THREAD

**Issue by l3utterfly** [ggerganov/llama.cpp#4837]
`ggml.c:4772` -> `b->type == GGML_TYPE_I32`

Using TinyLlama-v1.0-Q5. The same model works on android and PC with no issues.

**Comment by ggerganov** [comment]
You need to update to latest `llama.cpp`

The reason is that the `llama.cpp` Swift Package depends on `ggml` and the type enum in `ggml` has been updated yesterday. So your `llama.cpp` is using an old `ggml` header while linking to the new `ggml` library.

We should find a way to eliminate `ggml.h` from the `spm-headers`:

https://github.com/ggerganov/llama.cpp/tree/master/spm-headers

Not sure if simply deleting it would fix this

**Comment by l3utterfly** [comment]
Thank you, updating to the latest works.
