### ISSUE TITLE
Error while converting gpt-2 model to gguf

### ISSUE THREAD

**Issue by Stuv7CB** [ggerganov/llama.cpp#4888]
Hello

I'm trying to convert https://huggingface.co/ai-forever/ruGPT-3.5-13B model to gguf using convert-hf-to-gguf.py script
`python convert-hf-to-gguf.py path/to/ruGPT-3.5-13B`

But I get following error:
`Can not map tensor 'transformer.h.0.attn.masked_bias'`

If I mark this tensor to skip here: https://github.com/ggerganov/llama.cpp/blob/master/convert-hf-to-gguf.py#L1017
gguf file successfully created.

But if I try to load to load gguf, I receive error about wrong number of tensors. In model there are 485 tensors, but header states that model contains 486.

As far as I understand model have already `output.weight` tensor so gguf_writer.add_tensor doesn't add it, but increase number of tensors written in header. 

I'm not sure but it seams that this if-block should be removed because when I remove it created gguf file could be successfully loaded by ./main.

If so I may create PR with fixes

**Comment by ggerganov** [comment]
Instead of skipping the tensors like this, try adding them to `MODEL_TENSOR_SKIP` dict:

https://github.com/ggerganov/llama.cpp/blob/1e7694eee7ff39b9fef7cd19fad9ad4892725357/gguf-py/gguf/constants.py#L400-L418

**Comment by Stuv7CB** [comment]
As far as I understand these constants aren't used in convert-hf-to-gguf.py. If I try to use convert.py instead, it doesn't work with following error
`KeyError: ('torch', 'BoolStorage')`

**Comment by MirrorAzure** [comment]
Encountered same problem while trying to convert gpt2 model to gguf:
`Can not map tensor 'transformer.h.0.attn.masked_bias'`

Looks like the problem lies here:
https://github.com/ggerganov/llama.cpp/blob/b05102fe8cfa9893851c6bf6efd15cdc20b6afa2/convert-hf-to-gguf.py#L1141

GPT2-models don't use some of layers, so they get skipped. However, in our case layer is called `attn.masked_bias`, which is not checked.
