### ISSUE TITLE
Build with AMD AOCC + AOCL (CPU only)

### ISSUE THREAD

**Issue by GANJAC** [ggerganov/llama.cpp#5005]
Hi, on my Debian 11 (AMD EPYC 75F3 32-Core Processor, 64 GB ram) i've just installed AMD AOCC + AOCL:

https://www.amd.com/en/developer/aocc.html
https://www.amd.com/en/developer/aocl.html

How can i build llama.cpp with that ? And what arguments for the best optimization (BLAS, LAPACK ...)

Any suggestions are super appreciated!

**Comment by pnb** [comment]
I haven't tried AOCC but AOCL works fine and produces a small speedup versus no BLAS library, though I haven't compared it to others. You can compile like this, more or less (based on my bash history from November):

```bash
# Assuming you downloaded AOCL from https://www.amd.com/en/developer/aocl.html and put it in ~
cd
tar xf aocl-linux-gcc-4.1.0.tar.gz
cd aocl-linux-gcc-4.1.0
./install.sh
cd
git clone https://github.com/ggerganov/llama.cpp.git
cd llama.cpp
mkdir build && cd build
source ~/aocl/4.1.0/gcc/amd-libs.cfg
cmake .. -DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=AOCL -DBLAS_INCLUDE_DIRS=~/aocl/4.1.0/gcc/include
make -j
```

This is assuming Linux.

**Comment by GANJAC** [comment]
Thank you Nigel!!! Now i try to complete the commands with the AOCC clang++ and Zen3 specific optimization, if everything works i share the results here.

**Comment by HansvanHespen** [comment]
Exactly. If I do in the dockerfile ENV cmake_cxx_flags="-march=znver2", then it turns out in the logs that somewhere, make puts afterwards -march=native, thus cancelling my -march=znver2 directive. The end result is a sigill on the linux of the cloud. How do you crosscompile? How do you adapt the dockerfile so that the gcc compiler compiles to the target AMD Epyc processor, and not my Intel i7 cpu?
