### ISSUE TITLE
Move the third-party build / deploy scripts to a separate repository

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#506]
It keeps bothering me to see these scripts in the source root.
They cannot live anywhere except in the root of the repo, so therefore it is time to go.

Task: create `llama.flake` or `llama.deploy` repo and move the scripts there.

**Comment by j-f1** [comment]
Another option: move all of the source code to an `src` folder and leave the repo root for infrastructure things like makefiles/the README/support for packaging infrastructure.

**Comment by mdabir1203** [comment]
> It keeps bothering me to see these scripts in the source root. They cannot live anywhere except in the root of the repo, so therefore it is time to go.
> 
> Task: create `llama.flake` or `llama.deploy` repo and move the scripts there.

I made a repo based on the instruction. Wanted to ask shall I include a readme ?
link: https://github.com/mdabir1203/llama.deploy/blob/main/README.md

**Comment by MostAwesomeDude** [comment]
In NixOS/nixpkgs#225058, downstream indicates that they'd prefer to see the Nix flake remain, because it ultimately gives upstream (you!) control over how everything is built and packaged. If you remove the flake, then somebody like @dit7ya will choose the packaging and it'll be added to `nixpkgs`. In particular, we'll probably break out `ggml` into its own expression, and patch it to do CPU checks at runtime. Then `llama.cpp`, `whisper.cpp`, and `rwkv.cpp` would each be based on that same single `ggml` expression.

This isn't actually desirable! Any given snapshot of `llama.cpp`, with its `flake.nix` and `flake.lock`, should be reproducible and have its own consistent ABI for models. This is because the flake depends on `nixpkgs`. But if we do it the other way around, then `nixpkgs` depends on whatever ABI happened to be in the given snapshot of `llama.cpp`. In practice, this means that users will usually have stale versions of both `ggml` and `llama.cpp`.
