### ISSUE TITLE
Thread hanging issues after the sched_yield changes / Intel CPU slowdowns related to E-cores

### ISSUE THREAD

**Issue by kalomaze** [ggerganov/llama.cpp#5225]
It appears https://github.com/ggerganov/llama.cpp/pull/4761 caused a regression for my system.

Occasionally, it will "hang" when continuing an inference from where it left off (assuming there was no context reprocessing necessary).

<img width="576" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/66376113/76d6ca3e-bfc5-4655-b702-a938ff986360">

This can last over 30 seconds.

The e-cores being maxed out seems to cause some sort of constant slowdown for CPU inference in general.

For example, I get roughly ~140ms per token instead of ~160ms per token on partial offload Mixtral (16/33 layers) if I set custom processor affinity to prevent llama.cpp from using the E-cores whatsoever:

<img width="251" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/66376113/d91285e6-3205-4827-a351-3af61b478a75">

**Comment by ggerganov** [comment]
In general, you don't want to use E-cores with `llama.cpp`

**Comment by kalomaze** [comment]
> In general, you don't want to use E-cores with `llama.cpp`

Is there a way that this could be done automatically rather than having to be done manually?

**Comment by kalomaze** [comment]
> AFAIK simply setting `-t` equal to the number of P-cores or less should never cause the E-cores to be used

That is not happening.

**Comment by kalomaze** [comment]
https://github.com/ggerganov/llama.cpp/pull/5419
This PR helps to mitigate the issue, as CPU performance is generally back to where it was when Mixtral first released.
However, there's still an occasional "pause" in the generation.

**Comment by kalomaze** [comment]
If I go back to:
https://github.com/ggerganov/llama.cpp/pull/3192/files#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5d

And revert these changes related to scheduling:
![image](https://github.com/ggerganov/llama.cpp/assets/66376113/e9e3ca31-bb5e-4412-a8c2-cb6541543ecc)

It entirely fixes the issue.

I cannot reproduce the fix on by simply preventing sched_yield from being called on latest.
@ggerganov any pointers?

**Comment by kalomaze** [comment]
It seems like the issue is using a check _at all_.

<img width="694" alt="image" src="https://github.com/ggerganov/llama.cpp/assets/66376113/615b9d39-758f-41f8-98ab-30661331c3ab">

I get a 1.2x prompt processing speed improvement as a direct result of making these changes.

**Comment by ggerganov** [comment]
As the comment in the code says, it's not clear how to fix this properly. If we make the proposed change, then other configurations start suffering. Not sure if this was discussed somewhere already, but we likely need to separate all BLAS stuff in a separate backend in order to avoid interference between the `ggml` threads and the BLAS threads

**Comment by schmorp** [comment]
I would like to add that newer I-quants change the picture here. With traditional quants, using more than the 8 P-cores on my system slows down inference a bit (it's memory-bound), but with the more complicated I-quants, using 20 instead of 8 threads (i.e. utilizing e-cores) almost doubles the speed, probably because the 8 P-cores cannot saturate the memory bandwidth.
