### ISSUE TITLE
Faster IQ3_XSS AVX2 text generation

### ISSUE THREAD

**Issue by Dampfinchen** [ggerganov/llama.cpp#5290]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Hello,

I am trying out Mixtral on my 6 GB RTX laptop right now, using the new IQ3_XXS quant. And while I was very pleased to see much faster prompt processing speed than I've expected, the actual text generation seems very slow.

i7 9750H, 32 GB RAM, RTX 2060, 7 layers offloaded, latest llama.cpp build (b2050)
` llama_print_timings:        load time =    5158.79 ms
llama_print_timings:      sample time =      57.23 ms /   180 runs   (    0.32 ms per token,  3145.20 tokens per second)
llama_print_timings: prompt eval time =   63638.58 ms /  3606 tokens (   17.65 ms per token,    56.66 tokens per second)
llama_print_timings:        eval time =   85460.87 ms /   179 runs   (  477.44 ms per token,     2.09 tokens per second)
llama_print_timings:       total time =  149319.26 ms /  3785 tokens`

As you can see, the text generation speed is 477 ms/t which is much slower than a 13b model. People were previously telling me text generation is roughly on par with a 13B model as only 2 experts are active, however this doesn't seem to be the case here. For reference, my text generation speed for 13B Q4K_S is around 200 ms/t, which is more than double as fast. 

This is probably not a bug and it appears IQ3 quants are running slow on the CPU right now.

# Motivation

If possible, having the IQ3 quants be as fast as the k-quants would be very nice to have. I think this is a really fantastic quant that makes Mixtral available to more people.

**Comment by Dampfinchen** [comment]
As a comparison, I've added Mixtral 8x7B Q4K_S.

![llama cpp](https://github.com/ggerganov/llama.cpp/assets/59751859/4ca55ccf-0746-475c-b30c-30eafbabf85a)

Generation is much faster than with IQ3_XSS. (477 ms/t vs 318 ms/t), even though I was able to offload more layers with IQ3_XSS.

@ikawrakow is this normal behavior? What makes it so much slower?

**Comment by ikawrakow** [comment]
So, here is what I have on my computer running on the CPU (Ryzen-7950X):

| model                          |       size |     params | backend    |    threads | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ---------: | ---------- | ---------------: |
| llama 7B IQ3_XXS - 3.0625 bpw  |  17.05 GiB |    46.70 B | CPU        |         16 | tg 128     |      9.51 ± 0.03 |
| llama 7B IQ3_XXS - 3.0625 bpw  |  17.05 GiB |    46.70 B | CPU        |          8 | tg 128     |      7.89 ± 0.02 |
| llama 7B IQ3_XXS - 3.0625 bpw  |  17.05 GiB |    46.70 B | CPU        |          4 | tg 128     |      4.47 ± 0.01 |
| llama 7B Q4_K - Small          |  24.91 GiB |    46.70 B | CPU        |         16 | tg 128     |      7.42 ± 0.02 |
| llama 7B Q4_K - Small          |  24.91 GiB |    46.70 B | CPU        |          8 | tg 128     |      7.75 ± 0.01 |
| llama 7B Q4_K - Small          |  24.91 GiB |    46.70 B | CPU        |          4 | tg 128     |      7.58 ± 0.01 |
| llama 13B Q4_K - Small         |   6.91 GiB |    13.02 B | CPU        |         16 | tg 128     |      7.50 ± 0.01 |
| llama 13B Q4_K - Small         |   6.91 GiB |    13.02 B | CPU        |          8 | tg 128     |      7.82 ± 0.01 |
| llama 13B Q4_K - Small         |   6.91 GiB |    13.02 B | CPU        |          4 | tg 128     |      7.75 ± 0.01 |

Basically, if you have enough compute, inference becomes memory bound, and `IQ3_XXS` wins by being smaller, so requiring less data to be loaded from RAM. But of you do not have enough compute as it is in your case, then inference speed is compute bound. In that case, 4-bit quantization will always win because much less bit-fiddling is required to reconstruct the model weights. You see `Q4_K_S` has (almost) the same inference speed for 4+ threads. I.e., on my system, it is already memory bound at 4 threads (and running more than 8 threads actually hurts performance because the threads are fighting for access to the memory bandwidth). Not so with `IQ3_XXS`, where at 4 threads speed is less than half of 16 threads.

Is it possible to speed up CPU inference for `IQ3_XXS`? My guess is yes, but I have not put any significant effort into it. There was the recent effort to improve AVX2 performance for `IQ2_XS` (#5187), but one cannot just reuse what was done there because bits are arranged differently in `IQ3_XXS`. When doing such optimizations one needs to shuffle bits around, and I totally dislike doing that because I'm constantly confused about the correct shuffle mask.
