### ISSUE TITLE
Build your windows binaries with Clang and not MSVC.

### ISSUE THREAD

**Issue by BadisG** [ggerganov/llama.cpp#534]
Hello,

Your [windows binaries releases](https://github.com/ggerganov/llama.cpp/releases) have probably been built with MSVC and I think there's a better way to do it.

# Expected Behavior

I have a Intel® Core™ i7-10700K and the builds are supposed to recognize those architectures: [AVX | AVX2 | FMA | SSE3 | F16C]

# Current Behavior

Windows (MSVC build)
```
system_info: n_threads = 14 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 0 | 
NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | VSX = 0 |
```
It misses the FMA, SSE3 and the F16C architectures.

# Fix with Clang

If you build with Clang you'll get all the architectures right:

Windows (Clang build)
```
system_info: n_threads = 14 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | 
NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
```

# How to build with Clang

1. Install Clang
To do this, you have to install something called [LLVM](https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0) 
I downloaded LLVM-16.0.0-win64.exe but it could be LLVM-16.0.0-win32.exe for people that has Windows 32 bit.
During the install, Choose "Add LLVM to the system PATH for all users"

After the installation you can verify if you have clang installed on your computer by running ```clang --version``` on your cmd
Normally you'll get something like this
```
C:\Users\Utilisateur>clang --version
clang version 16.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

2. Install [chocolate](https://chocolatey.org/install#individual) (that's necessary to install Ninja (which is necessary to build with clang 😵 ))
To do that, open powershell as an administrator and run this command:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

3. Install Ninja
Open powershell as an administrator and run this command:
```
choco install ninja
```

4. Build with clang
run your cmd on the llama.cpp repository and run those commands
```
cmake -G "Ninja" -S . -B Windows-build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
cmake --build Windows-build/ --config Release
```

You'll get your exe here:
```
.\Windows-build\bin
```

**Comment by x02Sylvie** [comment]
I believe the issue with MSVC would be fixed with this pull request https://github.com/ggerganov/llama.cpp/pull/375

**Comment by BadisG** [comment]
@x02Sylvie we should test the speed and the perplexity of both of those compilators and see if one is better than the other. If Clang has significantly better results than MSVC then we should switch to this one for the futur builds releases.

**Comment by rupakhetibinit** [comment]
Does it have performance benefits while running the one compiled with llvm/clang?

**Comment by anzz1** [comment]
For simple changes, there is also the case of enabling [/fp:fast](https://learn.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior?view=msvc-170#fast) which could possibly increase performance significantly but obviously should be tested how it affects perplexity. It should in any case probably stay at /fp:precise for quantization.cpp, but for running the models the performance/accuracy of /fp:fast should be tested.

For more involved optimization , there is also [PGO](https://learn.microsoft.com/en-us/cpp/build/profile-guided-optimizations?view=msvc-170) .

Definitely the best performing and more accurate compiler should be used for the releases. I just rebased the [llama-patch-enable-fma-msvc](https://github.com/ggerganov/llama.cpp/tree/llama-patch-enable-fma-msvc) to master for easier testing, however only the ggml.c is the only changed file anyway.

Contradicting information is found online regarding the performance of MSVC vs Clang, some claiming a performance benefit of multiple times in one way or another. It obviously depends on the use case too, so this is something that only testing can show.

However, due to the project being clean C and does not rely on C++/STL heavily, I'd expect the binary output between compilers to be minimal but I could be wrong as there could be major differences on how the Clang / MSVC optimizes the hottest calculation codepaths and even smaller differences could add up to a considerable performance delta.

**Comment by JohnnyOpcode** [comment]
I wonder if we can squeeze a bit (pun) more performance using the Intel OneAPI Toolkits.

https://www.intel.com/content/www/us/en/developer/tools/oneapi/toolkits.html#base-kit
