### ISSUE TITLE
Can't find config.json

### ISSUE THREAD

**Issue by felipeblin** [ggerganov/llama.cpp#5345]
I use mistralai/Mistral-7B-Instruct-v0.2 and fine-tuned (colab pytorch) and then uploaded to huggingface. (y the way the model worked in colab. Then I downloaded locally and tried to convert to GGUF format but I get this error:
llama.cpp/convert-hf-to-gguf.py", line 167, in load_hparams
    with open(dir_model / "config.json", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory:
IN FACT, there is no config.json in the directory (where the model is)
By the way I tried with convert.py and got the error:
  raise Exception(f"Can't find model in directory {path}").
  
  THis the directory model content:
  
![image](https://github.com/ggerganov/llama.cpp/assets/38219218/a7ce2113-b98b-4101-98fc-18fa2209ff05)
Thanks!

**Comment by jeppelsh** [comment]
Got the same for LLaMA 3, downloaded officially from Meta

**Comment by teleprint-me** [comment]
Use the huggingface models. Not the 3rd party distributions. The huggingface models have better support due to community solidarity around it. The `convert.py` no longer operates as it should with the original Mistral models, which I consider to be unfortunate. There is a PR looking to offload RAM usage by dynamically allocating tensors at runtime, so this should reduce dependence on the original `convert.py` script over time. I'm not sure whether this dependence is a good thing or not. Only time will tell.
