### ISSUE TITLE
[Request/Enhancment]1-bit quants

### ISSUE THREAD

**Issue by benxh1995** [ggerganov/llama.cpp#5390]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x ] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x ] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

I would like to request an enhancement of the quantification process to allow 1bit quants. They don't have to be SOTA, just usable enough for users. 

# Motivation

The motivation for this request is to allow users with 8GB RAM and 16GB RAM access to the higher end of models (with 1bit quants ~70B should approximately fit in 16GB RAM).

**Comment by JohannesGaessler** [comment]
I'm not that knowledgeable when it comes for efficient quantization techniques (@ikawrakow is the expert for that) but I don't expect 1 bit quantization to be usable. Do you have any references for papers or code where someone has previously achieved usable 1 bit quantization?

**Comment by benxh1995** [comment]
I know of BitNet and QMoE:

https://arxiv.org/abs/2310.16795

https://arxiv.org/abs/2310.11453


And there is this approach which is similar to GPTQ: https://arxiv.org/abs/2310.00034

**Comment by benxh1995** [comment]
Highly relevant fresh paper describing binarization (1 bit quant) SOTA: https://huggingface.co/papers/2402.04291

**Comment by ikawrakow** [comment]
@benxh1995 Have you ever interacted with a model that has a perplexity of 32? (value for LLaMA-v2-7B from the SOTA paper you are quoting). A different question: Do you think that the 1-bit quantized LLaMA-v2-70B model with perplexity of of 8.4 will be competitive with a 4-bit quantized 7B model?

Don't get me wrong, the results of the paper are remarkable for 1-bit quantization, but that does not make them useful in practice. Btw., the current SOTA for 2-bit quantization has a perplexity of 3.94 for LLaMA-v2-70B. I guess, putting that into the paper instead of the hopelessly outdated GPTQ 2-bit result would make the 1-bit look much less impressive. In this repo you have a functioning 2-bit quantization with a LLaMA-v2-70B perplexity of 4.07. Have you tried it? If not, please do (you can download ready 2-bit quantized models from [here](https://huggingface.co/ikawrakow/various-2bit-sota-gguf)). If you did, and you thought that it was not adequate, you can be assured that you will like 1-bit models even less.

**Comment by nelsonhurstdev** [comment]
Interesting. This may allow 120B Models to run at decent speeds on Consumer GPUs. This quant could be used to target 70b+ models. I feel like anything smaller may be useless.

**Comment by mechanicmuthu** [comment]
Just guessing out loud. On 1 bpw do we reach a point where bitwise operators can come into play to speed up the low level computation?

**Comment by ikawrakow** [comment]
> Just guessing out loud. On 1 bpw do we reach a point where bitwise operators can come into play to speed up the low level computation?

Not for this variant. Quants take values of -1, 0, 1. If we one day arrive at the point where we can separate salient from non-salient weights, then one would hope to be able to use binary quants for the non-salient version. This is what BiLLM does. But then again, looking at the massive difference in quantization error between this PR and BiLLM, this may turn out to be not valuable.

But given that you are bringing this up, are you dissatisfied with the performance? I get 212 t/s for TG-128 of a 7B model on my GPU (RTX-4080), which is ~60% higher than `Q4_0`. My best guess is that at this matrix multiplication speed, in the range of 40% of the time goes into thread synchronization and other kernels that are independent of the quantization used.

**Comment by JohannesGaessler** [comment]
>Just guessing out loud. On 1 bpw do we reach a point where bitwise operators can come into play to speed up the low level computation?

I didn't test the performance of the new quantization myself but generally speaking the improvements from more efficient compute at low batch sizes are relatively small. I expect bitwise operations to only make a large difference if there were custom matrix multiplication kernels for large batch sizes (like mul_mat_q) that are compute bound rather than I/O bound.
