### ISSUE TITLE
Fiddler: CPU-GPU Orchestration for Fast Inference of Mixture-of-Experts Models

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#5484]
# Feature Description
Fiddler is a fast inference system for LLMs based on Mixture-of-Experts (MoE) architecture at local devices. It allows you to run unquantized Mixtral-8x7B model (>90GB of parameters) with >3 token/s on a single 24GB GPU.

# Motivation
so it can allow people to run much bigger MoE model than just load everything into VRAM.
https://arxiv.org/abs/2402.07033

# Possible Implementation
https://github.com/efeslab/fiddler
![image](https://github.com/ggerganov/llama.cpp/assets/6722084/24eb6b43-6eae-42bf-bb3c-20f45afc579f)

**Comment by fgdfgfthgr-fox** [comment]
I am not sure if I understand it right, but I think llama.cpp is already doing it?

**Comment by JohannesGaessler** [comment]
I have a Xeon system that I bought for 350€ used on ebay. This system has a Xeon E5-2683 v4 CPU as well as quad-channel 2133 MHz RAM. On this system using llama.cpp with CPU only I get 2.32 t/s for Mixtral FP16 (as reported by `llama-bench`). With the addition of a single P40 (24 GiB VRAM) I get 2.82 t/s. The limiting factor is the RAM bandwidth since the CPU is by far the slowest component and RAM bandwidth determines how quickly you can load the weights from RAM into the CPU (or how quickly you can load data via PCIe to VRAM).

For the scenario equivalent to `llama-bench` the paper reports 3 t/s with an "Intel Skylake (48 core, 2.60GHz)" CPU and a Quadro RTX 6000 or 3.5 t/s for an "Intel Cascade Lake (32 core, 2.20GHz)" and an L4. The RAM is **not** specified which is already very damning because it implies that they do not understand the bottleneck for CPU+GPU inference. The paper does not include a comparison to llama.cpp. In absolute terms the numbers reported in the paper are not impressive in any way because I think those are the speeds you should be getting on that hardware with CPU only. The authors are **not** demonstrating that their method overcomes the bottleneck imposed by RAM bandwidth. If the authors make a PR for their technique I will happily review it but as it is I definitely do not want to spend my time trying to implement this.
