### ISSUE TITLE
phi-2/LLMA2 gpu accerleration of pre-attention layer

### ISSUE THREAD

**Issue by pure-water** [ggerganov/llama.cpp#5499]
Regarding to the  typical model as LLMA2 and Phi-2, it appeas only the attention layers can be offloading to gpu via --ngl switch?

the position encoding layer and the embedding layer are hard fixed to CPU anyway?

**Comment by JohannesGaessler** [comment]
The position encoding layer should automatically be copied to the GPU if needed. IIRC with the embedding layer the issue was that the CPU needs to be able to access it in some cases so the data is just being stored in RAM universally. These are things that could still be optimized but I don't think the difference would be small.

**Comment by pure-water** [comment]
but the embedding layer calculation is happening @ the cpu side anyway?
