### ISSUE TITLE
On certain AMD CPU, AVX512 got enabled with `-march=native` flag, there's no way to disable usage of avx512 at the moment

### ISSUE THREAD

**Issue by wsxiaoys** [ggerganov/llama.cpp#5782]
Related discussion: https://github.com/TabbyML/tabby/issues/1570

Would it be appropriate to adding something like `-mno-avx512f` if `LLAMA_AVX512` is off?

**Comment by slaren** [comment]
Maybe I am misunderstanding something, but this seems to be working as intended. If you want to generate a binary that can be used for a different machine that the one you are compiling on, you should disable `LLAMA_NATIVE` to avoid passing `-march=native` to the compiler, and instead set the desired architecture flags such as `LLAMA_AVX2` manually.

**Comment by wsxiaoys** [comment]
Good point—I hadn't realized that LLAMA_NATIVE is enabled by default; I was under the impression that it was LLAMA_AVX2.

However, it might still surprise some users to find that AVX512 is enabled, even when they set `LLAMA_AVX512=off`.

**Comment by slaren** [comment]
The current behavior is not very consistent, with `LLAMA_NATIVE` we pass both `-march=native` and the rest of the architecture flags to the compiler. I think we should ignore all the other architecture flags if `LLAMA_NATIVE` is enabled. This is effectively what is done with MSVC, since `FindSIMD.cmake` will override the architecture flags depending on what it finds.
