### ISSUE TITLE
Server: possibility of customizable chat template?

### ISSUE THREAD

**Issue by ngxson** [ggerganov/llama.cpp#5922]
## Motivation

While we already have [support for known chat templates](https://github.com/ggerganov/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template), it sometimes not enough for users who want to:
- Use their own fine tuned model
- Or, use a model that does not have Jinja template

The problem is that other implementations of chat template out there are also quite messy, for example:
- Jinja tempate: as discussed in https://github.com/ggerganov/llama.cpp/issues/4216 , it's too complicated to add a such parser into the code base of llama.cpp
- The format of [ollama](https://ollama.com/library/zephyr:latest/blobs/a96be15318d6) requires a parser, and it's not very flexible for future usages
- [LM Studio format](https://github.com/bunnywaffle/AI-Persona/blob/04d1238fb276d45e0a76a48752b3339d069f7a40/LM%20Studio/ai.preset.json#L25) does not requires parser, but lack support for multi roles (we currently have `system` - `user` - `assistant`, but technically it's possible to have custom roles like `database`, `function`, `search-engine`,...)

## Possible implementation

My idea is to have a simple JSON format that take into account all roles:

```
{
  "system": {
    "prefix": "<|system|>\n",
    "postfix": "<|end|>\n"
  },
  "user": {
    "prefix": "<|user|>\n",
    "postfix": "<|end|>\n"
  },
  "assistant": {
    "prefix": "<|assistant|>\n",
    "postfix": "<|end|>\n"
  },
  "_stop": ["<|end|>"],
  "_generation": "<|assistant|>\n",
}
```

User can specify the custom template via `--chat-template-file ./my_template.json`

The cpp code will be as simple as:

```cpp
std::string apply_custom_template(json messages, json tmpl) {
  std::stringstream ss;
  for (auto & msg : messages) {
    json t = tmpl[msg["role"]];
    ss << t["prefix"] << msg["content"] << t["postfix"];
  }
  ss << tmpl["_generation"]; // add generation prompt
  return ss.str();
}
```

NOTE: This function does not take into account models that does not support system prompt for now, but this function can be added in the future, maybe toggle via an attribute inside json `"system_inside_user_message": true`

Ref:
- https://github.com/ggerganov/llama.cpp/issues/5447
- https://github.com/ggerganov/llama.cpp/issues/5921
- https://github.com/ggerganov/llama.cpp/issues/5822
- https://github.com/ggerganov/llama.cpp/issues/5974

**Comment by ggerganov** [comment]
Users that want to support a certain template should open a PR and implement it in the framework that we already have

**Comment by teleprint-me** [comment]
Yeah, this is why I said templates should be the responsibility of the user.

It's why I always use the completions endpoint and avoid any chat template enforcement. The problem is simple to understand once you understand how a tokenizer is created and trained. ANY token can be used. ANY TOKEN. This ambiguity is problematic for requiring even a loose set of rules. 

This problem will exist even if the industry agrees upon a standard. ChatML is nice, but it's only a single use case and doesn't solve the wider issue at hand. This also makes completions more valuable because they're the most flexible. Completions also set the foundation or stage for chat fine-tuning. It sucks that OpenAI took it down, but it's what I always use when I use llama.cpp. 

Completions are literally the only reason I use llama.cpp. There's so much more flexibility that way. Just put the responsibility on the user, end of discussion. This isn't a conclusion I came to lightly. It took time, research, and experimentation to figure this out. This is why I backed and proposed this idea. 

This is the most viable solution for the interim, and even then, this solution fails miserably with FIM and other templates. It's not that I think this is an impossible problem, but it is the type of problem that will create an entirely different set of problems that compound one another and eventually becomes a bottleneck in the best case scenario.

I really do understand the temptation here, but it's best avoided.

**Comment by ngxson** [comment]
> I really do understand the temptation here, but it's best avoided.

Thanks for your input. For clarification, I'm **not** saying that my proposal solves all the issues we have with chat templates in general. If I was that confident, I could have just made a PR instead.

I also not assuming that supporting custom chat template is a good idea or not. I'm still learning here. I understand your point. It's a valid reason **not** to have this feature and I appreciate that.

However, I will still keep this issue open to collect some feedback, maybe will be helpful if we change the decision in the future.

**Comment by teleprint-me** [comment]
I think this is the middle of the road solution which is good. 

I just keep reiterating it because the tokens are dictated by the tokenizer and the settings used to train the tokenizer. 

All of the tokens for the model are (usually, but unfortunately not always) in there, e.g. `tokenizer.model` or `tokenizer.json`. It was really interesting and fun learning how this worked.

So, to clarify, I support your proposal. Once the tokenizer is understood, managing the templates for the model becomes more intuitive.

A really great way to get a feel for it is with completions.

**Comment by ngxson** [comment]
I came across https://github.com/ollama/ollama/issues/1977 and feeling like we're in the middle of a "war of template". You're right @teleprint-me , there's the temptation, but better to avoid it at least in this stage.

**Comment by teleprint-me** [comment]
I'd love to have it automated, it would be great. I forgot where I stated it, but I remember reiterating that this is similar to _"Hilbert's paradox of the Grand Hotel"_ which _"is a thought experiment which illustrates a counterintuitive property of infinite sets"_.

This issue arises because of the desire to support many models with a variety of templates. Model developers can choose to set up the template however they'd like and so can fine-tuners.

The moment you begin baking in special tokens, chat templates, and more, is the moment you've bound yourself to an uncanny solution that exponentially becomes more difficult to manage over time. You'll always need to accommodate another "guest".

The simplest solution is to create an API or Framework that developers can plugin to. @ggerganov actually suggested this same solution awhile ago. I recommended this solution multiple times. I've been advocating to place the chat template as the responsibility of the user. My rationale is to keep the code and API simple and digestible.

I'm confident that there is a way to find a middle ground, but we'll need to work towards that middle ground. I think your idea is actually sound and the reason is because it's simple and flexible. The motto around here seems to be to not over engineer, but supporting chat templates will require much more than over engineering and this doesn't include the maintenance that will ensue as a result. It has technical debt written all over it.

I think using the prefix and postfix for prompts is probably the best we can do until templates become solidified. It's still early and we're just getting started. It's better to observe and learn as we progress. Once a pattern emerges, we can use that as an anchor.

**Comment by teleprint-me** [comment]
As an aside, I'd love to build a custom tokenizer for llama.cpp. I think it would be great. We could use it for training and fine-tuning. I haven't looked at the backend lately, but back-propagation would obviously help for updating the weights. What would be really neat it training and fine-tuning quants. Now that would be really cool :)

**Comment by kaizau** [comment]
Re: https://github.com/ggerganov/llama.cpp/issues/6726#issuecomment-2065729990

> @ngxson The main problem is that even with this level of flexibility, some templates can't be supported without doing some code logic (for example, llama 2 template [INST] with <<SYS>> system message).

My hunch is that code logic _in templates_ can still be avoided, if the configuration provides enough flexibility. For example, providing an alternate template based on message index:

```json
{
  "system": {
    "prefix": "<s>[INST] <<SYS>>\n",
    "postfix": "<<SYS>>\n\n"
  },
  "user_1": {
    "prefix": "",
    "postfix": " [/INST] "
  },
  "user": {
    "prefix": "<s>[INST] ",
    "postfix": " [/INST] "
  },
  "assistant": {
    "prefix": "",
    "postfix": " </s>"
  }
}
```
 
This could be implemented generally, or even just as a 1-off workaround for first user message.

**Comment by kaizau** [comment]
Re: https://github.com/ggerganov/llama.cpp/issues/6726#issuecomment-2065440493

> @bullno1 Sounds cool and i'd say take it further, why even template or search&replace within a role? Just change it to "prefix" and "suffix":

Might just be me, but I slightly prefer the aesthetic / concise legibility of seeing the entire message in context:

```json
{
  "system": "<s>[INST] <<SYS>>\n{{content}}<<SYS>>\n\n",
  "user_1": "{{content}} [/INST] ",
  "user": "<s>[INST] {{content}} [/INST] ",
  "assistant": "{{content}} </s>"
}
```

Not a big deal, because both are more legible than a string of escaped Jinja.

As for injection risk, this wouldn't need to execute code — just do a string replacement. Maybe I'm overlooking something here?

**Comment by kaizau** [comment]
@teleprint-me Seems like chat templates brushes up against a macro question around the ideal scope of llama.cpp and this server "example" in general.

But whether the `chat` endpoint is here or elsewhere, configurable chat templates is a very natural extension. Anything else is an incomplete solution which forces clients (or users) to implement their own workarounds on `completions` if they want to support the vast and growing number of templates.

**Comment by ngxson** [comment]
> Might just be me, but I slightly prefer the aesthetic / concise legibility of seeing the entire message in context

@kaizau I personally prefer having postfix/prefix explicitly, since it makes the cpp code more readable. I think the format the you proposed is more suitable for higher level programming languages, since the parser can be just one or two line of codes.

**Comment by teleprint-me** [comment]
@kaizau I agree with your assessment.

**Comment by bullno1** [comment]
> Re: [#6726 (comment)](https://github.com/ggerganov/llama.cpp/issues/6726#issuecomment-2065440493)
> 
> > @bullno1 Sounds cool and i'd say take it further, why even template or search&replace within a role? Just change it to "prefix" and "suffix":
> 
> Might just be me, but I slightly prefer the aesthetic / concise legibility of seeing the entire message in context:
> 
> ```json
> {
>   "system": "<s>[INST] <<SYS>>\n{{content}}<<SYS>>\n\n",
>   "user_1": "{{content}} [/INST] ",
>   "user": "<s>[INST] {{content}} [/INST] ",
>   "assistant": "{{content}} </s>"
> }
> ```
> 
> Not a big deal, because both are more legible than a string of escaped Jinja.
> 
> As for injection risk, this wouldn't need to execute code — just do a string replacement. Maybe I'm overlooking something here?

The injection risk I was talking about is more about user input containing special tokens like: `<start_of_turn>`, `<eot_id>`...
When we tokenize the markers separately, user message can be tokenized with `parse_special=false` and those special tags will appear as literal strings instead of special token.

**Comment by hanishkvc** [comment]
Please do have a look at the code in the below PR. Around the time when llama3 came out, I had a need to look at llama.cpp and inturn I worked on below, to try and see if one can have a generic flow which is driven by a config file to try and accomodate different modes/chat-handshake-template-standards in a generic and flexible way. The idea being that if a new template standard is added during finetuning of a model or if a new model or standard comes out, but which follows a sane convention matching the commonality that I have noticed across many models/standards, then the generic code flow itself can be used, by just updating the config file, without having to add a custom template block.

This inturn can be used by example/main, example/server, as well as other users of llama.cpp library. Currently main has been patched to use this config file based flow inturn piggy backing on its existing interactive mode and its in-prefix, in-suffix, antiprompt to a great extent.

https://github.com/ggerganov/llama.cpp/pull/6834

Based on some minimal testing at my end, I seem to be able to handle the nitty gritties of around 8(+1) model using this generic code + config file based flow.

Currently json format is used for the config file, but if needed can be switched to a simpler text based config file, to avoid users of the llama.cpp library from needing to depend on json library. 

The generic code flow uses a concept similar to what this PR is also thinking ie a generic code flow driven by a config file. 

Also the generic flow additionally takes care of

* the conditionality that is seen across few different models wrt tagging of the system-message + 1st user message flow by using related generic flags and also how system-suffix, system-end, user-begin and user-prefix are setup.

* the need to differentiate between role-begin, role-prefix, role-suffix and role-end tokens wrt each of the role. And inturn the variation in their insertion or not across different models, but done in a simple and generic way, by just allowing for each of these to be set to some specific string or left as empty string wrt each of the role, as needed by that specific model.

You can look at the examples/chaton_meta.json which has entries for the 8(+1) models/standard, which I have tested with my patch.

**Comment by JoakimCh** [comment]
> [teleprint-me:](https://github.com/ggerganov/llama.cpp/issues/5922#issuecomment-1987341505) Yeah, this is why I said templates should be the responsibility of the user.

Agreed, which I asked about here [issues/6982](https://github.com/ggerganov/llama.cpp/issues/6982).

As ngxson pointed out "the code is so simple", we can write it ourselves in whatever frontend we use.
