### ISSUE TITLE
GGUF writer reverses array (tensor) dimensions

### ISSUE THREAD

**Issue by certik** [ggerganov/llama.cpp#6040]
The GGUF writer reverses the array (tensor) dimensions when saving here:

https://github.com/ggerganov/llama.cpp/blob/b3d978600f07f22e94f2e797f18a8b5f6df23c89/gguf-py/gguf/gguf_writer.py#L208

And it does not reverse it when reading it here:

https://github.com/ggerganov/llama.cpp/blob/b3d978600f07f22e94f2e797f18a8b5f6df23c89/gguf-py/gguf/gguf_reader.py#L193

As a result, the shape gets reversed. Here is a minimal example to reproduce this issue:
```python
import numpy as np
import gguf
A = np.zeros((4, 10), dtype=np.float32)
A[:4,:4] = np.eye(4)
A[1,0] = 5.
print(A)
print(A.shape)
print(A.dtype)
print()


gguf_writer = gguf.GGUFWriter("a.gguf", "test")
gguf_writer.add_tensor("A", A)
gguf_writer.write_header_to_file()
gguf_writer.write_kv_data_to_file()
gguf_writer.write_tensors_to_file()
gguf_writer.close()

gguf_reader = gguf.GGUFReader("a.gguf")
print(gguf_reader.tensors[0])
print()
print(gguf_reader.tensors[0].data)
print(gguf_reader.tensors[0].shape)
print()
print("Incorrect:")
B = np.reshape(gguf_reader.tensors[0].data, gguf_reader.tensors[0].shape)
print(B)
print(B.shape)
print(B.dtype)
print()

print("Correct:")
C = np.reshape(gguf_reader.tensors[0].data, np.flip(gguf_reader.tensors[0].shape))
print(C)
print(C.shape)
print(C.dtype)
```
This prints:
```console
$ python a.py
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
(4, 10)
float32

gguf: This GGUF file is for Little Endian only
ReaderTensor(name='A', tensor_type=<GGMLQuantizationType.F32: 0>, shape=memmap([10,  4], dtype=uint64), n_elements=40, n_bytes=160.0, data_offset=128, data=memmap([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32), field=ReaderField(offset=68, name='A', parts=[memmap([1], dtype=uint64), memmap([65], dtype=uint8), memmap([2], dtype=uint32), memmap([10,  4], dtype=uint64), memmap([0], dtype=uint32), memmap([0], dtype=uint64)], data=[1, 3, 4, 5], types=[]))

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[10  4]

Incorrect:
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 5. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
(10, 4)
float32

Correct:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
(4, 10)
float32
```
As you can see, `A` has shape `(4, 10)`, in the `a.gguf` file it is saved as `(10, 4)` and then it is read as `(10, 4)` and the array `B` created using `np.reshape` becomes incorrect. One must reverse the dimensions using `np.flip` to get the correct array `C` (equal to `A`).

Also `gguf-dump` prints the shape reversed:
```console
$ gguf-dump a.gguf 
* Loading: a.gguf
* File is LITTLE endian, script is running on a LITTLE endian host.

* Dumping 4 key/value pair(s)
      1: UINT32     |        1 | GGUF.version = 3
      2: UINT64     |        1 | GGUF.tensor_count = 1
      3: UINT64     |        1 | GGUF.kv_count = 1
      4: STRING     |        1 | general.architecture = 'test'

* Dumping 1 tensor(s)
      1:         40 |    10,     4,     1,     1 | F32     | A
```

If this is intended behavior, it would be good to document it at https://github.com/ggerganov/ggml/blob/43a6d4af1971ee2912ff7bc2404011ff327b6a60/docs/gguf.md. I am happy to send a PR with documentation, once it is clarified what the behavior should be (ideally with a motivation behind it).

**Comment by compilade** [comment]
> if this behavior is intended, it should be documented.

It looks intended.

The README of `llama.cpp` mentions this in the [Coding guidelines](https://github.com/ggerganov/llama.cpp#coding-guidelines) section near the end:

> Tensors store data in row-major order. We refer to dimension 0 as columns, 1 as rows, 2 as matrices

(I think it's more intuitive to think of dimension 0 being "number of elements per row" instead of "number of columns per row", but it's conceptually the same thing. I think this was the intention behind naming the `ne` field of the `ggml_tensor` struct ("ne" likely stands for "number of elements" per dimension))

This is also stated in `ggml.h`:

https://github.com/ggerganov/llama.cpp/blob/928e0b7013c862cf10701957b3d654aa70f11bd8/ggml.h#L125

Numpy also uses row-major order for storing data, BUT the notation for dimensions is reversed, with the last dimension being the columns (aka the number of elements in a row).

You're right that the dimension order doesn't seem explicitly written in the GGUF spec. I'm sure a PR clarifying this would be welcome.

> I am happy to send a PR with documentation, once it is clarified what the behavior should be (ideally with a motivation behind it).

(Speculating here, but) I guess the motivation is probably because in C, it's easier to index the number of elements per dimensions from 0 instead of from "the last dimension", which in Python can be done by indexing with negative numbers.

**Comment by certik** [comment]
@compilade thanks for the feedback. To summarize:

* GGUF and ggml internally both use row-major order
* GGUF and ggml internally save dimension in the order: columns, rows, matrices, ..., that is, the *first* dimension is the contiguous one
* In C you could index an array with compile time dimensions as A[i][j], but here the *last* dimension (`j`) is the contiguous one, opposite from GGUF and ggml.
* NumPy also follows the C convention and the *last* dimension is the contiguous one, opposite from GGUF and ggml
* In mathematics (linear algebra), a matrix with dimensions (4, 10) means the last dimension (10) is the number of elements in the row (=number of columns), so in row-major order it means the *last* dimension is contiguous, as in NumPy and C, but opposite to GGUF and ggml

Let me know if you agree with this summary.

If so, then the answer is: GGML uses row-major order and stores dimensions as contiguous first. GGUF follows the same convention. This is opposite to the C and NumPy convention, where both also use row-major, but the last dimension is contiguous. The motivation why GGML chose to store the first dimension as contiguous is likely so that you can treat a matrix of the shape `(n, m)` as `[m, n, 1, 1]`, i.e., append 1 for the (unused) 3rd and 4th dimension, and the indexing algorithm can always treat it as a 4D array.

When saving from NumPy to GGUF, the order of dimensions must be reversed. When loading from GGUF to NumPy, the order of dimensions must be reversed also.

**Comment by compilade** [comment]
> GGUF and ggml internally save dimension in the order: columns, rows, matrices, ..., that is, the first dimension is the contiguous one

Note that tensors are not necessarily contiguous in ggml (but this doesn't apply to serialized tensors in GGUF, which are all contiguous). In ggml, there are strides for each dimensions (the `nb` field of `ggml_tensor`), which means the first dimension can be made non-contiguous (like when transposing and/or permuting), and dimensions can even be made to partially overlap with each other (though this is not usually done[^1]).

Turns out explaining this in-depth is more confusing. For example, when using `ggml_mul_mat`, the resulting tensor as well as the second argument is transposed, they can be considered column-major even if all the involved tensors are row-major:

[^1]: I've explored self-overlapping views in one of the initial implementations of Mamba in `llama.cpp`, where I've set `nb[2]` to the element size of the tensor. So they are possible.
    https://github.com/compilade/llama.cpp/blob/de50c549c4da0c60d3582f82660d3c534b4811ac/llama.cpp#L8080-L8083

![diagram of `ggml_mul_mat` equivalence](https://raw.githubusercontent.com/ggerganov/llama.cpp/b7368332e24c5b2c8038bf8267f43632783fcc35/media/matmul.png)

(this image is from the bottom of the README and was added in https://github.com/ggerganov/llama.cpp/pull/6881 (there's a good explanation in the comments over there))

But for tensors for which [`ggml_is_contiguous`](https://github.com/ggerganov/llama.cpp/blob/b7368332e24c5b2c8038bf8267f43632783fcc35/ggml.c#L2565-L2573) is true (e.g. all of the tensors stored in a GGUF file), your explanation holds.
