### ISSUE TITLE
How to Modify Hugging Face's Language Models?

### ISSUE THREAD

**Issue by kbuwel** [ggerganov/llama.cpp#6057]
I am Korean and a beginner. I downloaded several language models from Hugging Face and ran them on koboldcpp. They did output in Korean. However, there was a problem. The awkwardness characteristic of translation tools occurred. I requested the txt script that the language model developer used from them, but there was no response. I understand how to create a tokenizer. But I'm not sure how to write the script. The language models I downloaded are specialized for role-playing and scenario writing. How should I write the script to solve the problem I'm facing?

**Comment by ngxson** [comment]
I'm not quite understanding your question, maybe you can use a better tool like [deepl](https://www.deepl.com/translator) to translate your question?

Firstly, these models are not magic. It has to be trained - just like we human need to be trained at school.

The quality of output text depends on training data. I think you're confusing between training data and tokenizer, they are not the same thing.

**Comment by kbuwel** [comment]
The translation of my question was done by ms copilot. 
What I want to ask is that I would like to retrain the model created by training with llama.cpp in 
Korean, my native language. 
Korean is output, but it is awkward, like a translator. 
It's like you don't understand my question. 
What I want to do is solve this problem.

**Comment by ngxson** [comment]
> Korean is output, but it is awkward, like a translator.

Maybe one of these 2 reasons:
- The data is not good enough so the model cannot learn your language
- Training time is not enough

Typically, to train a model to understand another language, you need to train it on multiple GPUs and for days, not just hours. It's a very hard process that I'm not recommend to do if you're not very familiar with machine learning.

Instead, you can take a pre-trained korean model and do LORA fine tuning instead of training it: https://huggingface.co/models?search=korean+llama

But korean models seems rare, I don't know why, maybe because not many laboratories in your country interested in machine learning.

In Southeast Asia countries there're many models like Qwen and SeaLLM/Sailor that speak very good chinese, vietnamese, laos, thai,...

**Comment by kbuwel** [comment]
How do I train Korean? 
I have two 12GB GPUs. 
I downloaded the original model-00001-of-00003.safetensors file and the configuration file tokenizer 
file from huggingface. 
What files do I need to add Korean data? 
I have a lot of time.

**Comment by ngxson** [comment]
1. Are you from a laboratory? I'm not machine learning expert. If you have that much GPU power, please contact an expert in your country to help you.
2. llama.cpp cannot be used to train models from huggingface, please use python `transformers` library instead.
3. Data looks like this: https://huggingface.co/datasets/bkai-foundation-models/BKAINewsCorpus ; The best way is to crawl data from newspaper for example. This is used to train the base model that understand the language (but not behaviors).
4. After training base model that can understand language, you can fine tune it to follow instruction.

**Comment by ngxson** [comment]
If you use a pre-train korean base model (for example from https://huggingface.co/models?search=korean+llama ), then the next step is to translate a dataset from english to korean. Here is example of a role play dataset: https://huggingface.co/datasets/hieunguyenminh/roleplay

To translate, you can use 3rd party API like google translate or bing translate. The quality will not be good. That's why you should hire someone in your country who does the translation (which cost money)

**Comment by iamlemec** [comment]
Have you tried the Korean adapted models here yet: https://huggingface.co/beomi? I can't evaluate the output quality well, but these seem to be pretty widely used. I just tried `OPEN-SOLAR-KO-10.7B` and it converts and runs with llama.cpp.
