### ISSUE TITLE
Finetune gguf model on cpu

### ISSUE THREAD

**Issue by Kandaraa** [ggerganov/llama.cpp#6244]
hello 

I'm trying to finetune TheBloke/Mistral-7B-OpenOrca-oasst_top1_2023-08-25-v2-GGUF using a  json dataset of 7gb following this template: " instrunction: ............. input: ............. response:"

I have an ovh server with 15 cpu cores and 64 gb of ram

running this command :
`./finetune --model-base models/mistral-7b-openorca-oasst_top1_2023-08-25-v2.Q5_0.gguf --train-data datasets/finetune_data.json  --threads 9 --sample-start "{"instruction":"`

the ram get filled after a while and the console showed killed

how much ram is needed to procced the finetuning ? 
how much time estimated to ends up the finetuning? 
what is the parameter to precise the number of iteration the finetuning will done?

thanks

**Comment by Tachyon5** [comment]
Are you sure you training data is formatted correctly?

**Comment by Kandaraa** [comment]
My data is a json file around 7gb. A list of element each element is composed of: instruction, input and response as follow:

`[
     {
       "Instruction": "......",
       "Input": "......",
        "Response": "......",
      },
.
.
.
]`

And i mentionned in the command that the start sample is (--sample-start "{"instruction":")

Is there something wrong?

**Comment by ngxson** [comment]
llama.cpp `finetune` doesn't take into account JSON data, so it may not suitable in your case. Please use third party tool, for example https://github.com/OpenAccess-AI-Collective/axolotl

**Comment by Kandaraa** [comment]
Thanks for reply it support cpu and directly train on gguf please?

**Comment by teleprint-me** [comment]
You need to convert the JSON to a Plaintext format. The most complicated part of it would be consistent formatting for the plaintext file.

A good way to experiment with it is to experiment with `train-text-from-scratch`. `finetune` works in a similar way. Definitely worth experimenting with micro models because larger models take awhile on CPU. CPU's aren't designed with this in mind and are, unfortunately, way slower.

I actually ended up prototyping a script for converting JSON formatted conversational data to plaintext [here](https://github.com/teleprint-me/text-extraction/blob/main/text_extraction/cli/json.py). Shouldn't be too bad if you're comfortable with Python.

Regardless, once you're confident in the process, you can scale up and apply larger datasets and train/finetune larger models.

**Comment by Tachyon5** [comment]
the training data should just be a txt file with text like this:

"
<s>. //begin string token
<|im_start|> User:  Please answer this question:  Who is the greatest NBA player in history <|im_end|>
<|im_start|> Assistant: The greatest player in NBA history is Michael Jordan.
</s> //end of string token
<s>   //so and so forth
<|im_start|>   
....
"

each row has has a begining of string token <s> and ends in </s>. you need to specify this in the params when fine tuning. take a look here: https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GGUF
