### ISSUE TITLE
Add some models in ggml-models HF repo

### ISSUE THREAD

**Issue by phymbert** [ggerganov/llama.cpp#6292]
### Motivation

In the context of:

- #6233

Need to add some models in the [GGML HF Repo](https://huggingface.co/ggml-org/models/tree/main):

- mixtral8x7B Q4 Q8 F16 in split format
- bert-bge-large F16
- llama7B 13B split Q4 F16

**Comment by phymbert** [comment]
@ggerganov Georgi Hi, not urgent but if could you please assist on this ? thanks

**Comment by phymbert** [comment]
I will do it when required

**Comment by phymbert** [comment]
@ggerganov Georgi, I have added `phi-2` [f16](https://huggingface.co/ggml-org/models/tree/main/phi-2) but taking into account @julien-c recommandation to split the repo per model, tell me how do you want to proceeed taking into accounts files are used in `server` and `bench` CI workflows.

**Comment by ggerganov** [comment]
I was planning to migrate the models into separate repos over the next days. Meanwhile, the current `models` repo will stay as it is so that the CI keeps working. When the models have been migrated, we will update the CI and make the `models` repo private. When all CI is green, then we will delete the `models` repo

In case you want to help with that, feel free to start moving the models. Just create a repo with the name of the model as (e.h. `ggml-org/phi-2`) and move the files from `models` repo into the root dir of the new one
