### ISSUE TITLE
Unable to enter Chinese prompt

### ISSUE THREAD

**Issue by LainNya** [ggerganov/llama.cpp#646]
Hi!My use is compiled under Windows main.exe, when I type Chinese Prompt, I found that the model seems to be unable to understand, under debugging found that std::getline(std::cin,line) get is empty lines, then I tried Japanese, are the same result.
(Since I am a native Chinese speaker, this question was translated by DeepL)
![image](https://user-images.githubusercontent.com/18028414/229043234-a47c0569-07e1-4731-85d9-121f9774fdc9.png)

**Comment by LainNya** [comment]
> have you tried this https://github.com/ymcui/Chinese-LLaMA-Alpaca?

Yes, this is the model I use

**Comment by boholder** [comment]
Let me provide more information about this issue. Hope this helps to solve the problem.

@LainNya  [found out](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/11#issuecomment-1492125443) that:
in the `CMD` and `Powershell` (also `Cygwin64` Terminal as I tested) terminals of the **Windows environment**, the Chinese entered could not be fetched by `llama.cpp`. But in other terminals like `git-bash` and `linux subsystem for windows` (no it's just linux env) it works.

It [seems](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/20#issuecomment-1491906506) that the `std::getline` doesn't support UTF-8 character set.

This is the detailed cause and solution I found, but I can't tell since I'm not familiar with C++:

https://cboard.cprogramming.com/cplusplus-programming/145590-non-english-characters-cout-post1086757.html#post1086757

I'm not sure if this should be chalked up to a Windows terminal compatibility issue with C++.

Anyway, use `git-bash` and `linux subsystem for windows` as the workaround for now.

**Comment by tomsnunes** [comment]
This problem for unicode characters had been fixed here for me in the following PR #420 , but I confirm that it is currently not possible to insert or display utf-8 characters at moment.

**Comment by prusnak** [comment]
https://github.com/ggerganov/llama.cpp/pull/840 has been merged - try pulling the latest master and please test whether this fixed your issue

**Comment by boholder** [comment]
LGTM after replace the latest binaries in https://github.com/ggerganov/llama.cpp/releases/tag/master-aaf3b23
![screen shot that will expire after one month](https://i.ibb.co/rFsWdDy/20230409.jpg)
Modifying the prompt is also possible, nice job! 👍
