### ISSUE TITLE
Can I enable cuda and cpu blas at the same time?

### ISSUE THREAD

**Issue by EternalSaga** [ggerganov/llama.cpp#6599]
I tried to build llama.cpp on windows with vcpkg and cmake. The OpenBLAS is installed by vcpkg. The cmake building options is like this:
```
cmake .. -DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS -DLLAMA_NATIVE=ON -DLLAMA_CUDA=ON -DLLAMA_CUDA_F16=ON -DBUILD_SHARED_LIBS=ON  -DCMAKE_TOOLCHAIN_FILE=E:/program/vcpkg/scripts/buildsystems/vcpkg.cmake 
```
The compiling is successful, and I can load layers to GPU. However, it seems that the performance is worse than only use CUDA. I noticed that there is almost no workload on GPU.

**Comment by JohannesGaessler** [comment]
Both BLAS libraries and CUDA only make sense to use for matrix multiplications with large batch sizes. So the only way to combine the two and get better performance would be to run the CPU and the GPU in parallel for some matrix multiplication. However, every time that I tried this the performance was worse than just running everything on the GPU due to additional synchronization overhead. Therefore llama.cpp runs matrix multiplications exclusively on either the CPU or the GPU and there is no benefit to compiling with both GPU support and a CPU BLAS library.
