### ISSUE TITLE
Time Series Forecasting LLM Support

### ISSUE THREAD

**Issue by spectral-sequence** [ggerganov/llama.cpp#6791]
Chronos appears to be a great open source time series forecasting model. 
Is it possible to integrate this model into llama.cpp?

https://github.com/amazon-science/chronos-forecasting

**Comment by ngxson** [comment]
This model uses T5 architecture so we firstly need to support T5, see this issue: https://github.com/ggerganov/llama.cpp/issues/5763

Beside that, this model doesn't have a tokenizer (since time-series signal is converted directly into tokens), so convert script may fail. We can simply add a dummy tokenizer before converting to solve that problem. An example of the HF model can be found here: https://huggingface.co/amazon/chronos-t5-small/tree/main
