### ISSUE TITLE
Why Ollama is using VRAM Only insted of VRAM + RAM?

### ISSUE THREAD

**Issue by Viperz88** [ggerganov/llama.cpp#6876]
![image](https://github.com/ggerganov/llama.cpp/assets/136520478/4df02421-b44f-4e47-bb04-33df160f4e83)

I'm running the latest version of Ollama with Llama3:70b on Windows. It's consuming most of my VRAM, but I have 63.9 GB of available RAM that could boost the speed further, yet it's not being taken into account. Is there a way to do so?

**Comment by coder543** [comment]
This isn't the right forum to ask about ollama, this is the llama.cpp issue tracker.

But, if it were using your regular RAM there, then that would mean that the GPU code was swapping to system RAM, which would mean every computation requires the memory to go across the PCIe bus, which would be extremely slow. When you don't have enough VRAM, there is a separate task running on the CPU that will do computations for certain layers of the LLM there, which will not show up on the GPU RAM in task manager. This is still going to be slow, since your CPU does not have much RAM bandwidth, but it will be faster than shuffling the memory back and forth to the GPU.

**Comment by olinorwell** [comment]
This isn't the right forum for this question but I'll answer given that the underlying answer is correct for llama.cpp too.

Ollama by default pulls a Q4 GGUF version of Llama3-70B, which is about 40GB in size.

Llama.cpp 'under the hood' is using your VRAM (24GB) and 24.5GB of RAM which equates to 48.5GB, which is the model (40GB) plus the context etc (8GB). These numbers are exactly what you would expect to see. So there is no bug here.

You could fit a larger version of Llama3-70B if you wanted, like you say you have spare RAM. To do this in Ollama you need to specify a different 'tag' when pulling/running the model.
