### ISSUE TITLE
server: phi-3 end token not handled?

### ISSUE THREAD

**Issue by infozzdatalabs** [ggerganov/llama.cpp#6903]
Phi-3 4k model include in all responses the end token "<|end|>"

Im using: https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf and llama.cpp for docker cuda server in the latest version.

Thanks in advance.

**Comment by x4080** [comment]
i can confirm that, llama 3 template also, it seems there's change in llama cpp and utils.hpp not including the stop token

**Comment by thecivilizedgamer** [comment]
Seeing the same issue, with both Phi 3 and Llama 3, using server with the latest changes. I had to roll back to an older commit to get Llama 3 working properly again

**Comment by thecivilizedgamer** [comment]
> i can confirm that, llama 3 template also, it seems there's change in llama cpp and utils.hpp not including the stop token

Did you try Llama 3 with the latest commit? I was just made aware that it should have been fixed by this PR https://github.com/ggerganov/llama.cpp/pull/6860

I pulled the latest changes and tried again just now, and Llama 3 is working again for me. But Phi 3 still has issues with the stop token for server, at least for chat completions:

`Hello there! It's great to interact with you. How can I assist you today?<|end|>`

**Comment by teleprint-me** [comment]
Ive seen this with evry model Ive used so far. Will have to test. Been busy working, but Ive been using the stop option to handle stop tokens and it goes away. e.g. mistral `</s>`, llama3 `<|eot_id|>`, phi3 `<|end|>`, etc.

**Comment by x4080** [comment]
My temporary solution is re-adding :
```
    llama_params["stop"].push_back("<|eot_id|>"); // llama 3
    llama_params["stop"].push_back("<|end|>"); // phi 3

```
into util.hpp

**Comment by phymbert** [comment]
You can pass the stop tokens in the payload:

https://github.com/ggerganov/llama.cpp/pull/6916/files

**Comment by teleprint-me** [comment]
It's in the API for both server and main examples.

> stop: Specify a JSON array of stopping strings. These words will not be included in the completion, so make sure to add them to the prompt for the next iteration. Default: []

[REST API Docs](https://github.com/ggerganov/llama.cpp/tree/master/examples/server#api-endpoints)

**Comment by Any-Winter-4079** [comment]
I am running into this issue but with ./main:

`./main -m models/Phi-3-mini-4k-instruct-gguf/Phi-3-mini-4k-instruct-q4.gguf -n 1024 -e -c 4096 -ngl -1 -r "['<|end|>']" -p '1-2='`

>  1-2=0<|end|><|assistant|> The equation 1-2=0 is incorrect. The correct result of 1-2 is -1. Therefore, the equation 1-2 ≠ 0 is true.<|end|><|assistant|> Yes, that is correct. The equation 1-2 does not equal 0; instead, it equals -1. The equation 1-2 = 0 is false.<|end|><|assistant|> Absolutely, you've got it right. The expression 1-2 indeed equals -1, not 0. So, the equation 1-2 = 0 is not true.<|end|><|endoftext|> [end of text]

Commit: https://github.com/ggerganov/llama.cpp/commit/8a56075b07a8b571bf95a912ffdce4c928c2b414

On commit https://github.com/ggerganov/llama.cpp/commit/928e0b7013c862cf10701957b3d654aa70f11bd8 I get gibberish which is probably related to https://github.com/ggerganov/llama.cpp/issues/6944

**Comment by infozzdatalabs** [comment]
> It's in the API for both server and main examples.
> 
> > stop: Specify a JSON array of stopping strings. These words will not be included in the completion, so make sure to add them to the prompt for the next iteration. Default: []
> 
> [REST API Docs](https://github.com/ggerganov/llama.cpp/tree/master/examples/server#api-endpoints)

Yes, I noticed that as well. The stop parameter you mentioned is available for the "/completion" endpoint. However, when using the OpenAI API, the endpoint is "/v1/chat/completions".

**Comment by victorlwchen** [comment]
I also encountered this issue, I found that <|end|> token was processed as a User_Defined Type instead of a Control Type, causing it to be output as a normal token during the token_id to text conversion.

Referring to [https://github.com/vllm-project/vllm/pull/4182](https://github.com/vllm-project/vllm/pull/4182) , they would additionally handle the generation_config.json. Apparently, for phi-3 model, <|end|> should be considered as Control type token.

However, the handling of the phi-3 model by convert-hf-to-gguf.py would categorize the token ids inside added_tokens.json as USER_DEFINED type.

**Comment by maziyarpanahi** [comment]
Out of curiosity, can `llama_params["stop"]` be saved inside GGUF metadata? So I can edit GGUF models before shipping them and add the proper stops instead of asking users to do it?

**Comment by mosujiba** [comment]
When I run Phi-3 with `llama-cli -cnv` and the default chat template #8068, it still spits out the end token in all responses.
