### ISSUE TITLE
About dialogue training mode

### ISSUE THREAD

**Issue by andyyumiao** [ggerganov/llama.cpp#6993]
For the finetune, the default is use text dataset（e.g. shakespeare.txt）,  does it support dialogue training mode？

**Comment by arnfaldur** [comment]
It does not support a specific mode for dialogue training such a thing does not exist to my knowledge. Instruction tuning and RLHF could loosely be described as dialogue training.

Consider if your issue is an issue that is relevant to the development llama.cpp. 

If it is not. I recommend reading up on database creation, and instruction tuning, [here is a technical paper](https://arxiv.org/pdf/2308.10792). There are also plenty of resources and guides on youtube and around the internet.

If it really is an issue relevant to the development of llama.cpp, please explain it in much greater detail. What do you want to achieve? What have you done so far to achieve it?

**Comment by andyyumiao** [comment]
> It does not support a specific mode for dialogue training such a thing does not exist to my knowledge. Instruction tuning and RLHF could loosely be described as dialogue training.
> 
> Consider if your issue is an issue that is relevant to the development llama.cpp.
> 
> If it is not. I recommend reading up on database creation, and instruction tuning, [here is a technical paper](https://arxiv.org/pdf/2308.10792). There are also plenty of resources and guides on youtube and around the internet.
> 
> If it really is an issue relevant to the development of llama.cpp, please explain it in much greater detail. What do you want to achieve? What have you done so far to achieve it?

Yes, actually I mean the instruction tuning. Is there a demo for it on llama.cpp?

**Comment by arnfaldur** [comment]
Not to my knowledge or expectations. This is not the place to ask about this either. I recommend doing some research about what you're trying to do, elsewhere. There are plenty of good introductory articles, and videos on youtube, if you prefer.
