### ISSUE TITLE
Is possible to add AQLM to llamacpp? 

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#7105]
https://github.com/Vahe1994/AQLM
https://arxiv.org/pdf/2401.06118

**Comment by TheTerrasque** [comment]
This [have been discussed before](https://github.com/ggerganov/llama.cpp/discussions/5063), but might be worth a new look. 

From one of the devs: ["We have greatly improved the quality since Feb 6 as well."](https://www.reddit.com/r/LocalLLaMA/comments/1clinlb/bringing_2bit_llms_to_production_new_aqlm_models/l2ukxnt/?context=3)

**Comment by tomasmcm** [comment]
Meta-Llama-3.1-70B-Instruct quantised to only 21.9GB 😍 
https://huggingface.co/ISTA-DASLab/Meta-Llama-3.1-70B-Instruct-AQLM-PV-2Bit-1x16
![Screenshot 2024-09-18 at 10 27 18](https://github.com/user-attachments/assets/169eeed1-a891-49f0-8147-0e8b5d857e5b)
