### ISSUE TITLE
Running llama.cpp on android just prints out the question

### ISSUE THREAD

**Issue by Shreyas-ITB** [ggerganov/llama.cpp#712]
I ran llama.cpp on my android phone which has 8 threads and 8GB of ram in which around 7.16 GB is available, that is more than enough to run the 7B Alpaca model on it. But when i run it, it just repeats the question that i provided to it. I am using the `./examples/chat.sh` file. Why does it do that? How do i solve it?

**Comment by cmp-nct** [comment]
Just guessing: after prompt was processed there can be a noticeable delay until the completions start.
Also there are interactive modes that wait for return/enter.

**Comment by JackJollimore** [comment]
> I ran llama.cpp on my android phone which has 8 threads and 8GB of ram in which around 7.16 GB is available, that is more than enough to run the 7B Alpaca model on it. But when i run it, it just repeats the question that i provided to it. I am using the `./examples/chat.sh` file. Why does it do that? How do i solve it?

Hi, I've noticed that my device also with 8 threads performs terribly slow if i try and use the default thread options.

I think it's because my device labels the cores as 0 to 7 instead of 1 to 8, so I use '--threads 7', on my prompts because it's faster.

Perhaps you want to try '--threads 7' and see if it does more than print the question with the increased speed?

Good luck!
