### ISSUE TITLE
Train For Language Translation

### ISSUE THREAD

**Issue by nichellehouston** [ggerganov/llama.cpp#7178]
I want to train Llama 3 only for language translation what is dataset format for language translation and how can train?
My csv file content example:
{ "af": "Kom", "en": "Come on." }
{ "af": "Nie ingebed nie", "en": "Not embedded" }

**Comment by teleprint-me** [comment]
Might be useful: https://huggingface.co/datasets/mozilla-foundation/common_voice_17_0

Haven't had time to check, but it caught my attention for a bunch of reasons. It has included subtitles for each of the audio files including translations organized by language.

**Comment by stduhpf** [comment]
For format, why not train directly on your csv files? 
I don't think there's realy a good standard way to format prompts for a decoder-only LLM (like llama) for machine translation anyways. That's because translation is one of the few cases where using an encoder-decoder LLM (like t5) instead makes a lot more sense.
