### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by mike2003** [ggerganov/llama.cpp#7181]
I'm trying to run **llama-b2826-bin-win-cuda-cu12.2.0-x64.zip**, but nothing works! The main.exe or server.exe just terminates without any messages. What can I do to understand? Are there any logs?

win10x64
cudatk12.4
1660super

PS
I can run 
llama-b2826-bin-win-avx-x64.zip
llama-b2826-bin-win-noavx-x64.zip

**Comment by CISC** [comment]
Do you have the cudart and cublas DLLs in your path? If not, extract them from `cudart-llama-bin-win-cu12.2.0-x64.zip`.

**Comment by mike2003** [comment]
It didn't change anything. The program still terminates for no reason.

**Comment by arnfaldur** [comment]
Nothing in a computer happens "for no reason".
Try running the program from a terminal window. It should say something about what is happening.
This is most likely a path issue.

**Comment by eskeletor97** [comment]
I've had a similar issue few months ago. Cuda toolkit should technically be backwards compatible, but in my case when I tried to run CI builds it just insta segfaulted. When I compile on my own machine with 12.4 it works fine. It's a bit of a pain to setup on windows, but you'll have less issues in the long run.

**Comment by mike2003** [comment]
> Nothing in a computer happens

Of course I was talking only about this program. This program doesn't say anything.

two examples:
```
t:\llama-b2836-bin-win-avx-x64
λ main
Log start
main: build = 2836 (8c570c94)
main: built with MSVC 19.38.33135.0 for x64
main: seed  = 1715332631
llama_model_load: error loading model: llama_model_loader: failed to load model from models/7B/ggml-model-f16.gguf

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/7B/ggml-model-f16.gguf'
main: error: unable to load model

t:\llama-b2836-bin-win-avx-x64
λ
```
t:\llama-b2836-bin-win-cuda-cu12.2.0-x64
λ main

t:\llama-b2836-bin-win-cuda-cu12.2.0-x64
λ
```

```

**Comment by eskeletor97** [comment]
Wait, can you run avx2? What cpu do you have? If you are running some old ivy/sandy bridge then they lack instruction sets to run this. I don't know if it's possible to compile cuda build without avx2.

**Comment by mike2003** [comment]
I don't have avx2

**Comment by eskeletor97** [comment]
I see. You'd need to compile it yourself to see if it's even possible. I think cuda CI builds are avx2 by default.

**Comment by Paperfox204** [comment]
I have the same problem it seems...

Build was compiled on Mac m1 with clang(`$make -j 4)`.

Output is as fellows:
```
Log start
main: build = 0 (unknown)
main: built with Apple clang version 14.0.0 (clang-1400.0.29.102) for arm64-apple-darwin21.6.0
main: seed  = 1718007622
llama_model_load: error loading model: llama_model_loader: failed to load model from models/7B/ggml-model-f16.gguf

llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'models/7B/ggml-model-f16.gguf'
main: error: unable to load model
```

**Comment by arnfaldur** [comment]
@Paperfox204 your problem is not so related as @mike2003 only had issues with the Cuda build on windows. 

@mike2003 I apologize for not being more clear before. You are asking volunteers for technical support. You did not follow the issue templates that are put there so people who don't know how to create good issues, create good issues.

The point I was making by saying nothing happens for no reason is both that there is always a reason, and that it is not a useful thing to say in the context. You should show the volunteers here some respect by putting effort into your request. Follow a provided template, or explain in detail what you've tried. The same goes for each comment.

I suggest this issue be closed. If it persists, it can be re-opened with a template or as a discussion were I think it belongs.
