### ISSUE TITLE
Expanding Swift Package Functionality 

### ISSUE THREAD

**Issue by spprichard** [ggerganov/llama.cpp#7186]
### Discussed in https://github.com/ggerganov/llama.cpp/discussions/7053

<div type='discussions-op-text'>
<sup>Originally posted by **FreakTheMighty** May  2, 2024</sup>
I'm using the example swiftui application as a starting place and would like to add grammar constraints. I'm a bit stuck on how to actually load a grammar file. In the c++ examples, the [grammar_parser::parse](https://github.com/ggerganov/llama.cpp/blob/master/common/grammar-parser.h), but in swift this API doesn't appear to be exposed.

Any suggested on how to load a grammar would be much appreciated.
</div>

Would it be possible to expand the Swift package to include more functionality found in `common`?

**Comment by ggerganov** [comment]
The logic is that everything inside the `examples` folder is a demonstration of how to use the `llama.cpp` library that currently has only a C-style API defined in `llama.h`. There are many useful bits in the `examples` and especially in `common` that with time, as they mature, make their way into the core `llama` library, available through the C-style API. The grammar parser is one such thing that will at some point get tightly integrated - just need developer time to find the best way

We don't want to expose a C++ API of the stuff in `common` because C++ APIs are very difficult to adopt compared to C-style APIs and it is not worth the effort.

> Would it be possible to expand the Swift package to include more functionality found in common?

For now, it's better to replicate the `common` functionality that you are interested in your Swift project.

**Comment by spprichard** [comment]
Sweet! Makes sense. Thank you for the explanation 👍

**Comment by joyyang1215** [comment]
llama-sampling.cpp and llama-grammar.cpp are now in llama.cpp/src (rather than in common/). So, does it mean that it is possible to use these libraries inside Swift? (by import llama?)
