### ISSUE TITLE
Bug: gpu hang after bde7cd3cd949c1a85d3a199498ac98e78039d46f

### ISSUE THREAD

**Issue by rhjdvsgsgks** [ggerganov/llama.cpp#7730]
### What happened?

after bde7cd3cd949c1a85d3a199498ac98e78039d46f . inferring any llama3 q6 model will cause a gpu hang. previous version (a5735e4426b19a3ebd0c653ad8ac01420458ee95) is not affected

### Name and Version

bde7cd3cd949c1a85d3a199498ac98e78039d46f
using vulkan backend

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```
radv/amdgpu: The CS has been cancelled because the context is lost. This context is innocent.
terminate called after throwing an instance of 'vk::DeviceLostError'                   what():  vk::Queue::submit: ErrorDeviceLost
```

dmesg
```
[drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring comp_1.1.0 timeout, signaled seq=898, emitted seq=899
```

**Comment by slaren** [comment]
@0cc4m this is probably my bad, I made some changes to the way views are initialized in ggml-backend that may have created this issue. Views are now initialized in the buffer of their parent tensor, instead of on the compute buffer. The reason I made this change is because I came to the conclusion that allocating views on the compute buffer cannot work reliably because the compute buffer is not always of the same type as the buffer used to allocate the tensor originally, and backends should be able to use the same extra as their parent anyway. I thought it was safe to make this change because the CUDA backend no longer needs extras for normal buffers, but I didn't realize that the vulkan backend still does.

Looking at the `ggml_tensor_extra_gpu` of the vulkan backend I think it should be possible to do this, the only change is that you would have to calculate the offset as `t->extra->offset + t->extra->view_offs`. Essentially, add the offset of the view to the offset of the extra. Does that sound right?
