### ISSUE TITLE
I am running two socket servers, and the CPU usage is at 50%

### ISSUE THREAD

**Issue by superLiben** [ggerganov/llama.cpp#7812]
### What happened?

I am running GMME 7B and see the CPU usage at 50%. How can I increase the usage to 100%? I want to see the number of performance tokens per second at the CPU's maximum MHz
![image](https://github.com/ggerganov/llama.cpp/assets/138005314/a9eb1721-52fd-4900-9113-95e4d8cd3e68)
![aa](https://github.com/ggerganov/llama.cpp/assets/138005314/1ca72bee-568d-498e-be10-c834ac754048)
![bb](https://github.com/ggerganov/llama.cpp/assets/138005314/e148510c-7491-4123-a322-66b2148e5c8d)

### Name and Version

[root@localhost llama.cpp]# ./main --version
version: 3104 (a5cabd76)
built with cc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4) for x86_64-redhat-linux
[root@localhost llama.cpp]#

**Comment by superLiben** [comment]
I am using an Ampere(R) Altra(R) Max Processor M128-30 CPU @ 3.0GHz single-socket server, capable of running all CPUs. Does llama.cpp not support cross-socket?
![cc](https://github.com/ggerganov/llama.cpp/assets/138005314/2eca16d3-ccff-43be-8540-4d72c6bd3946)
![dd](https://github.com/ggerganov/llama.cpp/assets/138005314/29ca5123-96db-4d21-85c9-52927caeee7f)

**Comment by Rotatingxenomorph** [comment]
On CPU the memory bandwidth limits token/s. In most cases 100% cpu during inference would mean something was wrong and probably will be giving worse tokens/s. A good starting point is for the -t to be set at one less than the number of physical cores and test from there.

**Comment by jrichey98** [comment]
> Does llama.cpp not support cross-socket?

It does support cross-socket fine. I run it on E5-2667v2 CPUs. They are memory bandwidth limited, not CPU limited (8-ch DDR3 1866).

> On CPU the memory bandwidth limits token/s. In most cases 100% cpu during inference would mean something was wrong and probably will be giving worse tokens/s. A good starting point is for the -t to be set at one less than the number of physical cores and test from there.

I have ran llama.cpp on a 5950X and a 2xE5-2667v2 (2.5x performance of the 5950X) system. I've found that it's memory bandwidth limited usually (2x2666=5332 vs 8x1866=14928). 

- On the E5-2667v2 it benefited a little up to the number of cores on the CPU, probably because those CPUs are older and less powerful.
- On the 5950X it was massively memory limited however. I got best performance of -t 6, with very little performance penalty and the rest of the system running much better with -t 4.

You just have to test and see how many tokens/s you get with each setting for your system. But likely the issue isn't CPU, it's memory bandwidth.

Make sure to specify the optimal number of threads, and I know at lest on dual socket X86 systems the --numa option is very helpful.
