### ISSUE TITLE
No successful releases from CI in the last 2 days.

### ISSUE THREAD

**Issue by Spacellary** [ggerganov/llama.cpp#7828]
### What happened?

The last successful CI build with a release was [9380799867](https://github.com/ggerganov/llama.cpp/actions/runs/9380799867), is there a rework of the CI workflow underway or is that an unplanned issue?

These are used by many so I believe their absence isn't ideal, so I decided to inquiry formally.

The last [successful run](https://github.com/ggerganov/llama.cpp/actions/runs/9392640574) seems to have skipped the release and [the others after that](https://github.com/ggerganov/llama.cpp/actions/workflows/build.yml) aren't complete.

### Name and Version

Last successful CI run commit, skipping release:

[.github/workflows/build.yml ](https://github.com/ggerganov/llama.cpp/blob/8641ae1f5ab78bd3cd21f59f2b968f3d033d14f0/.github/workflows/build.yml)at [8641ae1](https://github.com/ggerganov/llama.cpp/commit/8641ae1f5ab78bd3cd21f59f2b968f3d033d14f0)

### Relevant log output

```shell
https://github.com/ggerganov/llama.cpp/actions/runs/9392640574
```

**Comment by amakropoulos** [comment]
@ggerganov the issue is due to an upgrade of the windows runner image in GitHub Actions.
The [last runner image](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#visual-studio-enterprise-2022) released yesterday uses Visual Studio 17.10 while the [previous runner image](https://github.com/actions/runner-images/blob/win22/20240514.3/images/windows/Windows2022-Readme.md#visual-studio-enterprise-2022) used 17.9.
17.10 no longer supports CUDA versions < 12.4.
I'm trying to make the compilation work for version 12.4 supported by [Jimver/cuda-toolkit v0.2.15](https://github.com/Jimver/cuda-toolkit/releases/tag/v0.2.15).

**Comment by amakropoulos** [comment]
Actually windows-2019 may work, I was testing on some additional code from my side failing :).

**Comment by bartowski1182** [comment]
Thanks for asking them and providing details, was wondering this myself as I prefer to use official releases and had to even roll back cause the imatrix args were broken with a release but then fixed since releases stopped

**Comment by turboderp** [comment]
@bdashore3 Worked out a stopgap solution for ExLlamaV2, explained [here](https://github.com/actions/runner-images/issues/10004#issuecomment-2155695838).

It would probably work here as well.

**Comment by Spacellary** [comment]
Similar:

https://github.com/MeshInspector/MeshLib/pull/2828

https://github.com/wpilibsuite/allwpilib/pull/6725
