### ISSUE TITLE
Feature Request: Add Paligemma support

### ISSUE THREAD

**Issue by nischalj10** [ggerganov/llama.cpp#7875]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Its a really solid model and has a lot of requests in the [discussions ](https://github.com/ggerganov/llama.cpp/discussions/7296)

### Motivation

Pulls way above its weight and has really good ocr capabilites

**Comment by iamlemec** [comment]
Yup! Work in progress at #7553.

**Comment by TalonBvV** [comment]
Hey there, I hope all is well, any luck getting the model to run? 

I'm quite curious, I managed to use Clip.cpp quantization to quantize phi-3 vision's projector and Llama.cpp quantization to quantize the language model component, the result was a pretty useful VLM with a total size of 1.5GB.
While this is great, because it proves that VLM models can be smaller and still accurate, but in terms of overall functionality Paligemma is a much better choice, it has baked in bounding box abilities which on it's own has limitless possibilities.
