### ISSUE TITLE
Encounter the "newline in constant" error while compiling with MSVC

### ISSUE THREAD

**Issue by Yan-Xiangjun** [ggerganov/llama.cpp#8334]
### What happened?

I used  `cmake -B build` to generate a Visual Studio solution. After that, when compiling `test-grammar-integration.cpp` with MSVC, the error "newline in constant" occurred.
Here is the position of the error:
![test1](https://github.com/ggerganov/llama.cpp/assets/126038017/8d76a0f1-90dd-451d-9847-3c2daa6658ba)
This is a detailed description of the error: https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2001?view=msvc-170&f1url=%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(C2001)%26rd%3Dtrue

### Name and Version

The version of llama.cpp is b3325.
I use Windows 11, Visual Studio 2022 17.8.2 and MSVC 19.38.33130.0.

### What operating system are you seeing the problem on?

Windows

**Comment by shibe2** [comment]
Maybe string literals with non-ASCII characters should have `u8` prefix, for example:

    u8"🔵🟠✅abc❌🟠🔵"

Also, build scripts should ensure that these source files are treated by compiler as encoded in UTF-8. For example, relevant GCC option is -finput-charset=UTF-8.

Alternatively, non-ASCII characters can be represented with `\u` and `\U` escapes, for example:

    u8"\U0001F535\U0001F7E0\u2705abc\u274C\U0001F7E0\U0001F535"

Yet another alternative is to use `\x` escapes instead of `u8` prefix, for example:

    "\xF0\x9F\x94\xB5\xF0\x9F\x9F\xA0\xE2\x9C\x85abc\xE2\x9D\x8C\xF0\x9F\x9F\xA0\xF0\x9F\x94\xB5"

Though this is even less readable.

**Comment by fairydreaming** [comment]
Likely not related, but I see a missing comma on the screenshot near the end of Failing strings.

**Comment by shibe2** [comment]
Missing comma was added, but unspecified character encoding was not addressed, I believe. Test strings are in UTF-8 in the file, and need to be in UTF-8 at runtime. This works as expected in most cases, but it relies on default behavior/encoding, which may be different in different compilers and in different environments with the same compiler.
