### ISSUE TITLE
tiktoken package missing from requirements

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#8466]
Some models require tiktoken package for convertion to work.
But titoken package is missing in requirements.txt.

THUDM/codegeex4-all-9b  is an example of that
llama.cpp/convert_hf_to_gguf.py will fail saying that tikoken package is needed but not found.

obviously a pip install titoken solves the problem.

**Comment by compilade** [comment]
This was also discussed when StableLM2 1.6B came out: <https://github.com/ggerganov/llama.cpp/pull/5052#issuecomment-1902670364>

TL;DR `requirements.txt` is for required dependencies, not optional ones, but the `*-extra` Nix devShells do include `tiktoken` because there's no equivalent to `pip install` there.
