### ISSUE TITLE
Feature Request: Support T5-based encoder-only models

### ISSUE THREAD

**Issue by Ronsor** [ggerganov/llama.cpp#8900]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Add support for T5-based encoder-only models (T5EncoderModel), similar to BERT models.

### Motivation

T5 encoder-decoder models are already supported, but most uses of T5 now involve only using the encoder to generate embeddings used to condition another model. Examples of this include Stable Diffusion 3 and Flux, which use a T5-based encoder.

**Comment by fairydreaming** [comment]
I did some quick tests and this is doable by using the existing LLM_ARCH_T5. I just added TENSOR_NOT_REQUIRED to all decoder tensors and added copying embeddings to lctx.embd in llama_encode_internal() so they can be retrieved by using API. I also did some crude tweaks to llama-embedding so it could handle --pooling none to print the result and voila:
```
embedding 0:  0.034207  0.165456  0.043617  ... -0.118661 -0.024527  0.070433 
embedding 1:  0.006645 -0.067356  0.085842  ... -0.212173  0.138131 -0.100815 
embedding 2:  0.057161  0.033909  0.050772  ... -0.069782 -0.098177 -0.122601 
embedding 3: -0.094016 -0.060146 -0.163193  ... -0.155676 -0.087803 -0.142278 
embedding 4: -0.076453  0.009360 -0.273724  ...  0.314213  0.047072 -0.094450 
embedding 5:  0.124635 -0.044540 -0.290185  ...  0.153005 -0.019226 -0.034184 
embedding 6:  0.134545 -0.102433 -0.017779  ...  0.038204 -0.120626 -0.134293 
embedding 7: -0.101406 -0.147312  0.043289  ...  0.082086 -0.052209  0.048596 
embedding 8: -0.076622 -0.044421 -0.009141  ... -0.001682  0.021479 -0.032543 
embedding 9: -0.167773  0.019032 -0.047412  ...  0.000374 -0.013778  0.090567 
embedding 10: -0.003602 -0.008351 -0.000150  ... -0.006356  0.006488  0.002825
```
while embeddings computed by using tensorflow are:
```
tensor([[[ 3.4144e-02,  1.6549e-01,  4.3646e-02,  ..., -1.1866e-01, -2.4421e-02,  7.0458e-02],
         [ 6.6725e-03, -6.7302e-02,  8.5827e-02,  ..., -2.1209e-01, 1.3815e-01, -1.0079e-01],
         [ 5.7131e-02,  3.3918e-02,  5.0821e-02,  ..., -6.9742e-02, -9.8140e-02, -1.2262e-01],
         ..., 
         [-7.6639e-02, -4.4381e-02, -9.0777e-03,  ..., -1.7003e-03, 2.1491e-02, -3.2551e-02],
         [-1.6784e-01,  1.9058e-02, -4.7421e-02,  ...,  3.4928e-04, -1.3742e-02,  9.0553e-02],
         [-3.6018e-03, -8.3508e-03, -1.5040e-04,  ..., -6.3572e-03, 6.4878e-03,  2.8254e-03]]], grad_fn=<MulBackward0>)
```

Alternatively we could add another architecture (e.g. LLM_ARCH_T5ENCODER) and maybe reuse some code from build_t5(). This seems like a cleaner approach as in this case it would be known if the model is encoder-only or encoder-decoder (is there any other simple way to get this information?). 

There is already llama_model_has_encoder() in the API, I think it's a good idea to also add llama_model_has_decoder() since after implementing this all three combinations (encoder-only, encoder-decoder, decoder-only) would be possible.

@ggerganov any thoughts?

**Comment by Ronsor** [comment]
I actually attempted the same thing; however, this resulted in SIGSEGV with `llama-server --embedding` due to the missing decoder layers. I'm not familiar enough with the current llama.cpp codebase to determine the best way to fix that.

**Comment by ggerganov** [comment]
@fairydreaming Both suggestions (`LLM_ARCH_T5_ENCODER` and `llama_model_has_decoder()`) sound good to me.

**Comment by fairydreaming** [comment]
@Ronsor Ah, the llama-server. Unfortunately, I don't feel confident enough to dig into it either.

**Comment by fairydreaming** [comment]
@Ronsor I just merged support for this in master, so you can try it now. The llama-server still doesn't handle T5 (neither encoder-only nor encoder-decoder variants), so for now you have to use llama-embedding tool to check the resulting embeddings.
