### ISSUE TITLE
Feature Request: Req to support Structured output and JSON schema to GBNF

### ISSUE THREAD

**Issue by jkfnc** [ggerganov/llama.cpp#8914]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Openai updated sdk with support for structured output and json schema. Is it possible to get similar feature added to completion api but compiling to GBNF grammar. https://platform.openai.com/docs/guides/structured-outputs

### Motivation

This will enable feature parity with completions api.

**Comment by James4Ever0** [comment]
Made one proposal to solve this problem:

https://github.com/ollama/ollama/issues/6302

**Comment by webitube** [comment]
Llamasharp already supports GBNF grammars.  I've been using them for a while now. Take a look at the LLama.Unittest/GrammarTest.cs for example usage.
It's a little convoluted, but it works. You have to create a SafeLLamaGrammarHandle for your grammar and pass that handle in your InferenceParams.
Just make sure you use a Clone() of the handle instead of the original handle. Otherwise, it would be disposed afterwards.
