### ISSUE TITLE
[Feature Request] Add batch processing for input prompt data in embedding mode.

### ISSUE THREAD

**Issue by AL-Kost** [ggerganov/llama.cpp#893]
It would be nice to add batch processing for input prompt data in embedding mode.
I.e., read prompts from a file and output a map of prompts and their embeddings.
It seems that this can be done by modifying the logic of the `-f` flag for embedding mode.

**Comment by rjadr** [comment]
I second this. I've been working on integrating llama.cpp in langchain, but the retrieval of embeddings is terribly slow since we can only pass [single strings](https://github.com/hwchase17/langchain/blob/master/langchain/embeddings/llamacpp.py#L111) (for which the model is loaded anew every time). Batch processing embeddings would be very helpful here, preferably by being able to pass a list of strings in the CLI.
