### ISSUE TITLE
obtain attention matrices during inference, similar to the output_attentions=True parameter in the transformers package

### ISSUE THREAD

**Issue by yuhkalhic** [ggerganov/llama.cpp#9122]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

I'd like to propose a new feature for Ollama: the ability to access attention matrices and/or the KV-Cache during model inference. This functionality is similar to what's available in the Hugging Face Transformers library, where users can set output_attentions=True or access past_key_values.

### Motivation

I think it would be useful  for users to replicate some research such as article in arxiv(2404.06910, 2305.17118) etc

**Comment by marcov-dart** [comment]
I was looking how to do this and I think I figured it out.

examples/eval-callback gives an example on how to use the eval callback.
I took the code from eval-callback and put that into examples/embedding to hook up the callback.
That works fine. Only thing then is to identify the correct tensor.

I believe it is in llama-graph.cpp in function build_attn_mha on line 1122.
The line that says: kq = ggml_soft_max_ext(...)
So after that line I added:
ggml_set_name(kq, "kq");

The calback gives me 24 x {4, 4, 16, 1} tensors.
I am using multilingual-e5-large-instruct. Which has 24 blocks, 16 heads and my input was 4 tokens so that look ok I think.
