### ISSUE TITLE
Feature Request: Standalone Clip Example

### ISSUE THREAD

**Issue by TalonBvV** [ggerganov/llama.cpp#9292]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Add standalone Clip to llama.cpp for image and text encoding.

I wouldn't mind giving this a try, let me know which of these options sound better suited to the llama.cpp vision.

### Motivation

It would be highly beneficial to add CLIP into llama.cpp as a standalone component instead of only being a part of llava.
My reasoning is that CLIP.cpp maintained by @monatis does not conform to all the latest changes in llama.cpp and ggml and it does not compile on windows.

I tried to make a few changes to get it running on windows and I encountered issues relating to it's use of ggml, it was passing ggml_tensor pointers in place of float function arguments.

### Possible Implementation

This could be achieved in one of two ways:
1) Implement Clip in a new directory in llama.cpp examples to preform text & image encoding.
2) Add new Multimodel approach in llama-embeddings for generating text & image embeddings.

I would be happy to give this a shot utilizing the current implementation in llava... although I'm sure one of the lead contributors would make quick work of this.
Let me know which of the above sound better in terms of the llama.cpp vision.

**Comment by ggerganov** [comment]
Eventually we can add `libclip` to the project, similar to the existing `libllama`. The main things that would need to happen to achieve this:

- Remove STB dependency from `clip.cpp`
- Improve the C-style `clip` API
- Add tests and examples

As a directory structure, it can be organized like this:

- add `include/clip.h`
- add `src/clip.cpp`
- add `src/clip-[other].cpp` if needed

With time, the two libs can start sharing some common functionality when it makes sense (e.g. quantization, model loading, etc.).

The `examples/llava/clip` implementation can remain for the time-being, to not break the `llava` examples. But the goal would be eventually to replace it with the main `libclip` implementation.

Since this is quite an orthogonal change relative to all the things currently being developed I think it can be easily developed in a separate branch that would be kept up-to-date with `master` via regular rebasing. A draft PR would allow to keep an eye on the progress and discuss how to proceed.

If you are interested, feel free to initiate the implementation. I think the most important thing to do is to not aim for supporting complicated features and latest models, but instead to start with the basics, add enough tests at the start and figure out the best way to represent the image data.

**Comment by TalonBvV** [comment]
Excellent, I'll get started by implementing a POC just to see how I can best follow your guidelines, will keep in touch regarding the draft PR.

**Comment by rnddvsrt** [comment]
@TalonBvV Have you managed to produce a sample example on Clip serving?

**Comment by TalonBvV** [comment]
@rnddvsrt To some extent yes, I've managed to create an image dataset equalizer using the existing clip implementation in Llava for standalone image embedding in order to highlight which types of images in a dataset are not presented enough and provide the ability to extract an equalized subset of the dataset that represents all internal degrees' of images equally.

But I have not made a pull request as of yet, I want to clean it up before doing so.

I also have a few questions before I move forward, I just haven't had much time on my hands.

@ggerganov I would like to find out by you a few specifics:

1) Why remove STB, is the idea to manage image reading/writing within Llama.cpp?
    1.1) if so, would it be ideal to add full multi media functionality to all for image/video/audio
2) After using the clip functionality that's already implemented, I can now see that it's already pretty accurate and complete.
    1.2) Seeing as the implementation is solid, would you want to add a higher level api to clip for image/text embedding use?
           If you would like this, would you want it to be done within clip? or added to embeddings example?
           Or maybe implement the API in clip and then add support for clip in the embeddings example?

**Comment by ggerganov** [comment]
In recent discussions about multi-modality (#11139, #11292), we seem to be aiming for a common API for all models including CLIP. So I don't think that the `libclip` is still on the table. More likely the functionality will end-up being a part of `libllama`.

1.1) `llama.cpp will receive just the image data in a very basic format - pixels with color. It will be the user's responsibility to provide the images in that format and they can use any library to do so. So there is no need to add image format read/write functionality in `llama.cpp`

1.2) Check the linked discussion to see what is currently being planned for the API.

**Comment by ngxson** [comment]
The `clip.cpp` actually contains multiple parts inside it, like image codec, image preprocessing, cgraphs for transformers, and cgraphs for multi-modal projector.
- image codec is provided by STB. The only thing it does is to read file from different formats (JPG/PNG/GIF/etc) and convert it into 2d array of RGB pixels (aka bitmap). Thus, we can just do it outside of the library, user can freely choose either they uses STB or something else like Magick++, Pillow, etc
- image preprocessing is just a simple set of function (resize, crop, etc) that operates on bitmap. They are just simple 2d for loop, will eventually be in `libllama`
- graphs for transformers and multi-modal projector will soon be part by `llm_build_context` in `llama.cpp`, which already contains the many cgraphs for transformers.
