### ISSUE TITLE
Bug: rpc-server segment fault when running with no kv cache offloading

### ISSUE THREAD

**Issue by jack2007** [ggerganov/llama.cpp#9337]
### What happened?

I have a rpc server 10.90.26.1:50052, it's OK with following command.
./llama-cli -m /data/zsq/models/qwen2-7b-instruct-q8_0.gguf --repeat_penalty 1.0 --color -i -r "User:" -f prompts/chat-with-bob.txt --rpc 10.90.26.1:50052  -ngl 1000

When I add -nkvo para to the command, the rpc server crashed.
./llama-cli -m /data/zsq/models/qwen2-7b-instruct-q8_0.gguf --repeat_penalty 1.0 --color -i -r "User:" -f prompts/chat-with-bob.txt --rpc 10.90.26.1:50052  -ngl 1000 -nkvo

No offoading kv cache  only slow down the token generation a little, but it occupies a lot cuda buffer when offloading.
It would be wonderful if I can run rpc server with no kv offloading, that means I can run bigger model like llama3.1-70B  with 2 or 3 machines.

Thanks.

### Name and Version

# ./llama-cli --version
version: 0 (unknown)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
git code: b3651

**Comment by slaren** [comment]
@rgerganov Part of the problem here is that sometimes backends may receive tensor views in the graph that use buffers that are not supported by the backend. These operations are no-ops and are ignored by the backends, so generally this is ok, but it causes problems with the RPC backend. I have pushed a partial fix to https://github.com/ggerganov/llama.cpp/commit/c3e2bb6dcf41b0a7ffca19469eab4ece50595372, but there is still an issue in that the number of tensors that need to be allocated in the ggml context is underestimated, and I am not sure how that should be fixed. Feel free to take that code if you are interested in fixing this, I won't continue working on this for now.

**Comment by rgerganov** [comment]
> but there is still an issue in that the number of tensors that need to be allocated in the ggml context is underestimated, and I am not sure how that should be fixed

I think the problem was that `buf_size` was declared as `static`, a stupid mistake made by me

**Comment by jack2007** [comment]
Verified in release b3716.
