### ISSUE TITLE
Question regarding distributed computing...

### ISSUE THREAD

**Issue by snapo** [ggerganov/llama.cpp#946]
I have currently access to 20 old computers, each with 32GB ram and 4 cores, 256gb ssd, 1 gbit speed network, connected to a 48port switch. (i could get a lot lot more computers but i dont have enough electricity currently)
Would it be somehow possible to distribute the llama model with llama.cpp to the 20 computers to being able to run the 65b model at a moderate speed?
What would i have to do to distribute the model on many computers to run it on cpu?
i am only interested in inference, not training..... for training i can rent cloud gpu's.

Thanks for any input that would help me / recommendation / problems.

What i see as a problem is how to split the model / models (in case i use other models) efficiently so that network bandwidth isnt the limiting factor.

**Comment by Loufe** [comment]
Consider the discussion in [this PR](https://github.com/ggerganov/llama.cpp/pull/934). They're discussing limiting much more integrated high-core count CPUs to only 8 (or 4) as more cores does not seem to positively correlate with better performance. I might be misunderstanding, but I think you need faster threads, not more.

**Comment by jon-chuang** [comment]
> more cores does not seem to positively correlate with better performance

This is somewhat false. The issue was the interference of hyperthreaded logical "cores" and Efficiency cores (E-cores) on M1 and recent Intel chips (alderlake and above).

> What would i have to do to distribute the model on many computers to run it on cpu?

I think it's a better idea to stick to a single node. Distributed inference is a pretty terrible idea and has high overhead. I would suggest sticking to the model that can run on a single node, and then load distributing your requests over those nodes.

**Comment by jon-chuang** [comment]
There already exists many ways to distribute across tensor and operator. See e.g. https://alpa.ai/index.html

I believe this is out of scope for llama.cpp

**Comment by ggerganov** [comment]
From `ggml` point of view, such distributed computing is completely possible. You simply have to partition your transformer the way you like and load the respective tensors on the respective nodes. You then create the partial compute graphs and should be ready to compute.

The main thing to solve is make the nodes communicate with each other - for example over the network.
This is something that will likely never be part of `ggml` or even `llama.cpp` since it will will bring 3rd party dependencies. So a distributed computing example will likely have to be demonstrated in a separate respository / fork.

Unless, you find a very elegant way to pass and queue messages between the nodes that fits in a few hundred lines of C/C++ code. In that case, this can become a `llama.cpp` example and I think it will be of great interest. Even if it works only on Linux for example.

**Comment by jon-chuang** [comment]
> Unless, you find a very elegant way to pass and queue messages between the nodes that fits in a few hundred lines of C/C++ code. In that case, this can become a llama.cpp example and I think it will be of great interest. Even if it works only on Linux for example.

If you accept MPI as a dependency, this is actually very possible. 

The test should be written using multiple processes to simulate multiple nodes.
