### ISSUE TITLE
[CANN]Feature Request: Support OrangeAIPRO 310b CANN

### ISSUE THREAD

**Issue by StudyingLover** [ggerganov/llama.cpp#9481]
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Follow-up on issue https://github.com/ggerganov/llama.cpp/issues/9423, I hope that llama.cpp can support running on the Orange Pi AI PRO.

### Motivation

Currently, llama.cpp has incomplete support for CANN. There are quite a few Orange Pi AI PRO users, many of whom have a need for deploying large models.

**Comment by hipudding** [comment]
May I ask what scenario you are using with llama.cpp? We are analyzing the usage scenarios of llama.cpp with Ascend NPU, and I want to collect some information through users.

**Comment by StudyingLover** [comment]
> Ascend NPU

We are trying to deploy edge-side models on Orange AI PRO and enable multi-agent collaboration between edge and cloud models. We need a feasible solution to quickly deploy large models. We believe llama.cpp is one of the best options, while another alternative is Ollama. However, we have noticed that Ollama does not support Ascend NPU (CANN) acceleration.

**Comment by hipudding** [comment]
Thanks. For 310B, it does need more time to support, because the interface of aclnn and AscnedC is not the same with other type of chips. Ollama use llama.cpp as it inferencing engine. We are working on it too.

**Comment by freesrz93** [comment]
> Thanks. For 310B, it does need more time to support, because the interface of aclnn and AscnedC is not the same with other type of chips. Ollama use llama.cpp as it inferencing engine. We are working on it too.

Hello! Sorry to bother you, but can you briefly summarize the work needed to support Ascend 310B?

I tried to run `whisper.cpp` on OrangePi AI PRO, and here is my steps: 
1. I found that some API are not available under `Ascend RC`, such as `aclrtMemGetAllocationGranularity` , which is unsupported:  https://github.com/ggerganov/llama.cpp/blob/26a8406ba9198eb6fdd8329fa717555b4f77f05f/ggml/src/ggml-cann/ggml-cann.cpp#L120-L125 because this function always return 2MB, I use a constant directly.

2. Some other memory-related APIs like `aclrtMallocPhysical` is not supported, and I noticed there was a `ggml_cann_pool_leg` (but seems not used), and I modified the code to use it to replace `ggml_cann_pool_vmm`:
 https://github.com/ggerganov/llama.cpp/blob/26a8406ba9198eb6fdd8329fa717555b4f77f05f/ggml/src/ggml-cann/ggml-cann.cpp#L468-L475

3. After these two modifications, the first error encountered is operator-related, when calling `aclnnIm2colGetWorkspaceSize`. I wonder if this means we have to implement all unsupported operators? Or there are alternative ones in `acl` itself?

**Comment by hipudding** [comment]
@freesrz93 We are not start support for 310B yet, I'm not sure what should be done to support 310B. 
There may exists some interface which not support for 310B, you need to replace it with other similar interfaces.
There implemented two mempools, you can use any of them.
