### ISSUE TITLE
Bug: Build fails on i386 systems

### ISSUE THREAD

**Issue by yurivict** [ggerganov/llama.cpp#9545]
### What happened?

```
/wrkdirs/usr/ports/misc/llama-cpp/work/llama.cpp-b3761/ggml/src/ggml-vulkan.cpp:2629:5: error: no matching function for call to 'vkCmdCopyBuffer'
 2629 |     vkCmdCopyBuffer(subctx->s->buffer, staging->buffer, dst->buffer, 1, &buf_copy);
      |     ^~~~~~~~~~~~~~~
/usr/local/include/vulkan/vulkan_core.h:4750:28: note: candidate function not viable: no known conversion from 'vk::Buffer' to 'VkBuffer' (aka 'unsigned long long') for 2nd argument
 4750 | VKAPI_ATTR void VKAPI_CALL vkCmdCopyBuffer(
      |                            ^
 4751 |     VkCommandBuffer                             commandBuffer,
 4752 |     VkBuffer                                    srcBuffer,
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Version: 3761
clang-18
FreeBSD 14.1

### Name and Version

3761

### What operating system are you seeing the problem on?

BSD

**Comment by csbo98** [comment]
Could I analyse this in the next few days？

**Comment by yurivict** [comment]
Sure!

**Comment by UnitedMarsupials** [comment]
This seems to have been a problem with vulkan-headers rather than llama.cpp. Better yet, the problem is no longer reproducible in vulkan-headers 1.4.327 -- which is, what [graphics/vulkan-headers](https://freshports.org/graphics/vulkan-headers) installs at the time of this typing.

The [misc/llama-cpp](https://freshports.org/misc/llama-cpp), which @yurivict maintains, no longer needs to be marked "broken" on i386.
