### ISSUE TITLE
Bug: [vulkan] llama.cpp not work on Raspberry Pi 5

### ISSUE THREAD

**Issue by FanShupei** [ggerganov/llama.cpp#9801]
### What happened?

I notice https://github.com/ggerganov/llama.cpp/issues/5237 is the prior issue for the same bug. However, it was closed neither confirmed nor fixed.

Run with validation layer enabled, the validation layer reports some issues. I'd like to ask whether these issues is fixable, or it indicates the underlying GPU lacks important features to run llama.cpp (so it's unfixable).

Reproduce commad (run any model):
`VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation gdb build/bin/llama-bench -m models/llama32-1b-instruct-f16.gguf`

The full log generated by validation layer is too long. See https://pastebin.com/nRJgLFY4

### Name and Version

version: 3880 (f3fdcfaa) built with cc (Debian 12.2.0-14) 12.2.0 for aarch64-linux-gnu
Platform: Respberry Pi 5
OS: Debian 12
vulkan loader version: 1.3.239
vulkan device: V3D 7.1.7 (apiVersion: 1.2.255, 23.2.1)

**Comment by Abhranta** [comment]
If you get it running, please tell me the benchmarks numbers if you can. I would love to know if I am getting optimal numbers or not.

**Comment by CGCMC** [comment]
@FanShupei I think error 1 happens because the driver doesn't support the VK_EXT_descriptor_indexing extension.

**Comment by MikuAuahDark** [comment]
With recent llama.cpp (3d68f034dad53f0f27ad626b2732ef48fbcea4ee), looks like it's really not possible to run llama.cpp with Vulkan in Raspberry Pi 5 (8GB). For reference I'm trying to run SmolLM2 360m Q4 K_M and any attempt to run the model will result in `Error: Shared memory size too small for matrix multiplication.`.

So there yo have it, Raspberry Pi 5 simply lacked the necessary bits.

**Comment by tcs-christian-ulrich** [comment]
why is this issue closed ?

**Comment by akshaybabloo** [comment]
> driver doesn't support the VK_EXT_descriptor_indexing extension.

I don't think this is true. Running `vulkaninfo` gives

```
...
VK_EXT_descriptor_indexing                    : extension revision 2
...
```

I think it does support it

**Comment by davidscarth** [comment]
**Update:** There's a lot more stuff going wrong behind the scenes that needs fixing. Fixing shaders because there may be hardcoded values that exceed hardware limitations is probably the top one. Maybe that was what was going wrong so long ago.

---

You can get past the gating of the ggml-vulkan.cpp, but there is work to be done to properly fix whatever is going on here.

[vulkan-low-smem-optimized.patch](https://github.com/user-attachments/files/21799307/vulkan-low-smem-optimized.patch)
This patch can be applied against the current b6176, ggml-vulkan.cpp [5edf159](https://github.com/ggml-org/llama.cpp/commit/5edf1592fdb9131d01321aeef4241c6a34969e27)

*How the patch works:* When tiny SMEM GPUs are detected it gates it into a new path and picks Pi-friendly GEMM tiles. This is not a production-ready patch, it is just a proof-of-concept to let you compile and run things.

I applied the patch and compiled llama.cpp with these build flags: -DCMAKE_BUILD_TYPE=Release -DGGML_VULKAN=ON -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DGGML_NATIVE=ON -DGGML_LTO=ON -DGGML_CCACHE=OFF

You can now successfully run llama-cli with "-ngl 1" and it will load a layer into GPU. "-ngl 2" will work as well, a little slower, still garbled text.

*Results:* As soon as you load a layer into GPU, the output that gets spit out is garbled (Same as reported in issue 5237). Say "Hello!" to [google_gemma-3-1b-it-qat-Q4_0](https://huggingface.co/bartowski/google_gemma-3-1b-it-qat-GGUF) and get a mix of random languages and weirdness. Compare to "-ngl 0" on the same build and using the same "Hello!" prompt and it is coherent "What can I do for you? Do you have a question..."

**Comment by geerlingguy** [comment]
Do we need another new issue since this one is closed? And the bigger question I have is how much performance improvement there could be running models on the iGPU instead of CPU? The CM5 and Pi 5 now have 16 GB of RAM options, and they aren't terrible for a low power solution.

**Comment by odilitime** [comment]
Follow-up with current findings and a proposed fix:

- Tracking issue: https://github.com/ggml-org/llama.cpp/issues/26213
- PR: https://github.com/ggml-org/llama.cpp/pull/26214

In addition to the low-SMEM matmul path discussed here, V3D also needs WG≤256 handling (hardcoded `local_size`/`BLOCK_SIZE` 512 + GET_ROWS `wg_denoms` mismatch). After those fixes on Pi 5 we get coherent English decode on Vulkan, but it remains ~80× slower than CPU for TinyLlama — correctness/enablement, not a speed win.
