### ISSUE TITLE
server : remove self-extend features

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/llama.cpp#9859]
The extra logic added to support this functionality is a bit questionable (https://github.com/ggerganov/llama.cpp/pull/5195#issuecomment-1917507112) and it introduces too much complexity around the context management. With new models available where the training context is plenty (32k and even 128k), we should remove this feature in view of simplifying the server implementation and potentially look to re-introduce it in the future in a better way.

**Comment by ngxson** [comment]
Thanks for doing this. I think we can re-introduce it if the community really needs. I had a rough plan to refactor it in a "functional programming" way, but still quite hard to wrap my head around.

Side story, I first knew about the self-context feature when I used llama.cpp `main` example to build my first self-hosted chatbot. I was at school back then, not even graduated. The project was hacky but so funny. We've come a long way 😄

**Comment by jcuenod** [comment]
Fwiw, I have been using this on the gemma 2 27B model. Its context window is only 4k, but the model is quite strong relative to its peers.

**Comment by thot-experiment** [comment]
so the last usable build is [b3909](https://github.com/ggerganov/llama.cpp/releases/tag/b3909) correct? Just updated for Phi4 and was sad to find this broken, i'm in the same boat as @jcuenod, gemma2 27b is still the best available model in terms of reasoning x prompt adherence in my real world use and the only thing holding it back is the small context window, this feature is a must in order to make the model usable for RAG tasks
