### ISSUE TITLE
Bug: When I try to run `llama-server` with the `--embd-normalize` option, I encounter the following error:

### ISSUE THREAD

**Issue by xanhf** [ggerganov/llama.cpp#9863]
### What happened?

./llama-server --host 0.0.0.0 --port 8080 -m /path/to/model --embd-normalize 2 --embd-output-format json --embd-separator "<#sep#>"

### Name and Version

master版本

### Relevant log output

```shell
./llama-server --host 0.0.0.0 --port 8080 -m /path/to/model --embd-normalize 2 --embd-output-format json --embd-separator "<#sep#>"

error: invalid argument: --embd-normalize
```

**Comment by iamlemec** [comment]
Indeed. Currently the server doesn't implement those extra embedding options. In the case of `embd-output-format` and `embd-separator`, I don't think it would be applicable since the server always returns JSON (right?). But for `embd-normalize` this would definitely make sense.

Just checked, and it's only a simple two line fix to pass the `embd-normalize` param to `common_embd_normalize`. Might be worth a PR if none are opposed. I should check though, are you sure you need this? The default value for `embd-normalize` is already 2 (euclidean).

**Comment by dsull111** [comment]
Seems this is still an issue. Does this affect the Qwen3 embeddings model? There is comment about how it uses this flag that was once posted on their HF readme -- "In addition, when running the `llama-server`, you also need to manually normalize the output embeddings as `llama-server` currently does not support the `--embd-normalize` option." however this was removed in July.
