### ISSUE TITLE
85%+ of the llama model could be redundant

### ISSUE THREAD

**Issue by jxxp9** [ggerganov/llama.cpp#989]
Turns out that most LLM parameters are redundant, see https://aclanthology.org/2020.emnlp-main.398.pdf.
They run the experiment with BERT and XLNet. Code for the pruning is provided.
There's lots of room for improvement apparently, since LLama is very similar to those. If someone's interested, that could be a nice thing to try 😄

**Comment by Azeirah** [comment]
https://github.com/fdalvi/analyzing-redundancy-in-pretrained-transformer-models

**Comment by Azeirah** [comment]
I'm just skimming through the paper quickly, I'm no AI expert whatsoever, but I do think I see one problem: the datasets they use to determine reduncancy focuses on English only, LLaMa supports a lot more languages that just English, including coding languages which would be pruned completely with their datasets.

I don't think this is necessarily a show-stopping problem, it just means that in order to use this technique for LLaMa we'd need more datasets specifically suited for LLaMa. If you were to use their original dataset, LLaMa would become an English-only LLM.

> 3.1 To analyze the general redundancy in pre-trained
models, we use the **Penn Treebank development
set** (Marcus et al., 1993), which consists of roughly
44,000 tokens. For task-specific analysis, we use
two broad categories of downstream tasks – Se-
quence Labeling and Sequence Classification tasks.
For the sequence labeling tasks, we study core
linguistic tasks, i) part-of-speech (POS) tagging
using the Penn TreeBank, ii) CCG super tagging
using CCGBank (Hockenmaier, 2006), iii) seman-
tic tagging (SEM) using Parallel Meaning Bank
data (Abzianidze and Bos, 2017) and iv) syn-
tactic chunking using CoNLL 2000 shared task
dataset (Sang and Buchholz, 2000).

[The penn treebank development set](https://catalog.ldc.upenn.edu/docs/LDC95T7/cl93.html)

>  Building a large annotated corpus of English: the Penn Treebank

**Comment by jon-chuang** [comment]
See also SparseGPT/LLaMa https://github.com/lachlansneff/sparsellama, https://arxiv.org/abs/2301.00774

**Comment by cmp-nct** [comment]
I didn't dig into it yet just my 10 Cents: llama uses SwiGLU, Bert Gelu and others Relu.
SwiGLU seems a super-heavy activation to me which also increases the perceived neuronal density of the network.

Next is the already mentioned factor: if you use a limited training set then you basicaly lobotomize all areas you didn't train at all and you damage those areas you did not train enough and you'll remove a lot of the nuances the model learned making it more "pragmatic" and less "creative".
I agree that this type of optimization is interesting but it comes with not so trivial consequences and complications.

**Comment by Green-Sky** [comment]
@Azeirah 
>  the datasets they use to determine reduncancy focuses on English only, LLaMa supports a lot more languages that just English, 

this might be true, but it would still be beneficial for specific use cases. (eg english only)

the paper states for llama states:
> ... performs language identification with a fastText linear classifier to remove non-English pages and filters low quality content with an n-gram language model.

> languages, which use either the Latin or Cyrillic
scripts: bg, ca, cs, da, de, en, es, fr, hr, hu, it,
nl, pl, pt, ro, ru, sl, sr, sv, uk.

**Comment by netsvetaev** [comment]
just tomention: other Latin languages are very similar to English (same Latin word roots) and that other Cyrillic languages allow the model to be used as a translation engine (and make it more interesting for other countries).

**Comment by xloem** [comment]
I wonder if pruning can be kind of like a form of finetuning where the resulting model is much smaller. For example, what if one pruned using the instruct data people are finetuning on? Or using the output distributions of a larger model as in knowledge distillation? In the latter case the model could possibly increase in strength rather than decrease.

Today I found there is structured LLaMA pruning code at https://github.com/horseee/LLaMA-Pruning and https://github.com/VainF/Torch-Pruning .

**Comment by Alumniminium** [comment]
Has anyone pruned alpaca/vicuna and uploaded it somewhere?

**Comment by ivanstepanovftw** [comment]
There is also knowledge distillation technique. I would like to se if someone would distill 65B into 7B model.

**Comment by xloem** [comment]
what’s the sparsification news? (or was this issue closed inaccurately?)

**Comment by kripper** [comment]
1) @ggerganov have you considered keeping neuron activation statistics?

This could be used to prune (lobotomize) the model and remove unused "knowledge" to reduce the model size, required RAM and improve the inference performance.

The neuron usage statistics could be collected for a given set of use cases (eg. leave the model running in production for some months and then stick to that used knowledge only).

2) other interesting approach that doesn't require lobotomizing the model would be to lazy-load the model weights dynamically by partitions:

When new knowledge is required (because some neurons activated) the model will load those weight partitions.

Unused weight partitions could be removed from memory by disconnecting those unused neurons similar to how the OS manages cache.

**Comment by kripper** [comment]
Oh. Lazy loading has already been implemented in https://github.com/ggerganov/llama.cpp/pull/613/

Can you please confirm that unused weight partitions are disconnected and not evaluated to improve inference performance?
